### PR TITLE
Add more tests and fixes for `$collStats` aggregation stage

### LINKED ISSUE #2349: Add more tests for `$collStats` aggregation stage
### What should be done?

Add tests for the following requests:
- `db.values.aggregate([{$count:"before"},{$collStats:{count:{}, storageStats:{}}},{$count:"after"}])`
- `db.values.aggregate([{$collStats:{count:{}, storageStats:{}}},{$count:"after"}])`

Also, check TODOs with the issue number for other possible cases, the error code is currently not correct.

### Where?

`integration/aggregate_stats_compat_test.go`
See also TODOs in the code.

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #2349.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/aggregate_stats_compat_test.go [hunk 1]
```diff
@@ -127,18 +119,49 @@ func TestAggregateCompatCollStats(tt *testing.T) {
 						nonEmptyResults = true
 					}
 
-					// Check the returned values when possible
-					// TODO https://github.com/FerretDB/FerretDB/issues/2349
```
Comment (chilagrow) [inline integration/aggregate_stats_compat_test.go:131]: Sizes of `storageStats` sanity check is done in https://github.com/FerretDB/FerretDB/pull/3538/files#diff-81f1b3fd332849d4efcb1ed0c8d183e19ecef6105d824a6a50eaf0482336ffe6

File: integration/aggregate_stats_compat_test.go [hunk 2]
```diff
@@ -23,74 +23,66 @@ import (
...
-		collStats  bson.D                   // required
+		pipeline bson.A // required
+
 		resultType compatTestCaseResultType // defaults to nonEmptyResult
+		skip       string                   // skip test for all handlers, must have issue number mentioned
 	}{
-		"NilCollStats": {
-			collStats:  nil,
-			resultType: emptyResult,
-		},
```
Comment (chilagrow) [inline integration/aggregate_stats_compat_test.go:39]: Test cases that produce error are moved to `TestAggregateCollStatsCommandErrors` to check error message

**Review by AlekSi — APPROVED** [review]

**Review by noisersup — APPROVED** [review]
