### PR TITLE
Fix exponential backoff minimum duration

### LINKED ISSUE #1720: Use exponential backoff with jitter
### What should be done?

We should use exponential backoff with jitter in places where we wait for something.

See https://aws.amazon.com/ru/blogs/architecture/exponential-backoff-and-jitter/

### Where?

Places that use `ctxutil.Sleep`, `time.Sleep`, `context.WithTimeout`, etc.

### Definition of Done

- no new external dependency;
- unit test for math added;
- spot refactorings done.

### PR DESCRIPTION
**Pull request by noisersup**
# Description

Closes #1720.

## Readiness checklist

* [x] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/util/ctxutil/ctxutil.go [hunk 1]
```diff
@@ -74,7 +74,9 @@ func DurationWithJitter(cap time.Duration, retry int64) time.Duration {
 
 	maxMilliseconds := float64(base.Milliseconds()) * math.Pow(2, float64(retry))
 	capMilliseconds := float64(cap.Milliseconds())
-	lowestValue := int64(math.Min(capMilliseconds, maxMilliseconds))
 
-	return time.Duration(rand.Int63n(lowestValue)) * time.Millisecond
+	lowestValue := int64(math.Min(capMilliseconds, maxMilliseconds)) - 100
+
+	// Math/rand is good enough because we don't need the randomness to be cryptographically secure.
+	return time.Duration(rand.Int63n(lowestValue)+100) * time.Millisecond
```
Comment (AlekSi) [inline internal/util/ctxutil/ctxutil.go:81]: I think that would panic with `cap = 50 * time.Millisecond`, for example. Please add a test

Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go:81]: Should we add a comment that provided cap cannot be smaller than `100ms`, or should we for example decrease min to 0ms if the cap is smaller than 100ms?

Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go:81]: Also, do we even need minimum jitter?

File: internal/util/ctxutil/ctxutil.go [hunk 2]
```diff
@@ -61,10 +61,10 @@ func SleepWithJitter(ctx context.Context, d time.Duration, attempts int64) {
 	<-sleepCtx.Done()
 }
 
-// DurationWithJitter returns an exponential backoff duration based on retry with random jitter.
-// The maximum sleep is the cap. The minimum duration is at least 100 milliseconds.
+// DurationWithJitter returns an exponential backoff duration based on retry with random "full jitter".
+// https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
 //
-// Math/rand is good enough because we don't need the randomness to be cryptographically secure.
+// The maximum sleep is the cap. The minimum duration is at least 100 milliseconds.
```
Comment (rumyantseva) [inline internal/util/ctxutil/ctxutil.go:67]: I think 100 milliseconds as the minimum duration is too much. I'd do something like 3-5 milliseconds, and then if it didn't help, we increase it within the next retry.

File: internal/util/ctxutil/ctxutil.go (hunk 1 above)
Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go]: For now I've updated description of function to mention expected parameters, added custom panic message similarly to the one that we already have for negative `retry`, and added test case that validates if it actually panics.

File: internal/util/ctxutil/ctxutil.go (hunk 2 above)
Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go]: Done

File: internal/util/ctxutil/ctxutil.go [hunk 3]
```diff
@@ -61,20 +62,28 @@ func SleepWithJitter(ctx context.Context, d time.Duration, attempts int64) {
...
-// The maximum sleep is the cap. The minimum duration is at least 100 milliseconds.
+// DurationWithJitter returns an exponential backoff duration based on retry with random "full jitter".
+// https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
 //
-// Math/rand is good enough because we don't need the randomness to be cryptographically secure.
+// The maximum sleep is the cap. The minimum sleep is at least 3 milliseconds.
+// Provided cap must be larger than minimum sleep, and retry number must be a positive number.
 func DurationWithJitter(cap time.Duration, retry int64) time.Duration {
 	const base = time.Millisecond * 100
+	const minMilliseconds = 3
```
Comment (chilagrow) [inline internal/util/ctxutil/ctxutil.go:72]: It's a bit weird to see `base` as Duration and `minMilliseconds` as int. Could we use same unit here? :hugs:

**Review by chilagrow — COMMENTED** [review]
Just tiny comment :hugs: nice work!

File: internal/util/ctxutil/ctxutil.go [hunk 4]
```diff
@@ -61,20 +62,28 @@ func SleepWithJitter(ctx context.Context, d time.Duration, attempts int64) {
...
+	if cap.Milliseconds() <= minMilliseconds {
+		panic(fmt.Sprintf("cap must be larger than min sleep (%dms)", minMilliseconds))
+	}
+
 	maxMilliseconds := float64(base.Milliseconds()) * math.Pow(2, float64(retry))
 	capMilliseconds := float64(cap.Milliseconds())
-	lowestValue := int64(math.Min(capMilliseconds, maxMilliseconds))
 
-	return time.Duration(rand.Int63n(lowestValue)) * time.Millisecond
+	lowestValue := int64(math.Min(capMilliseconds, maxMilliseconds)) - minMilliseconds
```
Comment (rumyantseva) [inline internal/util/ctxutil/ctxutil.go:85]: I think I am a bit lost with calculation :)

As far as I understand, we use this one:
```
temp = min(cap, base * 2**attempt)
sleep = temp/2 + random_between(0, temp/2)
```

so, in our case `temp = min(capMilliseconds, maxMilliseconds)`
then what is the rest of the calculation about?

Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go:85]: The calculation you mentioned is the Equal Jitter

We use Full Jitter approach:
```
sleep = random_between(0, min(cap, base * 2 ** attempt))
```

File: internal/util/ctxutil/ctxutil.go (hunk 3 above)
Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go]: done

**Review by chilagrow — DISMISSED** [review]

**Comment by noisersup** [comment]
## TODO
- [ ] rename variables
- [ ] generate graph from the duration test results

**Comment by noisersup** [comment]
image

Didn't know how exactly should I model the data so I've callected all returned backoff durations and counted how often they were returned. The timeouts are distributed pretty equally to me.

File: internal/util/ctxutil/ctxutil.go [hunk 5]
```diff
@@ -61,20 +62,32 @@ func SleepWithJitter(ctx context.Context, d time.Duration, attempts int64) {
...
+// https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
 //
-// Math/rand is good enough because we don't need the randomness to be cryptographically secure.
-func DurationWithJitter(cap time.Duration, retry int64) time.Duration {
-	const base = time.Millisecond * 100
+// The maximum sleep is the cap. The minimum sleep is at least 3 milliseconds.
+// Provided cap must be larger than minimum sleep, and attempt number must be a positive number.
+func DurationWithJitter(cap time.Duration, attempt int64) time.Duration {
+	const base = 100      // ms
+	const minDuration = 3 // ms
```
Comment (noisersup) [inline internal/util/ctxutil/ctxutil.go:72]: Simplified both values to integers, as doing calculations on durations creates pretty difficult code to read

File: internal/util/ctxutil/ctxutil.go [hunk 6]
```diff
@@ -61,20 +62,32 @@ func SleepWithJitter(ctx context.Context, d time.Duration, attempts int64) {
...
-	lowestValue := int64(math.Min(capMilliseconds, maxMilliseconds))
+	// calculate base backoff based on base duration and amount of attempts
+	backoff := float64(base * math.Pow(2, float64(attempt)))
+	// cap is a max limit of possible durations returned
+	maxDuration := int64(math.Min(float64(capDuration), backoff))
+
+	sleep := rand.Int63n(maxDuration-minDuration) + minDuration
 
-	return time.Duration(rand.Int63n(lowestValue)) * time.Millisecond
+	// Math/rand is good enough because we don't need the randomness to be cryptographically secure.
```
Comment (w84thesun) [inline internal/util/ctxutil/ctxutil.go:91]: Should we move that comment one line above?

**Review by w84thesun — COMMENTED** [review]
Overall looks good, added a small comment.

File: internal/util/ctxutil/ctxutil.go (hunk 5 above)
Comment (chilagrow) [reply internal/util/ctxutil/ctxutil.go:72]: What is the reason for `capDuration` instead of `cap`? all `base`, `minDuration`, `capDuration` `maxDuration` are same unit, so it's a bit odd to have different naming.

This is honestly just super minor.

**Review by chilagrow — APPROVED** [review]

File: internal/util/ctxutil/ctxutil.go (hunk 5 above)
Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go:72]: I wanted to store cap in milliseconds in variable, as it's used multiple times in code and calling `cap.Milliseconds()` inside `math.Min` just makes i more difficult to read, we have also `maxDuration` and `minDuration`, what could we do instead?

File: internal/util/ctxutil/ctxutil.go (hunk 6 above)
Comment (noisersup) [reply internal/util/ctxutil/ctxutil.go]: You're right, fixed

**Review by chilagrow — DISMISSED** [review]

File: internal/util/ctxutil/ctxutil.go (hunk 5 above)
Comment (chilagrow) [reply internal/util/ctxutil/ctxutil.go:72]: yeah that's fine :hugs:

**Review by w84thesun — APPROVED** [review]
:shipit:

**Comment by AlekSi** [comment]
> Didn't know how exactly should I model the data

Well, we want the graph of exponential backoff to looks like an exponent. Like in the original article. I'm not sure how to read the current graph.

**Comment by noisersup** [comment]
> Well, we want the graph of exponential backoff to looks like an exponent. Like in the original article. I'm not sure how to read the > current graph.

Are you talking about dot graph or the linear graph from the article?

**Comment by noisersup** [comment]
The exponent graph on their article shows impact of amount of competing clients on the amount of calls, which requires implementation of clients that will reconnect and make their connection successful or not.

**Review by rumyantseva — APPROVED** [review]
I'm still curious to see the distribution, but the approach looks good to me.

In principle, we can call a few loops that call `DurationWithJitter` in parallel (with retry being increased in each loop) and save results. That will give some distribution similar to the idea of parallel connections.

**Review by rumyantseva — APPROVED** [review]

**Comment by noisersup** [comment]
image

@AlekSi New chart based on the results of new test. It shows total amount of calls for simulation with n clients.

**Comment by AlekSi** [comment]
On a call with Elena, I just released that I misread graphs in the original article, and that was the source of confusion. I will send a PR explaining what I meant.
