### PR TITLE
Fix `$set` operator to apply correct comparison

### LINKED ISSUE #1662: `$set` operator does not set modified count for changing to same value
### Versions

0.7.1

### What did you do?

Moved `TestUpdateFieldCompatSet` test `ArrayNil` and `SetSameValueInt` test case to compat.

### What did you expect to see?

The same as compat.

### What did you see instead?

The compat expect 1 modification, but target has 0 modification.
```
        --- FAIL: TestUpdateFieldCompatSet/ArrayNil/TestUpdateFieldCompatSet-ArrayNil_Scalars (0.98s)
            --- FAIL: TestUpdateFieldCompatSet/ArrayNil/TestUpdateFieldCompatSet-ArrayNil_Scalars/null (0.02s)
                update_field_compat_test.go:387: 
                        Error Trace:    /home/chi/go/src/github.com/chilagrow/FerretDB/integration/update_compat_test.go:123
                        Error:          Not equal: 
                                        expected: &mongo.UpdateResult{MatchedCount:1, ModifiedCount:1, UpsertedCount:0, UpsertedID:interface {}(nil)}
                                        actual  : &mongo.UpdateResult{MatchedCount:1, ModifiedCount:0, UpsertedCount:0, UpsertedID:interface {}(nil)}
                                        
                                        Diff:
                                        --- Expected
                                        +++ Actual
                                        @@ -2,3 +2,3 @@
                                          MatchedCount: (int64) 1,
                                        - ModifiedCount: (int64) 1,
                                        + ModifiedCount: (int64) 0,
                                          UpsertedCount: (int64) 0,
                        Test:           TestUpdateFieldCompatSet/ArrayNil/TestUpdateFieldCompatSet-ArrayNil_Scalars/null
```

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1662.

## Readiness checklist

* [ ] I added unit tests for new functionality or bug fixes.
* [ ] I added integration tests for new functionality or bug fixes.
* [x] I added compatibility tests for new functionality or bug fixes.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/types/compare_order.go [hunk 1]
```diff
@@ -110,7 +137,19 @@ func CompareOrder(a, b any, order SortType) CompareResult {
 		return result
 	}
 
-	return Compare(a, b)
+	c := &comparer{
+		compareTypeOrder: compareType,
```
Comment (chilagrow) [inline internal/types/compare_order.go:141]: Within array and within document, we must also check for different number type, since we pass this `compareType` around.

File: internal/types/compare_order.go [hunk 2]
```diff
@@ -91,9 +92,35 @@ const (
...
+
+const (
+	_ numberOrderResult = iota
+	doubleDT
+	int32DT
+	int64DT
+)
+
+// detectNumberType returns a sequence for float64, int32 and int64 types.
+func detectNumberType(value any) numberOrderResult {
```
Comment (rumyantseva) [inline internal/types/compare_order.go:106]: I see where this function is used, but I don't understand how it works. The result of this function is compared with `numbersDataType` which is another constant, and there are no other use cases for it.

Should this function be called something like `isNumber` then and include a comparison with `numbersDataType`?

File: internal/types/compare_order.go [hunk 3]
```diff
@@ -91,9 +92,35 @@ const (
...
+type numberOrderResult uint8
+
+const (
+	_ numberOrderResult = iota
+	doubleDT
+	int32DT
+	int64DT
+)
+
+// detectNumberType returns a sequence for float64, int32 and int64 types.
```
Comment (rumyantseva) [inline internal/types/compare_order.go:105]: What does it mean "a sequence", I see `numberOrderResult` is a `uint8`, is there a way we interpret it as a sequence?

File: integration/update_field_compat_test.go [hunk 4]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
 		"EmptyArray": {
 			update: bson.D{{"$set", bson.D{{"v", bson.A{}}}}},
 		},
+		"ArrayNumbersAsc": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{int32(42), int64(43), 45.5}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
+		},
+		"ArrayStringsDesc": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{"c", "b", "a"}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1816",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:748]: This one should work for tigris, see https://github.com/FerretDB/FerretDB/blob/71ba4d0c578ba0777b9464e17f979610e2a42f88/integration/shareddata/composites.go#L133

File: integration/update_field_compat_test.go [hunk 5]
```diff
@@ -666,9 +666,24 @@ func TestUpdateFieldCompatSet(t *testing.T) {
 			update:        bson.D{{"$set", bson.D{{"foo", int32(12)}, {"v", nil}}}},
 			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1676",
 		},
-		"SetSameValueInt": {
-			update: bson.D{{"$set", bson.D{{"v", int32(42)}}}},
-			skip:   "https://github.com/FerretDB/FerretDB/issues/1662",
+		"SameValueInt32Type": {
+			update:        bson.D{{"$set", bson.D{{"v", int32(42)}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:671]: This one should work for Tigris, just an int32 number, should be fine.

File: integration/update_field_compat_test.go [hunk 6]
```diff
@@ -666,9 +666,24 @@ func TestUpdateFieldCompatSet(t *testing.T) {
...
+		},
+		"SameValueInt64Type": {
+			update:        bson.D{{"$set", bson.D{{"v", int64(42)}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:675]: Same, should work for Tigris, it's just a number

File: integration/update_field_compat_test.go [hunk 7]
```diff
@@ -666,9 +666,24 @@ func TestUpdateFieldCompatSet(t *testing.T) {
...
+		},
+		"SameValueDoubleType": {
+			update:        bson.D{{"$set", bson.D{{"v", 42.0}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:679]: Same, as far as I understand it should work for Tigris

File: integration/update_field_compat_test.go [hunk 8]
```diff
@@ -666,9 +666,24 @@ func TestUpdateFieldCompatSet(t *testing.T) {
...
+		},
+		"DocSameNumberType": {
+			update: bson.D{{"$set", bson.D{{"v", bson.D{{"foo", int32(42)}}}}}},
+		},
+		"DocDifferentNumberType": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.D{{"foo", int64(42)}}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:686]: This one doesn't need an issue number but an explanation that it can't be set for Tigris. If we attempt to set a different type, Tigris will return an error.

File: integration/update_field_compat_test.go [hunk 9]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
 			resultType: emptyResult,
 		},
 		"ArrayNil": {
-			update: bson.D{{"$set", bson.D{{"v", bson.A{nil}}}}},
-			skip:   "https://github.com/FerretDB/FerretDB/issues/1662",
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{nil}}}}},
+			skipForTigris: "tigris produce empty result because composites dataset is not applicable",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:737]: I think this case is possible in `beta.27`, so it's a TODO

File: integration/update_field_compat_test.go [hunk 10]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
 		},
 		"EmptyArray": {
 			update: bson.D{{"$set", bson.D{{"v", bson.A{}}}}},
 		},
+		"ArrayNumbersAsc": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{int32(42), int64(43), 45.5}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1668",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:744]: This one is not possible for Tigris, see `skipForTigris: "Tigris does not support mixed types in arrays",` in the code

File: integration/update_field_compat_test.go [hunk 11]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
+		},
+		"ArrayStringsDesc": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{"c", "b", "a"}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1816",
+		},
+		"ArrayDifferentNumberType": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{int64(42), int64(43), 45.5}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1816",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:752]: Tigris does not support mixed types in arrays

File: integration/update_field_compat_test.go [hunk 12]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
+		},
+		"ArraySameNumberType": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.A{int32(42), int64(43), 45.5}}}}},
+			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1816",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:756]: Tigris does not support mixed types in arrays

File: integration/update_field_compat_test.go [hunk 13]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
+		},
+		"DocSameNumberType": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.D{{"foo", int32(42)}, {"42", "foo"}, {"array", bson.A{int32(42), "foo", nil}}}}}}},
+			skipForTigris: "tigris produce empty result because composites dataset is not applicable",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:760]: See `Tigris does not support field names started from numbers (`42`)` messages. Composites are possible in general.

File: integration/update_field_compat_test.go [hunk 14]
```diff
@@ -718,12 +733,36 @@ func TestUpdateFieldCompatSetArray(t *testing.T) {
...
+		},
+		"DocDifferentNumberType": {
+			update:        bson.D{{"$set", bson.D{{"v", bson.D{{"foo", int32(42)}, {"42", "foo"}, {"array", bson.A{int64(42), "foo", nil}}}}}}},
+			skipForTigris: "tigris produce empty result because composites dataset is not applicable",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:764]: Same here. Composites are possible, fields started with numbers are not possible.

**Review by rumyantseva — COMMENTED** [review]
Left some comments about tests

File: internal/types/compare.go [hunk 15]
```diff
@@ -52,17 +53,31 @@ func Compare(docValue, filterValue any) CompareResult {
...
-	switch docValue := docValue.(type) {
+	c := &comparer{
+		compareTypeOrder: compareTypeOrder,
+	}
+
+	return c.compare(docValue, filterValue)
+}
+
+// comparer uses compareTypeOrder to perform type comparison.
+type comparer struct {
```
Comment (rumyantseva) [inline internal/types/compare.go:64]: Why a struct is needed? Is it used as a dependency somewhere?

File: internal/types/compare_order.go [hunk 16]
```diff
@@ -253,6 +292,31 @@ func compareTypeOrder(a, b any) CompareResult {
...
+		aType := detectNumberType(a)
+		bType := detectNumberType(b)
+
+		switch {
+		case aType < bType:
+			return Less
+		case aType > bType:
+			return Greater
+		default:
+			return Equal
```
Comment (rumyantseva) [inline internal/types/compare_order.go:313]: Are there any use cases for it? If I understand the task correctly, it's enough to know whether the types are equal or not.

File: internal/types/compare_order.go [hunk 17]
```diff
@@ -253,6 +292,31 @@ func compareTypeOrder(a, b any) CompareResult {
 	}
 }
 
+// compareType compares compareTypeOrder then compares
+// number types. The number types int32, int64 and float64
+// are considered different.
```
Comment (rumyantseva) [inline internal/types/compare_order.go:297]: Ther are not only considered different, there is also quite a specific logic in how we sort them.

File: internal/types/compare.go (hunk 15 above)
Comment (chilagrow) [reply internal/types/compare.go:64]: This is used for checking if number type is equal or not within nested documents, we need to pass how to compare type order when it is called within recursion. Definitely need to improve documentation

For standard comparison by `Compare(a, b)`, 
a doc `{"v": {"foo": {"bar": [int32(1)]}}}` should equal
a doc `{"v": {"foo": {"bar": [float64(1)]}}}`
For `CompareOrder(a,b,Ascending)`, above should not equal.

File: integration/update_field_compat_test.go (hunk 7 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: For the same as above, this can only be tested on double data, I updated the test.

File: integration/update_field_compat_test.go (hunk 8 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: :+1:

File: integration/update_field_compat_test.go (hunk 4 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: Yes it works on `ArrayStrings` :+1: , I just need to skip `ArrayDoubles`, `ArrayInt32s` and `ArrayRegexes`

File: integration/update_field_compat_test.go (hunk 11 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: Applied :+1:

File: integration/update_field_compat_test.go (hunk 12 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: Applied :+1:

File: integration/update_field_compat_test.go (hunk 13 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: Thanks. I didn't try to enable tigris handler for `Composites` but I see that it would fail on "42" :fearful:

File: integration/update_field_compat_test.go (hunk 14 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go]: :pray: updating skip reason

File: internal/types/compare_order.go (hunk 16 above)
Comment (chilagrow) [reply internal/types/compare_order.go]: No longer applicable now. We use separate func Identical for this work

File: internal/types/identical.go [hunk 18]
```diff
@@ -0,0 +1,175 @@
...
+		aIter, bIter := a.Iterator(), b.Iterator()
+		defer aIter.Close()
+		defer bIter.Close()
+
+		for {
+			_, aField, err := aIter.Next()
+			if errors.Is(err, iterator.ErrIteratorDone) {
+				return true
+			} else if err != nil {
+				return false
```
Comment (rumyantseva) [inline internal/types/identical.go:48]: As this function doesn't have an error return value, I suggest we should panic in all those cases if `iter.Next` returns an error (for objects and arrays). Currently, we just ignore it, and this could cause unexpected behavior if such an error becomes possible in the future.

File: integration/update_field_compat_test.go [hunk 19]
```diff
@@ -709,6 +794,9 @@ func TestUpdateFieldCompatSet(t *testing.T) {
 func TestUpdateFieldCompatSetArray(t *testing.T) {
 	t.Parallel()
 
+	stringsProvider := shareddata.AllProviders().
+		Remove("ArrayDoubles", "ArrayInt32s", "ArrayRegexes")
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:798]: It looks to me that if we want to specify string providers, they should be included, not excluded. Otherwise, every time we add a new (non-string) provider we need to come to this part of the code and exclude it here.

Also, do we need to specify them? Can't we ignore Tigris-related tests/errors?

**Review by rumyantseva — COMMENTED** [review]
I like the solution!

I added a couple of thoughts/questions.

File: integration/update_field_compat_test.go (hunk 19 above)
Comment (chilagrow) [reply integration/update_field_compat_test.go:798]: Yes that's an option, let me ignore errors :+1:

File: internal/types/identical.go (hunk 18 above)
Comment (chilagrow) [reply internal/types/identical.go]: Sounds sensible :hugs: let me do that

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by w84thesun — APPROVED** [review]
👍
