### PR TITLE
Fix fluky `TestRenameCollectionCompat` tests

### LINKED ISSUE #3409: Some backend tests are fluky
### What should be done?

SQLite:
* https://github.com/FerretDB/FerretDB/actions/runs/6262515571/job/17004858668?pr=3407
* https://github.com/FerretDB/FerretDB/actions/runs/6301692434/job/17107283075?pr=3430
* https://github.com/FerretDB/FerretDB/actions/runs/6416041905/job/17419012857?pr=3496

PostgreSQL:
* https://github.com/FerretDB/FerretDB/actions/runs/6271012235/job/17029850391?pr=3411
* https://github.com/FerretDB/FerretDB/actions/runs/6496580977/job/17643830496?pr=3565

We should either fix the test or our code.

### Where?

Integration tests, unit tests.

### Definition of Done

Test or code fixed.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #3409.

Test sometimes fails because `TestRenameCollectionCompat` contains `Valid` test case which actually rename collection. After that has executed, collection no longer exists. So I've separated valid case to another compat test.

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/renamecollection_compat_test.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ func TestRenameCollectionCompat(t *testing.T) {
 			targetNSFrom: targetDB.Name() + "." + targetCollection.Name(),
 			compatNSFrom: compatDB.Name() + "." + compatCollection.Name(),
 			targetNSTo:   targetDB.Name() + ".newCollection",
-			compatNSTo:   targetDB.Name() + ".newCollection",
+			compatNSTo:   compatDB.Name() + ".newCollection",
```
Comment (AlekSi) [inline integration/renamecollection_compat_test.go:58]: Aren't `targetDB.Name()` and `compatDB.Name()` the same? Could we `require.Equal(t, compatDB.Name(), targetDB.Name())` and then use two fields (`to` and `from`) instead of four?

Comment (chilagrow) [reply integration/renamecollection_compat_test.go:58]: True, maybe actually I'm on wrong lead.

Comment (chilagrow) [reply integration/renamecollection_compat_test.go:58]: Yeah I'm on the wrong lead, the issue is essentially other test has renamed the collection. so the collection didn't exist anymore.

Comment (AlekSi) [reply integration/renamecollection_compat_test.go:58]: We still could clean-up the test in this PR. Also, let's replace those `any`s with `string`s. Maybe clean-up something else.

Comment (chilagrow) [reply integration/renamecollection_compat_test.go]: I think those `any` are testing for invalid bson input. So want to keep them for testing.

File: integration/renamecollection_compat_test.go [hunk 2]
```diff
@@ -34,140 +34,179 @@ func TestRenameCollectionCompat(t *testing.T) {
...
+
+	// Rename one more time
+	targetCommand = bson.D{{"renameCollection", from}, {"to", to + "_new"}}
+	targetErr = targetDBConnect.RunCommand(ctx, targetCommand).Decode(&targetRes)
+	require.NoError(t, targetErr)
+
+	compatCommand = bson.D{{"renameCollection", from}, {"to", to + "_new"}}
+	compatErr = compatDBConnect.RunCommand(ctx, compatCommand).Decode(&compatRes)
+	require.NoError(t, compatErr)
+
```
Comment (rumyantseva) [inline integration/renamecollection_compat_test.go:97]: Don't we want to call `ListCollectionNames` here too?

**Review by rumyantseva — APPROVED** [review]
LGTM! Thanks for fixing this.

File: internal/backends/postgresql/metadata/registry_test.go [hunk 3]
```diff
@@ -150,7 +150,9 @@ func TestCreateDrop(t *testing.T) {
 		t.Skip("skipping in -short mode")
 	}
 
-	t.Parallel()
+	// Do not run parallel, `initDBs()` searches all schema with ferretdb metadata table and
```
[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/backends/postgresql/metadata/registry_test.go:153]: (see also #3442)

File: integration/renamecollection_compat_test.go (hunk 2 above)
Comment (chilagrow) [reply integration/renamecollection_compat_test.go:96]: Yes let's call it

File: internal/backends/postgresql/metadata/registry_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/backends/postgresql/metadata/registry_test.go]: That's true, it can be due to other integration test too. Reverted the change :pray:

**Review by AlekSi — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Review by noisersup — APPROVED** [review]
