### PR TITLE
Add aggregation pipeline compat tests and fix errors

### LINKED ISSUE #1410: Implement `aggregate` command
### What should be done?

After #1891 and #1439, it should be possible to add integration / compat tests for aggregation pipelines. Let's do that.

Add compatibility test helper similar to `testQueryCompat` that accepts aggregation pipeline instead of filter, sort, and projection. It should add `$sort` stage if it is not present in the test case for stable results.

Explain/pushdown checks are not in the scope because they are not possible yet.

Changing existing aggregation pipelines to return correct errors is in the scope. Stage-specific bug fixes are in the scope unless those bugs affect `find` and other commands too.

### Definition of Done

- stages updated to return correct errors;
- integration/compatibility tests added;
- spot refactorings done.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1410.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/aggregate_compat_test.go [hunk 1]
```diff
@@ -0,0 +1,324 @@
...
+		"ID": {
+			pipeline: bson.A{bson.D{{"$match", bson.D{{"_id", "string"}}}}},
+		},
+		"Int": {
+			pipeline: bson.A{
+				bson.D{{"$match", bson.D{{"v", 42}}}},
+				// sort by _id because mongoDB does not have deterministic natural order.
+				bson.D{{"$sort", bson.D{{"_id", 1}}}},
+			},
+		},
```
Comment (chilagrow) [inline integration/aggregate_compat_test.go:254]: See 

```
Error:      	Not equal: 
        	            	expected: [
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-numbers-asc",
        	            	    "v": [
        	            	      42,
        	            	      {
        	            	        "$l": "43"
        	            	      },
        	            	      {
        	            	        "$f": 45.5
        	            	      }
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-composite",
        	            	    "v": [
        	            	      {
        	            	        "$f": 42.13
        	            	      },
        	            	      "foo",
        	            	      {
        	            	        "$b": "KgAN",
        	            	        "s": 128
        	            	      },
        	            	      {
        	            	        "$o": "000102030405060708091011"
        	            	      },
        	            	      true,
        	            	      {
        	            	        "$d": 1635761922123
        	            	      },
        	            	      null,
        	            	      {
        	            	        "$r": "foo",
        	            	        "o": "i"
        	            	      },
        	            	      42,
        	            	      {
        	            	        "$t": "180388626445"
        	            	      },
        	            	      {
        	            	        "$l": "41"
        	            	      }
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-three",
        	            	    "v": [
        	            	      42,
        	            	      "foo",
        	            	      null
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array",
        	            	    "v": [
        	            	      42
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-three-reverse",
        	            	    "v": [
        	            	      null,
        	            	      "foo",
        	            	      42
        	            	    ]
        	            	  }
        	            	]
        	            	actual  : [
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array",
        	            	    "v": [
        	            	      42
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-three-reverse",
        	            	    "v": [
        	            	      null,
        	            	      "foo",
        	            	      42
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-numbers-asc",
        	            	    "v": [
        	            	      42,
        	            	      {
        	            	        "$l": "43"
        	            	      },
        	            	      {
        	            	        "$f": 45.5
        	            	      }
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-composite",
        	            	    "v": [
        	            	      {
        	            	        "$f": 42.13
        	            	      },
        	            	      "foo",
        	            	      {
        	            	        "$b": "KgAN",
        	            	        "s": 128
        	            	      },
        	            	      {
        	            	        "$o": "000102030405060708091011"
        	            	      },
        	            	      true,
        	            	      {
        	            	        "$d": 1635761922123
        	            	      },
        	            	      null,
        	            	      {
        	            	        "$r": "foo",
        	            	        "o": "i"
        	            	      },
        	            	      42,
        	            	      {
        	            	        "$t": "180388626445"
        	            	      },
        	            	      {
        	            	        "$l": "41"
        	            	      }
        	            	    ]
        	            	  },
        	            	  {
        	            	    "$k": [
        	            	      "_id",
        	            	      "v"
        	            	    ],
        	            	    "_id": "array-three",
        	            	    "v": [
        	            	      42,
        	            	      "foo",
        	            	      null
        	            	    ]
        	            	  }
        	            	]
```

File: integration/aggregate_compat_test.go [hunk 2]
```diff
@@ -0,0 +1,350 @@
...
+func TestAggregateCompatMatch(t *testing.T) {
+	testCases := map[string]aggregateStageCompatTestCase{
+		"ID": {
+			pipeline: bson.A{bson.D{{"$match", bson.D{{"_id", "string"}}}}},
+		},
+		"Int": {
+			pipeline: bson.A{
+				bson.D{{"$match", bson.D{{"v", 42}}}},
+				// sort by _id because compat does not have deterministic order.
+				bson.D{{"$sort", bson.D{{"_id", 1}}}},
```
Comment (AlekSi) [inline integration/aggregate_compat_test.go:253]: We should do it in `testAggregateStageCompat` itself; see

https://github.com/FerretDB/FerretDB/blob/852ebf4002669578fd332c90d5aff8f9af08a66f/integration/query_compat_test.go#L67-L70

There we should not use a separate field, but we could check if `pipeline` includes `$sort`

Comment (chilagrow) [reply integration/aggregate_compat_test.go]: Added check to find $sort in the pipeline, and adding $sort if that doesn't exist :+1:

File: integration/aggregate_compat_test.go [hunk 3]
```diff
@@ -0,0 +1,369 @@
...
+
+// aggregateStageCompatTestCase describes aggregate compatibility test case.
+type aggregateStageCompatTestCase struct {
+	skip       string                   // skip test for all handlers, must have issue number mentioned
+	pipeline   bson.A                   // required, unspecified $sort appends bson.D{{"$sort", bson.D{{"_id", 1}}}}
+	resultType compatTestCaseResultType // defaults to nonEmptyResult
+}
+
+// testAggregateStageCompat tests aggregate stage compatibility test cases.
+func testAggregateStageCompat(t *testing.T, testCases map[string]aggregateStageCompatTestCase) {
```
Comment (noisersup) [inline integration/aggregate_compat_test.go:37]: If we use this helper for in tests with single stages but also multiple stages, then I would suggest to make it plural
```suggestion
func testAggregateStagesCompat(t *testing.T, testCases map[string]aggregateStageCompatTestCase) {
```

File: integration/aggregate_compat_test.go [hunk 4]
```diff
@@ -0,0 +1,369 @@
...
+			t.Helper()
+
+			if tc.skip != "" {
+				t.Skip(tc.skip)
+			}
+
+			pipeline := tc.pipeline
+			require.NotNil(t, pipeline, "pipeline should be set")
+
+			t.Parallel()
```
Comment (noisersup) [inline integration/aggregate_compat_test.go:54]:
```suggestion
                        t.Parallel()
                        
			pipeline := tc.pipeline
			require.NotNil(t, pipeline, "pipeline should be set")			
```

File: integration/aggregate_compat_test.go [hunk 5]
```diff
@@ -0,0 +1,369 @@
...
+		"AscendingID": {
+			pipeline: bson.A{bson.D{{"$sort", bson.D{{"_id", 1}}}}},
+		},
+		"DescendingID": {
+			pipeline: bson.A{bson.D{{"$sort", bson.D{{"_id", -1}}}}},
+		},
+		"AscendingValue": {
+			pipeline: bson.A{bson.D{{"$sort", bson.D{
+				{"v", 1},
+				{"_id", 1}, // sort by _id when v is the same.
```
Comment (noisersup) [inline integration/aggregate_compat_test.go:332]: We could remove this, as it's the default test value, but I assume it's better to show it inside the test case as we test for `$sort` here particularly. :+1:

**Review by noisersup — COMMENTED** [review]
Some small changes suggested from me. Apart from that it looks good!

File: integration/aggregate_compat_test.go (hunk 5 above)
Comment (rumyantseva) [inline integration/aggregate_compat_test.go:332]: What if we don't set it and only have one case with `v`? I think as a user, if I want to sort by `v`, I don't really care about setting an `_id` as well. Should this comment be a TODO for sorting implementation?

**Review by rumyantseva — APPROVED** [review]
The tests looks good to me (left one minor comment), so I'm ready to approve. It looks to me like we need a separate issue to implement proper sorting.

File: integration/aggregate_compat_test.go (hunk 5 above)
Comment (chilagrow) [reply integration/aggregate_compat_test.go:332]: So if `_id` is not set, we let compat (and target) sort by any order when `v` are the same. For example, documents containing the same value `v` might be different order each execution. See the doc 
https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/#sort-consistency

We want to avoid inconsistency particularly between compat and target hence we sort by _id for those with same `v`. Does this make sense?

As a user, if you want to have consistently same order, it's recommended to use `_id` sort at the end too :hugs:

File: integration/aggregate_compat_test.go [hunk 6]
```diff
@@ -0,0 +1,369 @@
...
+
+			pipeline := tc.pipeline
+			require.NotNil(t, pipeline, "pipeline should be set")
+
+			t.Parallel()
+
+			var hasSortStage bool
+			for _, stage := range pipeline {
+				stage, ok := stage.(bson.D)
+				require.True(t, ok, "stage needs to be bson.D type")
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/aggregate_compat_test.go:59]: Actually I did tried that as well and driver handles it nicely with an error. So I'm removing this check!

File: integration/aggregate_compat_test.go (hunk 5 above)
Comment (chilagrow) [reply integration/aggregate_compat_test.go:334]: So this one isn't default value, but `AscendingID` test it the default one. Let's keep it there because we would want to have a test case for it explicitly!

File: integration/aggregate_compat_test.go (hunk 4 above)
Comment (chilagrow) [reply integration/aggregate_compat_test.go]: Yea sure

File: integration/aggregate_compat_test.go (hunk 3 above)
Comment (chilagrow) [reply integration/aggregate_compat_test.go]: Thanks, let's do that.

**Review by noisersup — APPROVED** [review]

File: integration/aggregate_compat_test.go (hunk 5 above)
Comment (rumyantseva) [reply integration/aggregate_compat_test.go:334]: Yeah, makes total sense! This looks like something we should mention in our documentation (cc @Fashander).

**Review by rumyantseva — APPROVED** [review]
:shipit:
