### PR TITLE
Skip flaky `currentOp` test and add TODO

### LINKED ISSUE #4871: Flaky `currentOp` test
### What should be done?

CI sometimes fails due to `TestCurrentOpGetMore` test unable to find running `getMore` operation.
Failing CIs
https://github.com/FerretDB/FerretDB/actions/runs/13659838873/job/38188187836?pr=4863
https://github.com/FerretDB/FerretDB/actions/runs/13664274468/job/38202175734?pr=4868
```
2025-03-04T22:37:56.5965885Z WARN           currentop_test.go:386: 
2025-03-04T22:37:56.5966350Z WARN                       Error Trace:    /home/runner/work/FerretDB/FerretDB/integration/currentop_test.go:386
2025-03-04T22:37:56.5966756Z WARN                                                               /home/runner/work/FerretDB/FerretDB/integration/currentop_test.go:59
2025-03-04T22:37:56.5967066Z WARN                       Error:          no in-progress operation found
2025-03-04T22:37:56.5967264Z WARN                       Test:           TestCurrentOpGetMore
2025-03-04T22:37:56.5967703Z WARN           setup.go:269: Keeping TestCurrentOpGetMore.TestCurrentOpGetMore for debugging
```

### Where?

https://github.com/FerretDB/FerretDB/blob/main/integration/currentop_test.go

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #4871.

Please reopen the issue.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/currentop_test.go [hunk 1]
```diff
@@ -33,6 +33,9 @@ import (
 )
 
 func TestCurrentOpGetMore(tt *testing.T) {
+	// TODO https://github.com/FerretDB/FerretDB/issues/4871
+	tt.Skip("https://github.com/FerretDB/FerretDB/issues/4871")
```
Comment (chilagrow) [inline integration/currentop_test.go:37]: This `TestCurrentOpGetMore` test fails on CI sometimes, while another `TestCurrentOpExplain` seems stable as I haven't spotted CI failure.
