### PR TITLE
Fix PLAIN mechanism authentication incorrectly working

### LINKED ISSUE #1877: Enforce new authentication
### What should be done?

When new authentication is enabled (by a flag or environment variable), it should be checked at the beginning of every command handler, not in the backend.
When new authentication is not enabled, it should be checked by backends as before.

With #3784 implemented, we should also add integration tests (for new authentication only).

Commands that do not require authentication are:
- `hello`
- `ping`
- `isMaster`
- `whatsmyuri`
- `buildInfo`
- `authenticate`
- `connectionStatus`
- `saslStart` 
- `saslContinue`
- `logout`

### Where?

Handler, backends.

### Definition of Done

- handler updated;
- all backends updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- **[user documentation](https://docs.ferretdb.io/security/authentication/) updated**.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

I found a bug related to enforcing new authentication, see added test.

Closes #1877.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handler/msg_logout.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ import (
 // MsgLogout implements `logout` command.
 func (h *Handler) MsgLogout(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg, error) {
 	conninfo.Get(ctx).SetAuth("", "")
+	conninfo.Get(ctx).SetMechanism("")
```
Comment (henvic) [inline internal/handler/msg_logout.go:29]: This looks fine to me, although I'd almost always rather have the auth and mechanism reset at once on a single mutex with something like `conninfo.Get(ctx).LogoutSCRAM()` or `ResetSCRAM()`.

**Review by henvic — APPROVED** [review]

File: internal/handler/msg_logout.go (hunk 1 above)
Comment (chilagrow) [reply internal/handler/msg_logout.go:29]: How about if I make mechanism part of Auth so I can do below?
`conninfo.Get(ctx).SetAuth("", "","")`

Comment (henvic) [reply internal/handler/msg_logout.go]: Sounds even better to me.

**Review by henvic — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]
