### PR TITLE
Fix docker health check on evaluation image

### LINKED ISSUE #4976: Provide evaluation Docker image with production builds
### What should be done?

No matter how much we try to discourage them, some people will use evaluation Docker images in production. Many do that for convenience—deploying one container is more straightforward than two.

Let's update our existing evaluation Docke with development built to use ~[runit](https://smarden.org/runit/) as we [did in 1.x](https://github.com/FerretDB/FerretDB/tree/main-v1/build/ferretdb/all-in-one)~ supervisord. Make sure that termination signals are handled correctly.

After that, let's rename that image to `ferretdb-eval-dev`.

After that, let's make a `ferretdb-eval` image using production builds of FerretDB and DocumentDB.

Let's build both like we build `ferretdb-eval` now – for every commit into `main` branch and for every PR with `packages` and `trust` labels (and unlike our main production image).

### Where?

Build system, CI.

### Definition of Done

- images are built;
- spot refactorings done;
- user documentation updated.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Also always set `POSTGRES_DB` to `postgres`

Closes #4976.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: build/ferretdb/eval-dev.Dockerfile [hunk 1]
```diff
@@ -122,7 +122,7 @@ COPY --from=eval-dev-build /src/build/ferretdb/evaluation/entrypoint.sh /usr/loc
 ENTRYPOINT ["entrypoint.sh"]
 
 HEALTHCHECK --interval=1m --timeout=5s --retries=1 --start-period=30s --start-interval=5s \
-  CMD ["/ferretdb", "ping"]
+  CMD ["/usr/local/bin/ferretdb", "ping"]
```
Comment (chilagrow) [inline build/ferretdb/eval-dev.Dockerfile:125]:
```
$ task docker-local FILE=eval-dev
...
$ docker run --rm -d --name ferretdb -p 27017:27017 --env POSTGRES_PASSWORD=password ferretdb-local
...
$ docker container ls
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                   PORTS                                                     NAMES
1949dfba0074   ferretdb-local                  "entrypoint.sh"          3 minutes ago   Up 3 minutes (healthy)   5432/tcp, 8088/tcp, 27018/tcp, 0.0.0.0:27017->27017/tcp   ferretdb
```

File: build/ferretdb/evaluation/entrypoint.sh [hunk 2]
```diff
@@ -12,6 +12,10 @@ if [ "${POSTGRES_DB:-postgres}" != "postgres" ]; then
     exit 1
 fi
 
+# explicitly set POSTGRES_DB, because if POSTGRES_DB is unset it uses POSTGRES_USER value
+# see https://hub.docker.com/_/postgres
+export POSTGRES_DB="postgres"
```
Comment (chilagrow) [inline build/ferretdb/evaluation/entrypoint.sh:17]: it was reporting this upon
```
$ docker run --rm --name ferretdb -p 27017:27017 --env POSTGRES_PASSWORD=password --env POSTGRES_USER=username  ferretdb-local
...
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/20-install.sql                                                                                                                     
psql:/docker-entrypoint-initdb.d/20-install.sql:1: NOTICE:  installing required extension "documentdb_core"                                                                                                 
psql:/docker-entrypoint-initdb.d/20-install.sql:1: NOTICE:  installing required extension "pg_cron"                                                                                                         
2025-04-17 04:09:36.829 UTC [86] ERROR:  can only create extension in database postgres                                                                                                                     
2025-04-17 04:09:36.829 UTC [86] DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.         
2025-04-17 04:09:36.829 UTC [86] HINT:  Add cron.database_name = 'username' in postgresql.conf to use the current database.                                                                                 
```

Comment (chilagrow) [reply build/ferretdb/evaluation/entrypoint.sh:17]: manually tested 
```
$ docker run -d --rm --name ferretdb -p 27017:27017 --env POSTGRES_PASSWORD=password --env POSTGRES_USER=username ferretdb-local
cf113c6c86c542b44ced96cb2518b4bec91204c6bc4f7ba6c3cb49343581f26b
$ docker exec -it ferretdb bash -c "mongosh mongodb://username:password@127.0.0.1:27017"
Current Mongosh Log ID: 680096a775ae9d2d91d861df
Connecting to:          mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.0
Using MongoDB:          7.0.77
Using Mongosh:          2.5.0                
                                                                                                      
For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/
                                                   
                                                   
To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.
                                                   
------                             
   The server generated these startup warnings when booting
   2025-04-17T05:50:31.318Z: Powered by FerretDB v2.1.0-30-gbcaa5ee07 and DocumentDB 0.103.0 (PostgreSQL 17.4).
   2025-04-17T05:50:31.318Z: Please star 🌟 us on GitHub: https://github.com/FerretDB/FerretDB.
   2025-04-17T05:50:31.318Z: The telemetry state is undecided. Read more about FerretDB telemetry and how to opt out at https://beacon.ferretdb.com.
   2025-04-17T05:50:31.319Z: This is a development build. The performance will be affected.
   2025-04-17T05:50:31.319Z: Debug logging enabled. The security and performance will be affected.
------

test> db.foo.insertOne({abc: 123})
{
  acknowledged: true,
  insertedId: ObjectId('6800973075ae9d2d91d861e0')
}
```

**Review by noisersup — APPROVED** [review]
