### PR TITLE
Fix error types and array handling when dot notation is used with `$set` operator

### LINKED ISSUE #1661: Wrong error type is returned from $set
### Versions

0.7.1

### What did you do?

Moved `TestUpdateFieldCompatSet` test `ArrayFieldExist` test case to compat test.

### What did you expect to see?

Same error as compat.

### What did you see instead?

The error expected is `WriteError`, error received was `CommandError`.
```
                        Error:          Not equal: 
                                        expected: mongo.WriteException(mongo.WriteException{WriteConcernError:(*mongo.WriteConcernError)(nil), WriteErrors:mongo.WriteErrors{mongo.WriteError{Index:0, Code:28, Message:"Cannot create field 'array' in element {v: new Date(1635761922123)}", Details:bson.Raw(nil), Raw:bson.Raw(nil)}}, Labels:[]string(nil), Raw:bson.Raw(nil)})
                                        actual  : mongo.CommandError(mongo.CommandError{Code:1, Message:"[pool.go:213 pgdb.(*Pool).InTransaction] Cannot create field 'array' in element {v: new Date(1635761922123)}", Labels:[]string(nil), Name:"InternalError", Wrapped:error(nil), Raw:bson.Raw(nil)})

```

### PR DESCRIPTION
**Pull request by rumyantseva**
# Description

Closes #1661.

## Readiness checklist

* [x] I added unit tests for new functionality or bug fixes.
* [x] I added integration tests for new functionality or bug fixes.
* [ ] I added compatibility tests for new functionality or bug fixes.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] I ensured that the title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/types/document_test.go [hunk 1]
```diff
@@ -144,6 +144,33 @@ func TestDocument(t *testing.T) {
 					)),
 				)),
 			},
+			{
```
Comment (rumyantseva) [inline internal/types/document_test.go:147]: These unit tests are provided for documentation purposes only (to understand how `SetByPath` should work for complicated array case). Proper testing is done through compat tests (see `TestUpdateFieldCompatSet`).

File: internal/types/path.go [hunk 2]
```diff
@@ -263,6 +265,14 @@ func insertByPath(doc *Document, path Path) error {
 						),
 					)
 				}
+
+				// If path needs to be reserved in the middle of the array, we should fill the gap with Null
```
Comment (rumyantseva) [inline internal/types/path.go:269]: @chilagrow PTAL, it looks similat to your `$inc` task!

File: internal/handlers/common/update.go [hunk 3]
```diff
@@ -236,7 +238,7 @@ func processPopFieldExpression(doc *types.Document, update *types.Document) (boo
 
 		err = doc.SetByPath(path, array)
 		if err != nil {
-			return false, err
+			return false, lazyerrors.Error(err)
```
Comment (rumyantseva) [inline internal/handlers/common/update.go:241]: There is no test case for it, and I couldn't come up with one quickly, so I return `lazyerrors.Error` to make the fact we don't test it explicit.

File: internal/handlers/common/update.go [hunk 4]
```diff
@@ -284,9 +286,8 @@ func processRenameFieldExpression(doc *types.Document, update *types.Document) (
 		doc.RemoveByPath(sourcePath)
 
 		// Set new path with old value
-		err = doc.SetByPath(targetPath, val)
-		if err != nil {
-			return changed, err
+		if err := doc.SetByPath(targetPath, val); err != nil {
+			return false, lazyerrors.Error(err)
```
Comment (rumyantseva) [inline internal/handlers/common/update.go:290]: There is no test case for it, and I couldn't come up with one quickly, so I return `lazyerrors.Error` to make the fact we don't test it explicit.

File: internal/handlers/common/update.go [hunk 5]
```diff
@@ -340,12 +340,8 @@ func processIncFieldExpression(doc *types.Document, updateV any) (bool, error) {
...
 		incremented, err := addNumbers(incValue, docValue)
 		if err == nil {
-			err := doc.SetByPath(path, incremented)
-			if err != nil {
-				return false, NewWriteErrorMsg(
-					ErrUnsuitableValueType,
-					fmt.Sprintf(`Cannot create field in element {%s: %v}`, path.Prefix(), docValue),
-				)
+			if err = doc.SetByPath(path, incremented); err != nil {
+				return false, lazyerrors.Error(err)
```
Comment (rumyantseva) [inline internal/handlers/common/update.go:344]: There is no test case for it, and I couldn't come up with one quickly, so I return `lazyerrors.Error` to make the fact we don't test it explicit.

File: integration/update_field_compat_test.go [hunk 6]
```diff
@@ -669,23 +669,30 @@ func TestUpdateFieldCompatSet(t *testing.T) {
...
 		"ArrayFieldNotExist": {
 			update:        bson.D{{"$set", bson.D{{"foo.0.baz", int32(1)}}}},
 			skipForTigris: "https://github.com/FerretDB/FerretDB/issues/1676",
 		},
-		"DocArrFieldNotExist": {
-			update: bson.D{{"$set", bson.D{{"v.0.foo", int32(1)}}}},
-			skip:   "https://github.com/FerretDB/FerretDB/issues/1661",
+		"DocArrFieldNotExists_0": {
+			update:        bson.D{{"$set", bson.D{{"v.0.foo", int32(1)}}}},
+			skipForTigris: "Tigris needs a special data set: https://github.com/FerretDB/FerretDB/issues/1791",
```
Comment (rumyantseva) [inline integration/update_field_compat_test.go:687]: I decided not to add new Tigris data sets as part of the current task, because it slows down Tigris even more... So we need to figure out what's wrong (#1791).

File: internal/types/path.go (hunk 2 above)
Comment (chilagrow) [reply internal/types/path.go:269]: This is great!

**Review by chilagrow — APPROVED** [review]
Looks great!

**Review by noisersup — APPROVED** [review]
LGTM!
