### PR TITLE
Fix `speculativeAuthenticate` panic on empty database

### LINKED ISSUE #4100: Implement localhost exception
### What should be done?

When new authentication is enabled, `admin.system.users` collection does not exist, and the client is [connected from the localhost](https://pkg.go.dev/net/netip#Addr.IsLoopback), bypass credentials checking instead of what #4075 did (falling back to old backend authentication).

It is similar to https://www.mongodb.com/docs/manual/core/localhost-exception/

For testing, we probably should add a fixed user to MongoDB and FerretDB in the `envtool` and use MongoDB URI with those credentials in tests for the initial connection.

We probably should also clean up the way we create and drop users in tests, including test setup. We also should remove or simplify `if IsMongo` / `if !IsMongo` branches.

### Where?

See issue number in the codebase add by https://github.com/FerretDB/FerretDB/pull/4075.

### Definition of Done

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated;
- something else?

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

This panic is only visible on mechanism called `MONGODB-X509`. But it's nice to fix panic if you come across one :hugs: 

Run FerretDB with `--test-enable-new-auth` flag.
```
diff --git a/Taskfile.yml b/Taskfile.yml
index c50d557f3..8cef1ba5c 100644
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -364,6 +364,7 @@ tasks:
         --handler=pg
         --postgresql-url='postgres://username@127.0.0.1:5432/ferretdb?search_path='
         --test-records-dir=tmp/records
+        --test-enable-new-auth
```

Run `mongosh` without database, use below mechanism, it won't panic for PLAIN or SCRAM.
```
$ docker compose exec mongodb mongosh --verbose --shell 'mongodb://host.docker.internal:27017/?authMechanism=MONGODB-X509'
Current Mongosh Log ID: 65f163a2de277b1c0f3c9181                                                      
Connecting to:          mongodb://host.docker.internal:27017/?authMechanism=MONGODB-X509&directConnection=true&appName=mongosh+2.1.4                                                                        
MongoNetworkError: connection 1 to 192.168.65.2:27017 closed                                                     
```

See panic, it appears because Op query seems to error on command error or lazyerror.
```
2024-03-13T17:23:46.441+0900    ERROR   // 127.0.0.1:43834 -> 127.0.0.1:27017   clientconn/conn.go:525  Handler error for unhandled response opcode      {"error": "BadValue (2): required parameter \"db\" is miss
ing", "opcode": "OP_REPLY"}                                                                                                                                                                                        
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).route                                                                                                                                                     
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/conn.go:525                   
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/conn.go:316
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/listener.go:305               
2024-03-13T17:23:46.441+0900    ERROR   // 127.0.0.1:43834 -> 127.0.0.1:27017   clientconn/conn.go:615  Response header: length:     0, id:    0, response_to:    0, opcode: OP_REPLY
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).logResponse                                     
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/conn.go:615                   
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run                                                                                                                                                       
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/conn.go:317                   
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1                                        
        /home/chi/go/src/github.com/chilagrow/FerretDB/internal/clientconn/listener.go:305               
2024-03-13T17:23:46.441+0900    ERROR   // 127.0.0.1:43834 -> 127.0.0.1:27017   clientconn/conn.go:616  Response message:
%!s(<nil>)                   
```

 Since if `SpeculativeAuthenticate` does not succeed, it calls saslStart. If db is not set, return Op query without `SpeculativeAuthenticate` field, the error is returned from saslStart. 

Closes #4100.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handler/cmd_query.go [hunk 1]
```diff
@@ -46,7 +46,9 @@ func (h *Handler) CmdQuery(ctx context.Context, query *wire.OpQuery) (*wire.OpRe
 
 		dbName, err := common.GetRequiredParam[string](document, "db")
 		if err != nil {
-			return nil, lazyerrors.Error(err)
+			reply.SetDocument(replyDoc)
+
+			return reply, nil
```
Comment (chilagrow) [inline internal/handler/cmd_query.go:51]: Cannot be tested in integration test because go driver returns `"database name cannot be empty"` before sending request to FerretDB.

File: internal/handler/cmd_query.go
Comment (chilagrow) [inline internal/handler/cmd_query.go:1]: I wonder if other error in this file also panics too :thinking:? For example `ErrNotImplemented`. I'm not sure if I can reach that path though.

**Comment by chilagrow** [comment]
With this fix an error is returned.

```
$ docker compose exec mongodb mongosh --verbose --shell 'mongodb://host.docker.internal:27017/?authMechanism=MONGODB-X509'                         [100/9304]
Current Mongosh Log ID: 65f16407349a0891c9b05ba3                                                                                                                                                            
Connecting to:          mongodb://host.docker.internal:27017/?authMechanism=MONGODB-X509&directConnection=true&appName=mongosh+2.1.4                                                                        
MongoServerError: no such command: 'authenticate'     
```

**Review by AlekSi — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
Nice catch!
