### PR TITLE
Fix `SchemaStats` to return empty stats

### LINKED ISSUE #1317: Fix `SchemaStats` to return empty stats (so tests won't fail)
### Versions

https://github.com/FerretDB/FerretDB/pull/1318

### What did you do?

Remove `SkipForPostgresWithReason` from `TestCommandsAdministrationServerStatusStress` and run the test for Postgres.

### What did you expect to see?

No errors.

### What did you see instead?

```
Error Trace:	/Users/elena/workdir/FerretDB/integration/commands_administration_test.go:952
			/Users/elena/workdir/FerretDB/integration/asm_arm64.s:1172
Error:		Received unexpected error:
			(InternalError) [msg_serverstatus.go:44 pg.(*Handler).MsgServerStatus] 
			[pool.go:234 pgdb.(*Pool).InTransaction] [pool.go:204 pgdb.SchemaStats] 
			ERROR: schema "testcommandsadministrationserverstatusstresspostgres_stress_3" does not exist (SQLSTATE 3F000)
```

### How to fix

As we don't have a good quick solution to fix the logic in `SchemaStats`, as a temporary solution let's return an empty result. 

A proper fix is not in the scope of the current task, see #1346.

DoD:

- [x] no TODOs / skipped tests mentioning the current issue number are in the code
- [x] fix the comment about collection creation (Tigris vs Postgres)

### PR DESCRIPTION
**Pull request by w84thesun**
# Description

Closes #1317.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by noisersup — APPROVED** [review]
LGTM. We could comment the serverStatus code and attach a "TODO", instead of deleting it completely though. The code will be probably reused in the future if I understand.

File: internal/handlers/pg/pgdb/pool.go [hunk 1]
```diff
@@ -180,44 +180,9 @@ func (pgPool *Pool) checkConnection(ctx context.Context) error {
...
-	}
-
-	res.Name = schema
-	err := pgPool.QueryRow(ctx, sql, args...).
-		Scan(&res.CountTables, &res.CountRows, &res.SizeTotal, &res.SizeIndexes, &res.SizeRelation, &res.CountIndexes)
-	if err != nil {
-		return nil, lazyerrors.Error(err)
-	}
-	return &res, nil
+	return &DBStats{
```
Comment (chilagrow) [inline internal/handlers/pg/pgdb/pool.go:183]: Let's update godoc.

**Review by AlekSi — APPROVED** [review]

File: internal/handlers/pg/pgdb/pool.go (hunk 1 above)
Comment (rumyantseva) [reply internal/handlers/pg/pgdb/pool.go:183]: fixed!

**Review by chilagrow — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]
