### PR TITLE
Fix `$` path errors for sort

### LINKED ISSUE #2259: Paths with dollar signs are handled incorrectly
We added support for dot notation in sorting, but it does not work correctly with sorting like `{"$v.foo", 1}`. For it, MongoDB returns:
```
(Location16410) FieldPath field names may not start with '$'. Consider using $getField or $setField.
```
FerretDB does not return an error.

See references to this issue in the code.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #2259.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handlers/common/sort.go [hunk 1]
```diff
@@ -40,6 +41,14 @@ func SortDocuments(docs []*types.Document, sortDoc *types.Document) error {
 	sortFuncs := make([]sortFunc, len(sortDoc.Keys()))
 
 	for i, sortKey := range sortDoc.Keys() {
+		if strings.Contains(sortKey, "$") {
```
Comment (rumyantseva) [inline internal/handlers/common/sort.go:44]:
```suggestion
		if strings.HasPrefix(sortKey, "$") {
```

I suggest `HasPrefix` for clarity (the error is about `$` being the first symbol), the rest looks good to me.

**Review by rumyantseva — APPROVED** [review]

**Review by w84thesun — DISMISSED** [review]
LGTM!

**Review by rumyantseva — DISMISSED** [review]
LGTM

**Review by w84thesun — APPROVED** [review]

**Review by w84thesun — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
