### PR TITLE
Fix issues for the Unix listener

### LINKED ISSUE #1295: Fix issues for the Unix listener
### Versions

`main` on October 21

### What did you do?

Run FerretDB with a Unix socket listener. Run a few commands.

### What did you expect to see?

Those commands should work.

### What did you see instead?

They return internal errors or panic.

---

The fix itself should be easy: there are a few places where we do type assertion on `net.TCPAddr` that panic for Unix sockets.

But before fixing those places, we should make our integration tests use Unix sockets for in-process FerretDB. And that would require some setup refactoring. The simplest way to do it might be switching from passing port numbers to passing MongoDB URIs.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1295. 

* `test-integration-pg` runs on unix socket, ` -target-unix-socket` is already specified in `Taskfile.yml`. 
* We don't support unix socket on windows, windows always uses TCP.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handlers/pg/msg_explain.go [hunk 1]
```diff
@@ -84,7 +84,9 @@ func (h *Handler) MsgExplain(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg,
 	var port int32
 	connInfo := conninfo.GetConnInfo(ctx)
 	if connInfo.PeerAddr != nil {
-		port = int32(connInfo.PeerAddr.(*net.TCPAddr).Port)
+		if tcpAddr, ok := connInfo.PeerAddr.(*net.TCPAddr); ok {
```
Comment (rumyantseva) [inline internal/handlers/pg/msg_explain.go:87]: In the case when `ok == false` the port is `0`, and then we consider the connection uses a socket, right?

File: internal/handlers/pg/msg_explain.go [hunk 2]
```diff
@@ -84,7 +84,9 @@ func (h *Handler) MsgExplain(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg,
...
+			port = int32(tcpAddr.Port)
```
Comment (rumyantseva) [inline internal/handlers/pg/msg_explain.go:88]: Do I understand correctly that if we want to test it, we need to run tests without `-target-unix-socket`? 
That looks a bit tricky as in `Taskfile.yml` we don't set  `-target-unix-socket` only for Tigris, and this case will not be covered (because it's the one for `pg`).

**Review by rumyantseva — COMMENTED** [review]
Not a full review yet, asked a couple of questions to understand the code.

**Review by rumyantseva — CHANGES_REQUESTED** [review]
Hmmm, it seems that something doesn't work for Mac.
I checked out the code locally and when I try to run tests on my env I see a lot of errors like

```
 task test-integration-tigris
task: [test-integration-tigris] go test -count=1 -race=true -tags=ferretdb_tigris -shuffle=on -coverpkg=../... -coverprofile=integration-tigris.txt . -handler=tigris

-test.shuffle 1668675367702040000
2022-11-17T09:56:07.704+0100    INFO    setup/common.go:233     Target system: in-process FerretDB with "tigris" handler.
2022-11-17T09:56:07.704+0100    INFO    setup/common.go:241     Compat system: port 37017.
2022-11-17T09:56:07.705+0100    INFO    debug   debug/debug.go:61       Starting debug server on http://127.0.0.1:58294/
--- FAIL: TestFindAndModifyCompatErrors (0.00s)
    --- FAIL: TestFindAndModifyCompatErrors/BadUpdateType (0.01s)
        common_unix.go:42: listen unix socket path too long len: 119, path: /var/folders/9p/cc9b8krs2zd1x9qx89fs1sjw0000gn/t/testfindandmodifycompaterrorsbadupdatetype2783407907/001/ferretdb.sock
```

File: internal/handlers/pg/msg_explain.go (hunk 2 above)
Comment (chilagrow) [reply internal/handlers/pg/msg_explain.go:88]: Yes, without `-target-unix-socket` uses TCP. With current Taskfile.yml setup we won't be testing port related thing on CI.

File: internal/handlers/pg/msg_explain.go (hunk 1 above)
Comment (chilagrow) [reply internal/handlers/pg/msg_explain.go:87]: Yeah. Also I didn't change returned document structure. The returned document will have "port":0 for unix socket connection.

**Comment by chilagrow** [comment]
> Hmmm, it seems that something doesn't work for Mac. I checked out the code locally and when I try to run tests on my env I see a lot of errors like
> 
> ```
>  task test-integration-tigris
> task: [test-integration-tigris] go test -count=1 -race=true -tags=ferretdb_tigris -shuffle=on -coverpkg=../... -coverprofile=integration-tigris.txt . -handler=tigris
> 
> -test.shuffle 1668675367702040000
> 2022-11-17T09:56:07.704+0100    INFO    setup/common.go:233     Target system: in-process FerretDB with "tigris" handler.
> 2022-11-17T09:56:07.704+0100    INFO    setup/common.go:241     Compat system: port 37017.
> 2022-11-17T09:56:07.705+0100    INFO    debug   debug/debug.go:61       Starting debug server on http://127.0.0.1:58294/
> --- FAIL: TestFindAndModifyCompatErrors (0.00s)
>     --- FAIL: TestFindAndModifyCompatErrors/BadUpdateType (0.01s)
>         common_unix.go:42: listen unix socket path too long len: 119, path: /var/folders/9p/cc9b8krs2zd1x9qx89fs1sjw0000gn/t/testfindandmodifycompaterrorsbadupdatetype2783407907/001/ferretdb.sock
> ```

I attempted using `tmp/sockets/` dir but this didn't work for me. My contains upper case chars `FerretDB` in path `/home/chi/go/src/github.com/chilagrow/FerretDB/tmp/sockets` and unix socket path with upper case letter seems to have problem even after escaping it.

The alternative I chose was to use os.TempDir() and use shorter generated dir name and cleaning it up.

File: integration/setup/setup.go [hunk 3]
```diff
@@ -49,6 +49,7 @@ type SetupOpts struct {
 type SetupResult struct {
 	Ctx           context.Context
 	Collection    *mongo.Collection
+	MongoURI      string
 	Port          uint16
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/setup/setup.go]: Thanks good point!

File: integration/commands_administration_test.go [hunk 4]
```diff
@@ -1046,9 +1046,11 @@ func TestCommandsAdministrationWhatsMyURI(t *testing.T) {
 	databaseName := s.Collection.Database().Name()
 	collectionName := s.Collection.Name()
 
+	// only check port number on TCP connection, no need to check on unix socket
+	isTCP := s.IsTPC(t)
```
Comment (w84thesun) [inline integration/commands_administration_test.go:1050]: I believe there is a typo in `TCP`.

**Review by w84thesun — CHANGES_REQUESTED** [review]
Checked it on Windows, looks like everything is working fine. A typo fix is needed.

File: integration/commands_administration_test.go (hunk 4 above)
Comment (chilagrow) [reply integration/commands_administration_test.go:1050]: Yes :sweat_smile:  thanks for catching this :pray:

**Review by rumyantseva — APPROVED** [review]
LGTM.

Tests pass on my env.

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by w84thesun — APPROVED** [review]
