### PR TITLE
Fix greater and less operators on array value comparison

### LINKED ISSUE #1569: Greater than comparison with array of integer returns unexpected result
### Versions

0.6.2

### What did you do?

Add `"array-numbers": bson.A{42, 43, 45}` to Composites shareddata. Comparison test to compare filter `bson.D{{"v", bson.D{{"$gt", int32(42)}}}}` returns false.

It's something related to array order and sorting and comparing against the largest value https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#arrays

Please look for the issue number in the code as well.

### What did you expect to see?

Returns true.

### What did you see instead?

```
Compat (expected) IDs: [array-numbers array-two]
Target (actual)   IDs: [array-two]
```

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1569.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/types/compare.go [hunk 1]
```diff
@@ -70,7 +111,7 @@ func Compare(docValue, filterValue any) CompareResult {
 				continue
 			}
 
-			if res := compareScalars(docValue, filterValue); res != Incomparable {
+			if res := compareScalars(docValue, filterValue); cond(res) {
```
Comment (chilagrow) [inline internal/types/compare.go:114]: I didn't use `Max` or `Min`, this somehow got quite a bit complicated. For example comparing `$gte` with doc `bson.A{"c", "b", "a"}` with filter `bson.D{{"v", bson.D{{"$gte", 41.13}}}}`, I think it is greater because [string is greater than number](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#comparison-sort-order). But mongo DB doesn't think so according to the compat test. Anyway for now, let's skip max and min.

File: internal/types/compare.go [hunk 2]
```diff
@@ -70,7 +123,7 @@ func Compare(docValue, filterValue any) CompareResult {
 				continue
 			}
 
-			if res := compareScalars(docValue, filterValue); res != Incomparable {
+			if res := compareScalars(docValue, filterValue); cond.satisfies(res) {
```
Comment (chilagrow) [inline internal/types/compare.go:126]: I didn't use Max or Min, this somehow got quite a bit complicated. For example comparing $gte with doc bson.A{"c", "b", "a"} with filter bson.D{{"v", bson.D{{"$gte", 41.13}}}}, I think it is greater because [string is greater than number](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#comparison-sort-order). But mongo DB doesn't think so according to the compat test. Anyway for now, let's skip max and min.

File: internal/types/compare.go (hunk 1 above)
Comment (chilagrow) [reply internal/types/compare.go]: I was totally wrong :see_no_evil:

Comment (chilagrow) [reply internal/types/compare.go]: Okay, so it seems this way. If you have a docValue `bson.A{nil, "foo", 42}` and a filter `{"$gte", 43}`, compat returns less `<`. It seems to skip/ignores a string "foo" (which has [greater comparison order](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#comparison-sort-order)) but only compare against number 42. So getting max won't work because max is specific to type of value filter has.

File: internal/types/compare.go [hunk 3]
```diff
@@ -40,12 +40,67 @@ const (
...
+	case Greater:
+		return c.greater
+	case Less:
+		return c.less
+	case Equal:
+		return c.equal
+	case Incomparable:
+		return false
+	default:
+		return false
```
Comment (rumyantseva) [inline internal/types/compare.go:94]: What could be other values apart from Greater, Less, Equal and Incomparable?

Comment (chilagrow) [reply internal/types/compare.go]: Removed this default added panic, just for the consistency with rest of the code

File: internal/types/compare.go [hunk 4]
```diff
@@ -40,12 +40,67 @@ const (
...
+	return compare(docValue, filterValue, cond{greater: true, less: true, equal: true})
+}
+
+// CompareGreaterThan compares docValue for the greater than condition.
+func CompareGreaterThan(docValue, filterValue any) CompareResult {
+	return compare(docValue, filterValue, cond{greater: true})
+}
+
+// CompareGreaterThanOrEq compares docValue for the greater than or equal to condition.
+func CompareGreaterThanOrEq(docValue, filterValue any) CompareResult {
```
[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/types/compare.go:60]: I think types package should export only `Compare` function and everything else should be an internal. I think we want to move towards a smaller exported APIs in general

[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/types/compare.go:60]: At the moment we pass `Compare(bson.A{"c", "b", "a"}, 43)` for `Compare(docValue, filterValue)`. So we don't have information related to the operator and we need that for this case. Perhaps we can pass `Compare(bson.A{"c", "b", "a"}, bson.D{{"$gte", 41.13}})` which includes the operator info, dependent on document comparison though.

Any other way of how we could achieve this?

[the remark this answers is not in the document]
Comment (rumyantseva) [reply internal/types/compare.go:60]: @chilagrow hmm, I think I start understanding... So, when we call `Compare` we can't say "it's equal" or "it's greater" without knowing the operator? Like for different operators, the result of `Compare` could be different?

[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/types/compare.go:60]: I think Compare(a, b) should compare values a and b; both a and b should not be expressions containing operators, but just values

[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/types/compare.go:60]: And I think `Compare(docValue, filterValue any)` is a rudiment of an old comparison code that tried to handle subarrays. That really should be `Compare(a, b any)` if possible

[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/types/compare.go:60]: I think what could possibly be done is to get `max` for  $gt, $gte and  `min` value for $lt,$lte before calling `Compare` and call `Compare(maxValue,filterValue)` for $gt for example. At the moment getting `max` or `min` is a bit tricky because when an array contains multiple types, it doesn't behave as expected.

[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/types/compare.go:60]: I'll see how this can be simplified to  Compare(a, b any)

[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/types/compare.go:60]: > At the moment getting max or min is a bit tricky because when an array contains multiple types, it doesn't behave as expected

So we just™ need to fix comparison, so Min and Max methods behave correctly

[the remark this answers is not in the document]
Comment (noisersup) [reply internal/types/compare.go:60]: I think I understand the logic of this PR and the solution looks reasonable to me. And yeah, I see a field to simplify our *existing* code, but I'm not sure if refactoring the code is in a scope of this issue.

File: integration/shareddata/composites.go [hunk 5]
```diff
@@ -40,6 +40,9 @@ var Composites = &Values[string]{
 		"array-three-reverse": bson.A{nil, "foo", int32(42)},
 		"array-empty":         bson.A{},
 		"array-null":          bson.A{nil},
+		"array-numbers-asc":   bson.A{int32(42), int32(43), int32(45)},
+		"array-strings-desc":  bson.A{"c", "b", "a"},
+		"array-composite":     bson.A{nil, primitive.Timestamp{T: 42, I: 13}, false, "z", primitive.NilObjectID},
```
Comment (chilagrow) [inline integration/shareddata/composites.go:45]: I wanted to add more concrete one but it failed on many tests so for now I created this issue https://github.com/FerretDB/FerretDB/issues/1607

File: internal/types/compare.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/types/compare.go]: I moved all the logic related to operator into filter. No change in `Compare` now.

File: integration/query_projection_test.go [hunk 6]
```diff
@@ -63,61 +63,6 @@ func TestQueryProjection(t *testing.T) {
...
-	require.NoError(t, err)
-
-	for name, tc := range map[string]struct {
-		projection  any
-		expectedIDs []any
-	}{
-		"ElemMatch": {
-			projection: bson.D{{
-				"v",
-				bson.D{{"$elemMatch", bson.D{{"field", bson.D{{"$eq", 42}}}}}},
```
Comment (chilagrow) [inline integration/query_projection_test.go:94]: Already moved in https://github.com/FerretDB/FerretDB/blob/main/integration/query_projection_compat_test.go#L60 and now shareddata has array numbers in composit `"array-numbers-asc": bson.A{int32(42), int32(43), int32(45)}`

File: integration/query_projection_compat_test.go [hunk 7]
```diff
@@ -64,21 +64,3 @@ func TestQueryProjectionCompatElemMatch(t *testing.T) {
 
 	testQueryCompat(t, testCases)
 }
-
-func TestQueryProjectionCompatSlice(t *testing.T) {
```
Comment (chilagrow) [inline integration/query_projection_compat_test.go:68]: Somehow this was duplicated so removing it. See L50 to L66

File: integration/query_test.go [hunk 8]
```diff
@@ -274,7 +274,7 @@ func TestQueryCount(t *testing.T) {
 	}{
 		"CountAllDocuments": {
 			command:  bson.D{{"count", collection.Name()}},
-			response: 45,
+			response: 48,
```
Comment (AlekSi) [inline integration/query_test.go:277]: Those tests really should be moved to compat tests

File: internal/handlers/common/filter.go [hunk 9]
```diff
@@ -348,9 +348,23 @@ func filterFieldExpr(doc *types.Document, filterKey string, expr *types.Document
...
 			// {field: {$gt: exprValue}}
-			if _, ok := exprValue.(types.Regex); ok {
+			switch exprValue.(type) {
+			case *types.Document, *types.Array:
+			case types.Regex:
 				msg := fmt.Sprintf(`Can't have RegEx as arg to predicate over field '%s'.`, filterKey)
 				return false, NewCommandErrorMsgWithArgument(ErrBadValue, msg, exprKey)
+			default:
+				if arrValue, ok := fieldValue.(*types.Array); ok {
+					// Filter array by only keeping the same type as exprValue.
```
Comment (rumyantseva) [inline internal/handlers/common/filter.go:358]: As discussed in the call, we need the "why" for this comment. 
For example, something like "only values of the same type can be compared, so we filter the array" (but maybe there is a better wording for it"

File: integration/shareddata/composites.go [hunk 10]
```diff
@@ -40,6 +40,9 @@ var Composites = &Values[string]{
 		"array-three-reverse": bson.A{nil, "foo", int32(42)},
 		"array-empty":         bson.A{},
 		"array-null":          bson.A{nil},
+		"array-numbers-asc":   bson.A{int32(42), int32(43), int32(45)},
```
Comment (rumyantseva) [inline integration/shareddata/composites.go:43]: @chilagrow as you mentioned in the call, those could be int32, int64, and float to check that we compare numbers correctly.

**Review by rumyantseva — APPROVED** [review]
The code looks good to me overall. Great job with all those tiny details! 

As discussed in the call, there are a couple of comments about documentation/test cases to improve.

**Review by rumyantseva — COMMENTED** [review]
Sorry, I meant to leave "comment" (not "approve" yet, but almost! 👍)

File: internal/handlers/common/filter.go (hunk 9 above)
Comment (w84thesun) [inline internal/handlers/common/filter.go:358]: Please rewrite this comment.

**Review by w84thesun — CHANGES_REQUESTED** [review]
As discussed on the call comment about using `FIlterArrayByType` needs to be clarified a bit.

File: integration/update_test.go [hunk 11]
```diff
@@ -96,13 +96,13 @@ func TestMultiFlag(t *testing.T) {
 				update:         bson.D{{"$set", bson.D{{"v", int32(43)}}}},
 				multi:          false,
 				stat:           bson.D{{"n", int32(1)}, {"nModified", int32(1)}, {"ok", float64(1)}},
-				expectedToFind: 5,
+				expectedToFind: 6,
```
Comment (chilagrow) [inline integration/update_test.go:99]: Created and issue to move update tests to compat https://github.com/FerretDB/FerretDB/issues/1610

File: integration/query_test.go (hunk 8 above)
Comment (chilagrow) [reply integration/query_test.go]: fixed

File: integration/shareddata/composites.go (hunk 10 above)
Comment (chilagrow) [reply integration/shareddata/composites.go]: fixed.

File: internal/handlers/common/filter.go (hunk 9 above)
Comment (chilagrow) [reply internal/handlers/common/filter.go]: I added example as well :pray:

Comment (chilagrow) [reply internal/handlers/common/filter.go]: added, please let me know it it's not clear :pray:

**Review by w84thesun — DISMISSED** [review]

**Review by noisersup — DISMISSED** [review]

File: integration/query_command_compat_test.go [hunk 12]
```diff
@@ -0,0 +1,109 @@
...
+)
+
+// queryCountCompatTestCase describes command query compatibility test case.
+type queryCountCompatTestCase struct {
+	query   bson.D // optional
+	command bson.D // defaults to count collection
+}
+
+// testQueryCountCompat tests command query compatibility test cases.
+func testQueryCountCompat(t *testing.T, testCases map[string]queryCountCompatTestCase) {
```
Comment (rumyantseva) [inline integration/query_command_compat_test.go:33]: Hmm, if I'm not mistaken, `count_compat_test.go` has some similar things... Does it make sense to combine those two, so we don't have duplicate code?

**Review by rumyantseva — COMMENTED** [review]
There is a possible duplicate of code for count compat tests (see `count_compat_test.go`), the rest looks good to me.

File: integration/query_command_compat_test.go (hunk 12 above)
Comment (chilagrow) [reply integration/query_command_compat_test.go]: yes thanks for spotting this. I combined them

**Review by rumyantseva — DISMISSED** [review]
Looks good to me overall, one tiny comment about test cases.

File: integration/count_compat_test.go [hunk 13]
```diff
@@ -120,6 +131,19 @@ func TestCountCompat(t *testing.T) {
...
+		"IDBool": {
+			filter: bson.D{{"_id", "bool-true"}},
+		},
+		"FieldTrue": {
+			filter: bson.D{{"v", true}},
+		},
+		"FieldTypeArrays": {
+			filter: bson.D{{"v", bson.D{{"$type", "array"}}}},
+		},
+		"NonExistingCollection": {
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/count_compat_test.go]: Thanks, non-existing collections are already covered so removing test.

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by w84thesun — APPROVED** [review]
