### PR TITLE
Fix `maxTimeMS` for `getMore` command

### LINKED ISSUE #2984: Support `maxTimeMS` in `getMore` command parameter
### What should be done?

After https://github.com/FerretDB/FerretDB/issues/2283

https://www.mongodb.com/docs/manual/reference/command/getMore/

`maxTimeMS` for `getMore` is supported only for tailable cursor.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/getmore.go

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;

### PR DESCRIPTION
**Pull request by noisersup**
# Description

Closes #2984.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [x] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [x] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handler/msg_find.go [hunk 1]
```diff
@@ -102,10 +104,19 @@ func (h *Handler) MsgFind(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg, er
...
 
 	cancel := func() {}
+	var findDone atomic.Bool
+
 	if params.MaxTimeMS != 0 {
-		// It is not clear if maxTimeMS affects only find, or both find and getMore (as the current code does).
-		// TODO https://github.com/FerretDB/FerretDB/issues/2984
-		ctx, cancel = context.WithTimeout(ctx, time.Duration(params.MaxTimeMS)*time.Millisecond)
+		ctx, cancel = context.WithCancel(ctx)
+		go func() {
```
Comment (rumyantseva) [inline internal/handler/msg_find.go:111]: Hmm, this gorutine will run for the whole duration of `MaxTimeMS`, even if `findDone.Load()` was true a while ago. 

Wouldn't something like this work?

```go
for {
		select {
		case <-ticker.C:
			canel()
		case <-signalChan:
			return
		}
	}
```

and `signalChan` is closed the same way as `findDone` is set as true.

Comment (noisersup) [reply internal/handler/msg_find.go:111]: I thought about something like that, though at this point it felt that introducing another go routine instead of ticker might be more suitable (as we only need one signal and not entire ticker). Although I remember that I've implemented something similar in some previous PR, and there were some objections in terms of complexity because of goroutines.

But yeah, in this case it seems to be more reasonable so will change that quickly and let's wait for the comments:)

File: internal/handler/msg_aggregate.go [hunk 2]
```diff
@@ -248,10 +248,21 @@ func (h *Handler) MsgAggregate(ctx context.Context, msg *wire.OpMsg) (*wire.OpMs
...
-		// TODO https://github.com/FerretDB/FerretDB/issues/2983
-		ctx, cancel = context.WithTimeout(ctx, time.Duration(maxTimeMS)*time.Millisecond)
+		ctx, cancel = context.WithCancel(ctx)
+
+		go func() {
+			select {
+			case <-timeout.C:
+				cancel()
+			case <-findDone:
+				return
```
Comment (henvic) [inline internal/handler/msg_aggregate.go:263]: Maybe use a `case <-ctx.Done()`?

File: internal/handler/msg_aggregate.go [hunk 3]
```diff
@@ -248,10 +248,21 @@ func (h *Handler) MsgAggregate(ctx context.Context, msg *wire.OpMsg) (*wire.OpMs
 	}
 
 	cancel := func() {}
```
Comment (henvic) [inline internal/handler/msg_aggregate.go:250]: Maybe you can remove this line and/or make it `var cancel func()` for the sake of brevity.

File: internal/handler/msg_aggregate.go [hunk 4]
```diff
@@ -248,10 +248,21 @@ func (h *Handler) MsgAggregate(ctx context.Context, msg *wire.OpMsg) (*wire.OpMs
...
+
+	timeout := time.NewTicker(time.Duration(maxTimeMS) * time.Millisecond)
```
Comment (henvic) [inline internal/handler/msg_aggregate.go:252]: It's important to call `ticker.Stop()` to clear up resources when finished with a ticker.

File: internal/handler/msg_find.go [hunk 5]
```diff
@@ -98,10 +98,22 @@ func (h *Handler) MsgFind(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg, er
...
+		ctx, cancel = context.WithCancel(ctx)
+
+		timeout := time.NewTicker(time.Duration(params.MaxTimeMS) * time.Millisecond)
+
+		go func() {
+			select {
+			case <-timeout.C:
+				cancel()
+			case <-findDone:
+				return
```
Comment (henvic) [inline internal/handler/msg_find.go:114]: Similar remarks to msg_aggregate.go.

File: internal/handler/msg_aggregate.go (hunk 4 above)
Comment (noisersup) [reply internal/handler/msg_aggregate.go:252]: The PR is not ready yet for another round of reviews but thanks!

File: internal/handler/msg_aggregate.go (hunk 2 above)
Comment (noisersup) [reply internal/handler/msg_aggregate.go:263]: In which case? Those lines are managing the context cancellation, not waiting for it

**Review by AlekSi — COMMENTED** [review]
Please re-request review when ready

File: internal/handler/msg_aggregate.go (hunk 3 above)
Comment (noisersup) [reply internal/handler/msg_aggregate.go:250]: The func's default value is nil, which cannot be called

File: internal/handler/msg_aggregate.go (hunk 2 above)
Comment (henvic) [reply internal/handler/msg_aggregate.go:265]: Oh, I see. I was mostly worried about the case when the function returns due to an error and `findDone <- struct{}{}` doesn't happen.

File: internal/handler/msg_find.go [hunk 6]
```diff
@@ -98,10 +98,23 @@ func (h *Handler) MsgFind(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg, er
...
+		defer timeout.Stop()
+
+		go func() {
+			select {
+			case <-timeout.C:
+				cancel()
+			case <-findDone:
+				return
+			}
+		}()
```
[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/handler/msg_find.go:117]: (not to mention that _ticker_ looks very strange there; if anything, it should be a timer)

[the remark this answers is not in the document]
Comment (noisersup) [reply internal/handler/msg_find.go:124]: It won't as underlying ticker has buffered channel. Also I've updated ticker to timer

**Review by AlekSi — APPROVED** [review]

**Review by henvic — APPROVED** [review]
