### PR TITLE
Fix `findAndModify` for `$exists` query operator

### LINKED ISSUE #1098: `upsert`: the response from FerretDB is not the same as from proxy
FerretDB version (commit) to reproduce the problem: `0c96f230f5359602d99ac440b6b66a9c91ff539e`
OS: MacOS
FerretDB is run via `task run`

## How to reproduce
Perform `findAndModify` with `upsert`, for example:
```
db.hello.findAndModify({ query: { _id: 12345}, update: {"$set": {"v": 43}}, upsert: true})
```

## Expected result
The responses from proxy and FerretDB are equal

## Actual result
The responses are different:
```2022-09-01T08:31:08.727+0200	DEBUG	// 127.0.0.1:62708 -> 127.0.0.1:27017 	clientconn/conn.go:437	Response header: length:   127, id:    7, response_to:   45, opcode: OP_MSG
2022-09-01T08:31:08.727+0200	DEBUG	// 127.0.0.1:62708 -> 127.0.0.1:27017 	clientconn/conn.go:438	Response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "lastErrorObject",
          "value",
          "ok"
        ],
        "lastErrorObject": {
          "$k": [
            "n",
            "updatedExisting",
            "upserted"
          ],
          "n": 1,
          "updatedExisting": false,
          "upserted": 12345
        },
        "value": {
          "$k": [
            "_id",
            "v"
          ],
          "_id": 12345,
          "v": 43
        },
        "ok": {
          "$f": 1
        }
      },
      "Kind": 0
    }
  ]
}



2022-09-01T08:31:08.730+0200	DEBUG	// 127.0.0.1:62708 -> 127.0.0.1:27017 	clientconn/conn.go:437	Proxy response header: length:   106, id: 78919, response_to:   45, opcode: OP_MSG
2022-09-01T08:31:08.731+0200	DEBUG	// 127.0.0.1:62708 -> 127.0.0.1:27017 	clientconn/conn.go:438	Proxy response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "lastErrorObject",
          "value",
          "ok"
        ],
        "lastErrorObject": {
          "$k": [
            "n",
            "updatedExisting",
            "upserted"
          ],
          "n": 1,
          "updatedExisting": false,
          "upserted": 12345
        },
        "value": null,
        "ok": {
          "$f": 1
        }
      },
      "Kind": 0
    }
  ]
}



2022-09-01T08:31:08.732+0200	DEBUG	// 127.0.0.1:62708 -> 127.0.0.1:27017 	clientconn/conn.go:223	Header diff:
--- res header
+++ proxy header
@@ -1 +1 @@
-length:   127, id:    7, response_to:   45, opcode: OP_MSG
+length:   106, id: 78919, response_to:   45, opcode: OP_MSG

Body diff:
--- res body
+++ proxy body
@@ -21,10 +21,3 @@
         },
-        "value": {
-          "$k": [
-            "_id",
-            "v"
-          ],
-          "_id": 12345,
-          "v": 43
-        },
+        "value": null,
         "ok": {
```

TODO:
- Find the current issue number mentioned in the compat tests for findAndModify, remove "skip", fix the problem and make tests pass

### LINKED ISSUE #1243: `findAndModify` with `remove: true` works incorrectly when the result is not found
### Versions

FerretDB: v0.5.4 (or current main - ab452bb84b2bfc8a95bb65db06c9c1a35e27ae4e).

### What did you do?

This is the data to reproduce the problem (collection `bools`, created by `task env-data`):
```
db.bools.find()
[
  { _id: 'bool-null', v: null },
  { _id: 'bool-false', v: false },
  { _id: 'bool-true', v: true }
]
```

I call:
```
db.bools.findAndModify({query: {_id: "double"}, remove: true});
```

Important: notice that such `_id` doesn't exist in this collection.

### What did you expect to see?

Proxy response message:
```
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "lastErrorObject",
          "value",
          "ok"
        ],
        "lastErrorObject": {
          "$k": [
            "n"
          ],
          "n": 0
        },
        "value": null,
        "ok": {
          "$f": 1
        }
      },
      "Kind": 0
    }
  ]
}
```

### What did you see instead?

FerretDB response:

```
Response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "lastErrorObject",
          "ok"
        ],
        "lastErrorObject": {
          "$k": [
            "n"
          ],
          "n": 0
        },
        "ok": {
          "$f": 1
        }
      },
      "Kind": 0
    }
  ]
}
```

In this response, `value: null` is missing. We should fix it. 

### TODO

Find the tests where this issue number is mentioned, unskip these tests, fix the problem.
See https://github.com/FerretDB/FerretDB/pull/1241/files for the tests that are skipped.

### LINKED ISSUE #2241: `$exists: false` is not handled correctly by `findAndReplace`
### Versions

 FerretDB v0.9.4-rc.1-6-g68b0187

### What did you do?

on the mongosh

```
foo> db.bar.findOneAndReplace({_id: { $exists: false } }, { replaced: true }, { upsert:true} )
MongoServerError: invalid key: "$exists" (key must not start with '$' sign)
```

### What did you expect to see?

the query (`$exists: false`) does not match any existing document, however since the option specifies` upsert: true` it should insert a new document.

note that the following works instead:

```
foo> db.bar.findOneAndReplace({_id: { $exists: true } }, { replaced: true }, { upsert:true} )
```

this also works:

```
foo> db.bar.find({_id: { $exists: false } })
```

### What did you see instead?

`MongoServerError: invalid key: "$exists" (key must not start with '$' sign)`

FerretDB logs:

```
ferretdb  | 2023-03-20T10:08:22.170Z	DEBUG	// 172.21.0.1:38350 -> 172.21.0.3:27017 	clientconn/conn.go:279	Request header: length:   142, id:   22, response_to:    0, opcode: OP_MSG
ferretdb  | 2023-03-20T10:08:22.171Z	DEBUG	// 172.21.0.1:38350 -> 172.21.0.3:27017 	clientconn/conn.go:280	Request message:
ferretdb  | {
ferretdb  |   "Checksum": 0,
ferretdb  |   "FlagBits": 0,
ferretdb  |   "Sections": [
ferretdb  |     {
ferretdb  |       "Document": {
ferretdb  |         "$k": [
ferretdb  |           "findAndModify",
ferretdb  |           "query",
ferretdb  |           "remove",
ferretdb  |           "new",
ferretdb  |           "upsert",
ferretdb  |           "update",
ferretdb  |           "$db"
ferretdb  |         ],
ferretdb  |         "findAndModify": "bar",
ferretdb  |         "query": {
ferretdb  |           "$k": [
ferretdb  |             "_id"
ferretdb  |           ],
ferretdb  |           "_id": {
ferretdb  |             "$k": [
ferretdb  |               "$exists"
ferretdb  |             ],
ferretdb  |             "$exists": false
ferretdb  |           }
ferretdb  |         },
ferretdb  |         "remove": false,
ferretdb  |         "new": false,
ferretdb  |         "upsert": true,
ferretdb  |         "update": {
ferretdb  |           "$k": [
ferretdb  |             "replaced"
ferretdb  |           ],
ferretdb  |           "replaced": true
ferretdb  |         },
ferretdb  |         "$db": "foo"
ferretdb  |       },
ferretdb  |       "Kind": 0
ferretdb  |     }
ferretdb  |   ]
ferretdb  | }
ferretdb  |
ferretdb  |
ferretdb  |
ferretdb  | 2023-03-20T10:08:22.172Z	INFO	pgdb	v4@v4.18.1/conn.go:354	Dialing PostgreSQL server	{"host": "postgres"}
postgres  | 2023-03-20 10:08:22.220 UTC [41] FATAL:  password authentication failed for user "root"
postgres  | 2023-03-20 10:08:22.220 UTC [41] DETAIL:  Role "root" does not exist.
ferretdb  | 2023-03-20T10:08:22.220Z	ERROR	pgdb	v4@v4.18.1/conn.go:354	connect failed	{"err": "failed to connect to `host=postgres user=root database=ferretdb`: failed SASL auth (FATAL: password authentication failed for user \"root\" (SQLSTATE 28P01))"}
postgres  | 	Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
ferretdb  | github.com/jackc/pgx/v4.(*Conn).log
ferretdb  | 	/cache/gomodcache/github.com/jackc/pgx/v4@v4.18.1/conn.go:354
ferretdb  | github.com/jackc/pgx/v4.connect
ferretdb  | 	/cache/gomodcache/github.com/jackc/pgx/v4@v4.18.1/conn.go:225
ferretdb  | github.com/jackc/pgx/v4.ConnectConfig
ferretdb  | 	/cache/gomodcache/github.com/jackc/pgx/v4@v4.18.1/conn.go:113
ferretdb  | github.com/jackc/pgx/v4/pgxpool.ConnectConfig.func1
ferretdb  | 	/cache/gomodcache/github.com/jackc/pgx/v4@v4.18.1/pgxpool/pool.go:232
ferretdb  | github.com/jackc/puddle.(*Pool).constructResourceValue
ferretdb  | 	/cache/gomodcache/github.com/jackc/puddle@v1.3.0/pool.go:558
ferretdb  | github.com/jackc/puddle.(*Pool).Acquire.func1
ferretdb  | 	/cache/gomodcache/github.com/jackc/puddle@v1.3.0/pool.go:317
ferretdb  | 2023-03-20T10:08:22.220Z	WARN	pg/pg.go:129	DBPool: authentication failed	{"username": "", "error": "pgdb.NewPool: failed to connect to `host=postgres user=root database=ferretdb`: failed SASL auth (FATAL: password authentication failed for user \"root\" (SQLSTATE 28P01))"}
ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).DBPool
ferretdb  | 	/src/internal/handlers/pg/pg.go:129
ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).MsgFindAndModify
ferretdb  | 	/src/internal/handlers/pg/msg_findandmodify.go:35
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).handleOpMsg
ferretdb  | 	/src/internal/clientconn/conn.go:517
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).route
ferretdb  | 	/src/internal/clientconn/conn.go:400
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
ferretdb  | 	/src/internal/clientconn/conn.go:289
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
ferretdb  | 	/src/internal/clientconn/listener.go:307
ferretdb  | 2023-03-20T10:08:22.221Z	ERROR	// 172.21.0.1:38350 -> 172.21.0.3:27017 	clientconn/conn.go:552	Response header: length:   348, id:    6, response_to:   22, opcode: OP_MSG
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).logResponse
ferretdb  | 	/src/internal/clientconn/conn.go:552
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
ferretdb  | 	/src/internal/clientconn/conn.go:290
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
ferretdb  | 	/src/internal/clientconn/listener.go:307
ferretdb  | 2023-03-20T10:08:22.222Z	ERROR	// 172.21.0.1:38350 -> 172.21.0.3:27017 	clientconn/conn.go:553	Response message:
ferretdb  | {
ferretdb  |   "Checksum": 0,
ferretdb  |   "FlagBits": 0,
ferretdb  |   "Sections": [
ferretdb  |     {
ferretdb  |       "Document": {
ferretdb  |         "$k": [
ferretdb  |           "ok",
ferretdb  |           "errmsg",
ferretdb  |           "code",
ferretdb  |           "codeName"
ferretdb  |         ],
ferretdb  |         "ok": {
ferretdb  |           "$f": 0
ferretdb  |         },
ferretdb  |         "errmsg": "[msg_findandmodify.go:37 pg.(*Handler).MsgFindAndModify] [pg.go:130 pg.(*Handler).DBPool] pgdb.NewPool: failed to connect to `host=postgres user=root database=ferretdb`: failed SASL auth (FATAL: password authentication failed for user \"root\" (SQLSTATE 28P01))",
ferretdb  |         "code": 1,
ferretdb  |         "codeName": "InternalError"
ferretdb  |       },
ferretdb  |       "Kind": 0
ferretdb  |     }
ferretdb  |   ]
ferretdb  | }
ferretdb  |
ferretdb  |
ferretdb  |
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).logResponse
ferretdb  | 	/src/internal/clientconn/conn.go:553
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
ferretdb  | 	/src/internal/clientconn/conn.go:290
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
ferretdb  | 	/src/internal/clientconn/listener.go:307
ferretdb  | 2023-03-20T10:08:22.223Z	WARN	listener	clientconn/listener.go:311	Connection stopped	{"conn": "172.21.0.1:38350 -> 172.21.0.3:27017", "error": "fatal error"}
ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
ferretdb  | 	/src/internal/clientconn/listener.go:311
ferretdb  | 2023-03-20T10:08:22.519Z	DEBUG	// 172.21.0.1:38324 -> 172.21.0.3:27017 	clientconn/conn.go:279	Request header: length:    52, id:   23, response_to:    0, opcode: OP_MSG
ferretdb  | 2023-03-20T10:08:22.519Z	DEBUG	// 172.21.0.1:38324 -> 172.21.0.3:27017 	clientconn/conn.go:280	Request message:
ferretdb  | {
ferretdb  |   "Checksum": 0,
ferretdb  |   "FlagBits": 0,
ferretdb  |   "Sections": [
ferretdb  |     {
ferretdb  |       "Document": {
ferretdb  |         "$k": [
ferretdb  |           "ismaster",
ferretdb  |           "$db"
ferretdb  |         ],
ferretdb  |         "ismaster": true,
ferretdb  |         "$db": "admin"
ferretdb  |       },
ferretdb  |       "Kind": 0
ferretdb  |     }
ferretdb  |   ]
ferretdb  | }
ferretdb  |
ferretdb  |
ferretdb  |
ferretdb  | 2023-03-20T10:08:22.520Z	DEBUG	// 172.21.0.1:38324 -> 172.21.0.3:27017 	clientconn/conn.go:552	Response header: length:   190, id:    2, response_to:   23, opcode: OP_MSG
ferretdb  | 2023-03-20T10:08:22.521Z	DEBUG	// 172.21.0.1:38324 -> 172.21.0.3:27017 	clientconn/conn.go:553	Response message:
ferretdb  | {
ferretdb  |   "Checksum": 0,
ferretdb  |   "FlagBits": 0,
ferretdb  |   "Sections": [
ferretdb  |     {
ferretdb  |       "Document": {
ferretdb  |         "$k": [
ferretdb  |           "ismaster",
ferretdb  |           "maxBsonObjectSize",
ferretdb  |           "maxMessageSizeBytes",
ferretdb  |           "maxWriteBatchSize",
ferretdb  |           "localTime",
ferretdb  |           "minWireVersion",
ferretdb  |           "maxWireVersion",
ferretdb  |           "readOnly",
ferretdb  |           "ok"
ferretdb  |         ],
ferretdb  |         "ismaster": true,
ferretdb  |         "maxBsonObjectSize": 16777216,
ferretdb  |         "maxMessageSizeBytes": 48000000,
ferretdb  |         "maxWriteBatchSize": 100000,
ferretdb  |         "localTime": {
ferretdb  |           "$d": 1679306902519
ferretdb  |         },
ferretdb  |         "minWireVersion": 13,
ferretdb  |         "maxWireVersion": 17,
ferretdb  |         "readOnly": false,
ferretdb  |         "ok": {
ferretdb  |           "$f": 1
ferretdb  |         }
ferretdb  |       },
ferretdb  |       "Kind": 0
ferretdb  |     }
ferretdb  |   ]
ferretdb  | }
ferretdb  |
ferretdb  |
ferretdb  |
```

### Environment

```markdown
- OS: docker image ghcr.io/ferretdb/ferretdb-dev:main
- Architecture:
- Version: FerretDB v0.9.4-rc.1-6-g68b0187
- Deployment:
- Deployment details:

docker-compose.yml


version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb-dev:main
    container_name: ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

networks:
  default:
    name: ferretdb
```
```

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #2241.
Closes #1243.
Closes #1098.

In this PR, duplicated logic and codes were added to common package instead of duplicating them in pg and tigris handlers.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handlers/tigris/msg_findandmodify.go [hunk 1]
```diff
@@ -130,30 +132,28 @@ func (h *Handler) MsgFindAndModify(ctx context.Context, msg *wire.OpMsg) (*wire.
 				if _, err = updateDocument(ctx, dbPool, &qp, upsert); err != nil {
 					return nil, err
 				}
-			}
-		}
 
-		var resultDoc *types.Document
-		if params.ReturnNewDocument || len(resDocs) == 0 {
```
Comment (chilagrow) [inline internal/handlers/tigris/msg_findandmodify.go:137]: `len(resDocs) == 0` case returns early, see L103. So this is unreachable hence removing

File: internal/handlers/pg/msg_findandmodify.go [hunk 2]
```diff
@@ -117,49 +118,45 @@ func (h *Handler) MsgFindAndModify(ctx context.Context, msg *wire.OpMsg) (*wire.
...
-					if _, err = updateDocument(ctx, tx, &queryParams, upsert); err != nil {
-						return err
-					}
+				if _, err = updateDocument(ctx, tx, &qp, upsert); err != nil {
+					return lazyerrors.Error(err)
 				}
-			}
 
-			var resultDoc *types.Document
-			if params.ReturnNewDocument || len(resDocs) == 0 {
```
Comment (chilagrow) [inline internal/handlers/pg/msg_findandmodify.go:144]: `len(resDocs) == 0` case returns early, see L109. So this is unreachable hence removing

File: integration/findandmodify_test.go [hunk 3]
```diff
@@ -122,6 +122,32 @@ func TestFindAndModifyErrors(t *testing.T) {
 			},
 			altMessage: "BSON field 'upsert' is the wrong type 'string', expected types '[bool, long, int, decimal, double]'",
 		},
+		"DollarPrefixedFieldName": {
```
Comment (rumyantseva) [inline integration/findandmodify_test.go:125]: I think if we can use compat tests, we should use them.
Why don't these cases use compat tests?

File: internal/handlers/common/findandmodify.go [hunk 4]
```diff
@@ -168,3 +178,152 @@ func GetFindAndModifyParams(doc *types.Document, l *zap.Logger) (*FindAndModifyP
...
+		res.ReturnValue = res.Update
+	}
+
+	return res, err
+}
+
+// insertDocuments creates an insert document from the parameter.
+// When inserting new document we must check that `_id` is present, so we must extract `_id`
+// from query or generate a new one.
+func insertDocuments(params *FindAndModifyParams) (*types.Document, error) {
```
Comment (rumyantseva) [inline internal/handlers/common/findandmodify.go:212]: It's a bit confusing to call it `insertDocuments` because, as far as I can see, this function doesn't insert anything. Maybe it could be called something like `prepareDocumentForInsert`? It prepares a single document, right?

File: internal/handlers/common/findandmodify.go [hunk 5]
```diff
@@ -168,3 +178,152 @@ func GetFindAndModifyParams(doc *types.Document, l *zap.Logger) (*FindAndModifyP
...
+		}
+
+		insert.Set("_id", id)
+	}
+
+	return insert, nil
+}
+
+// updateDocuments updates the first document with update parameters.
+func updateDocuments(docs []*types.Document, params *FindAndModifyParams) (*types.Document, error) {
```
Comment (rumyantseva) [inline internal/handlers/common/findandmodify.go:236]: Same here: this function doesn't update but prepares a document to be sent for update, right?

File: internal/handlers/common/findandmodify.go [hunk 6]
```diff
@@ -168,3 +178,152 @@ func GetFindAndModifyParams(doc *types.Document, l *zap.Logger) (*FindAndModifyP
...
+	}
+
+	_, hasOp, err := hasFilterOperator(idDoc)
+	if err != nil {
+		return nil, err
+	}
+
+	if hasOp {
+		return types.NewObjectID(), nil
+	}
```
Comment (rumyantseva) [inline internal/handlers/common/findandmodify.go:287]: This is an interesting piece of logic. Do we have a compat test that covers it?

File: internal/handlers/common/findandmodify.go [hunk 7]
```diff
@@ -168,3 +178,152 @@ func GetFindAndModifyParams(doc *types.Document, l *zap.Logger) (*FindAndModifyP
 		MaxTimeMS:          maxTimeMS,
 	}, nil
 }
+
+// UpsertDocument updates the first document if exists, or create an insert document
+// from the params if no documents in query result docs.
+func UpsertDocument(docs []*types.Document, params *FindAndModifyParams) (*UpsertParams, error) {
```
Comment (rumyantseva) [inline internal/handlers/common/findandmodify.go:184]: Same here: this function doesn't upsert anything.

File: internal/handlers/common/findandmodify.go [hunk 8]
```diff
@@ -32,6 +35,13 @@ type FindAndModifyParams struct {
 	MaxTimeMS                             int32
 }
 
+// UpsertParams represents parameters for upsert, if the document exists Update is set.
+// Otherwise, Insert is set. It returns ReturnValue to return to the client.
+type UpsertParams struct {
+	Insert, Update *types.Document
```
Comment (rumyantseva) [inline internal/handlers/common/findandmodify.go:41]: Hmm, is it possible that both `Insert` and `Update` are not nil?

If not, should this be structured differently?
E.g. 
```
doc *types.Document
insert bool // if false, update operation is expected
```

And also, I don't really understand what is `ReturnValue`, what is the difference between it and the document itself?

**Review by rumyantseva — CHANGES_REQUESTED** [review]
I like that we cover more cases, and I like the idea of refactoring `findAndModify`. 
However, I find some structuring/naming a bit confusing. 

Let's decide if we want to have a quick fix for this particular bug and a proper refactoring later, or if a proper refactoring as a part of this issue. 

Also, as agreed, I created a separate issue to cover the rest of `$exists` cases for `findAndModify` - https://github.com/FerretDB/FerretDB/issues/2400.

File: integration/findandmodify_test.go (hunk 3 above)
Comment (chilagrow) [reply integration/findandmodify_test.go:125]: Yes, these ones can be in compat!

File: internal/handlers/common/findandmodify.go (hunk 6 above)
Comment (chilagrow) [reply internal/handlers/common/findandmodify.go:287]: Yes `UpsertExpressionKey`. And this was the core cause of https://github.com/FerretDB/FerretDB/issues/2241

File: internal/handlers/common/findandmodify.go (hunk 5 above)
Comment (chilagrow) [reply internal/handlers/common/findandmodify.go:236]: Thanks, renamed to `prepareDocumentForInsert`

File: internal/handlers/common/findandmodify.go (hunk 7 above)
Comment (chilagrow) [reply internal/handlers/common/findandmodify.go:184]: Renamed to `PrepareDocumentForUpsert`

File: internal/handlers/common/findandmodify.go [hunk 9]
```diff
@@ -32,6 +50,21 @@ type FindAndModifyParams struct {
 	MaxTimeMS                             int32
 }
 
+// UpsertParams represents parameters for upsert, if the document exists Update is set.
+// Otherwise, Insert is set. It returns ReturnValue to return to the client.
+type UpsertParams struct {
+	// ReturnValue is the value set on the command response.
+	// It returns original document for update operation, and null for insert operation.
+	// If FindAndModifyParams.ReturnNewDocument is true, it returns upserted document.
+	ReturnValue any
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/handlers/common/findandmodify.go:59]: Yes the caller can figure it out. But I didn't want to add new logic to both pg and tigris handler, that's why. Once we start having more handlers, we prefer to keep as much logic as possible in the common. :hugs:

[the remark this answers is not in the document]
Comment (rumyantseva) [reply internal/handlers/common/findandmodify.go:59]: Agree! As we will refactor things separately, let's keep it as is for now.

**Review by rumyantseva — APPROVED** [review]
As agreed, in the scope of this PR we fix a particular bug (actually, three bugs)!
I like the test cases and I like how we started moving the logic to common!
