### PR TITLE
Make `db.collection.stats()` & `.dataSize()` work from `mongosh`

### LINKED ISSUE #242: `db.collection.stats()` & `.dataSize()` does not work from mongosh
Run FerretDB:

```
➜ make run
```

Run mongosh:
```
➜ mongosh --norc --port 27017

test> use monila
switched to db monila
monila> db.actor.stats()
MongoNetworkError: connection 8 to 127.0.0.1:27017 closed
```

Logs from FerretDB:

```
2022-01-07T23:28:55.445+0300	DPANIC	// 127.0.0.1:54978 -> 127.0.0.1:27017 	clientconn/conn.go:118	interface conversion: interface {} is nil, not string
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func1
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:118
runtime.gopanic
	runtime/panic.go:844
runtime.panicdottypeE
	runtime/iface.go:262
github.com/FerretDB/FerretDB/internal/handlers/shared.(*Handler).MsgCollStats
	github.com/FerretDB/FerretDB/internal/handlers/shared/msg_collstats.go:33
github.com/FerretDB/FerretDB/internal/handlers.(*Handler).handleOpMsg
	github.com/FerretDB/FerretDB/internal/handlers/handler.go:163
github.com/FerretDB/FerretDB/internal/handlers.(*Handler).Handle
	github.com/FerretDB/FerretDB/internal/handlers/handler.go:85
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:171
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:138
panic: interface conversion: interface {} is nil, not string [recovered]
	panic: interface conversion: interface {} is nil, not string
(err = <nil>)

goroutine 45 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001620c0, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x60a
go.uber.org/zap.(*SugaredLogger).log(0xc00013c010, 0x3, {0xe665c4, 0xd}, {0xc00031d228, 0x2, 0x2}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.19.1/sugar.go:227 +0x13b
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	go.uber.org/zap@v1.19.1/sugar.go:154
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func1()
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:118 +0x1ab
panic({0xdc2720, 0xc0003b5140})
	runtime/panic.go:844 +0x258
github.com/FerretDB/FerretDB/internal/handlers/shared.(*Handler).MsgCollStats(0xc00013a000, {0xf91660, 0xc0001120c0}, 0x2?)
	github.com/FerretDB/FerretDB/internal/handlers/shared/msg_collstats.go:33 +0x7fa
github.com/FerretDB/FerretDB/internal/handlers.(*Handler).handleOpMsg(0xc000116050, {0xf91660, 0xc0001120c0}, 0x13c80c0?)
	github.com/FerretDB/FerretDB/internal/handlers/handler.go:163 +0x8b1
github.com/FerretDB/FerretDB/internal/handlers.(*Handler).Handle(0xc000116050, {0xf91660, 0xc0001120c0}, 0xc0003b82c0, {0xf91f70?, 0xc000146a80?})
	github.com/FerretDB/FerretDB/internal/handlers/handler.go:85 +0x22e
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc000112080, {0xf91660?, 0xc0001120c0})
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:171 +0xab4
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2()
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:138 +0x5df
created by github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:110 +0xb8e
Makefile.kev:68: recipe for target 'run' failed
make: *** [run] Error 2
```

It looks like the command is stored in capitalized (`collStats`) form in the document:

```
2022-01-07T23:28:55.444+0300	DEBUG	// 127.0.0.1:54978 -> 127.0.0.1:27017 	clientconn/conn.go:163	Request message:
{
  "Checksum": 0,
  "FlagBits": [],
  "Sections": [
    {
      "Document": {
        "$k": [
          "collStats",
          "$db"
        ],
        "collStats": "actor",
        "$db": "monila"
      },
      "Kind": 0
    }
  ]
}
```

And we could not find it:
- https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/shared/msg_collstats.go#L33

### PR DESCRIPTION
**Pull request by ekalinin**
Closes #242.

Besides that tidied up the data types (`int64 -> int32`) in the response of the `collStats`.

### CODE REVIEW

File: internal/handlers/shared/msg_collstats.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func (h *Handler) MsgCollStats(ctx context.Context, msg *wire.OpMsg) (*wire.OpMs
 	}
 
 	m := document.Map()
-	collection := m[document.Command()].(string)
+	collection := m["collStats"].(string)
```
Comment (AlekSi) [inline internal/handlers/shared/msg_collstats.go:33]: Can it be invoked as `db.runCommand({cOlLsTaTs: "film"})`? Would it work?

Comment (ekalinin) [reply internal/handlers/shared/msg_collstats.go:33]: Yes, it can.

And MongoDB's response is:

```
monila> db.runCommand({ cOlLsTaTs: "actor" })
MongoServerError: no such command: 'cOlLsTaTs'
```

While FerretDB's response is:

```
monila> db.runCommand({ cOlLsTaTs: "actor" })
MongoNetworkError: connection 16 to 127.0.0.1:27017 closed
```

Comment (AlekSi) [reply internal/handlers/shared/msg_collstats.go:33]: Ok, so MongoDB command are case-sensitive

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
Thank you!
