### PR TITLE
Fix long overflow detection on `$mul`

### LINKED ISSUE #2057: Fix pushdowns for large double values
### What should be done?

When we filter large double values (for example `float64(2<<61)` While comparing numbers to large double values with at least 16 digits before floating point, MongoDB rounds both values to 16 digits before comparison. 

FerretDB shares the same behavior, although after introducing pushdowns, documents with large values are sometimes omitted, because we don't round those values on the database query layer. We should tweak those queries to stop losing data before filtering.

~This is probably, because we might marshal those values to JSON before putting them into the query. We should check that, and fix it.~ *we should also remove unnecessary `marshalSingleValue` calls*

Make a separate PR for strings first.

### Where?
In PostgreSQL and Tigris handler. 
Check where this issue number is mentioned.

## Definition Of Done
- [x] Investigate if we are sure that we marshal values to JSON before inserting them to query.
- [x] If not, find in which place we round the value.
- [ ] Fix the bug
- [ ] Uncomment skipped tests under this issue number.

### PR DESCRIPTION
**Pull request by noisersup**
# Description

Closes #2057.

The current check for overflows doesn't work correctly for most long values larger than 1<<53, and creates false-negatives, by returning overflow errors on values that didn't overflow. That's because of lost precision on float64 multiplication.

For example, the current state doesn't fail on `9007199254740992 * 42`, but fails for `9007199254740993 * 42`, as at this point, the first number is converted to float64 unprecisely, which results in different result.

## Readiness checklist

* [x] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handlers/common/params.go [hunk 1]
```diff
@@ -391,6 +374,26 @@ func multiplyNumbers(v1, v2 any) (any, error) {
 	}
 }
 
+// multiplyLongSafely returns the multiplication of two int64 values.
+// It handles int64 overflows, and returns errLongExceeded error on one.
+//
+// Please prefer to use multiplyNumbers instead of this function.
+func multiplyLongSafely(v1, v2 int64) (int64, error) {
+	switch {
+	case v1 == 0 || v2 == 0 || v1 == 1 || v2 == 1:
```
Comment (rumyantseva) [inline internal/handlers/common/params.go:383]: I see why `v2 == 0` is here - to avoid division by zero later, but why do the other values are here too? Are those cases also special?

**Review by rumyantseva — COMMENTED** [review]
Started reading the code (I haven't gone through `TestMultiplyLongSafely` yet). Asked one question.

File: internal/handlers/common/params.go (hunk 1 above)
Comment (noisersup) [reply internal/handlers/common/params.go:383]: We check for 1 and 0 for every value, because it's possible to multiply those with MinInt64. Without this check, function returns overflow on operations like `MinInt64 * 1` or `0 * MinInt64`, etc.

Comment (noisersup) [reply internal/handlers/common/params.go:383]: Should I leave a comment explaining that? It was confusing either to me, and I've written this code 2 hours ago...

Comment (noisersup) [reply internal/handlers/common/params.go:383]: although now I'm thinking about `-1` values either. It's not ready for review yet sorry

File: internal/handlers/common/params_test.go [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+	for name, tc := range map[string]struct {
+		values []int64 // [v1,v2,v1+v2] or [v1,v2] if you don't want to check multiplication result
+
+		// overflow checks if at least one value returned errLongExceeded error.
+		overflow bool // defaults to false
+
+		// valuesRange allows to execute test for the numbers next to v1.
+		// if v1=42 and valuesRange=2, following numbers will be tested: [42,43,44]
+		// It shouldn't be used with multiplication result, but rather to test overflows on large ranges.
+		valuesRange int
```
Comment (noisersup) [inline internal/handlers/common/params_test.go:37]: This one is useful if we want to check for overflow on large values. We haven't realized that we have a bug here so far, because we've used one or two single big values which were able to be presented as float64 precisely. While all other numbers around those values were loosing their precision.

**Review by chilagrow — COMMENTED** [review]
Thanks for fixing the bug! The tests are a bit complicated, I think it's worth simplifying

File: internal/handlers/common/params_test.go [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestMultiplyLongSafely(t *testing.T) {
+	t.Parallel()
+
+	for name, tc := range map[string]struct {
+		values []int64 // [v1,v2,v1+v2] or [v1,v2] if you don't want to check multiplication result
```
[the remark this answers is not in the document]
Comment (noisersup) [reply internal/handlers/common/params_test.go:29]: I didn't want to create so many lines of codes just to place similar testcases under separate names, but yes we can do it

File: internal/handlers/common/params.go [hunk 4]
```diff
@@ -391,6 +374,32 @@ func multiplyNumbers(v1, v2 any) (any, error) {
 	}
 }
 
+// multiplyLongSafely returns the multiplication of two int64 values.
+// It handles int64 overflows, and returns errLongExceeded error on one.
+//
+// Please prefer to use multiplyNumbers instead of this function.
```
[the remark this answers is not in the document]
Comment (noisersup) [reply internal/handlers/common/params.go:380]: We had and it's covered [here](https://github.com/FerretDB/FerretDB/pull/2232/files#diff-a21b8c640c12ecfe3c572f59caf5486544b411403f77500597b373634b17b726R364) and [here](https://github.com/FerretDB/FerretDB/pull/2232/files#diff-a21b8c640c12ecfe3c572f59caf5486544b411403f77500597b373634b17b726R354)

File: internal/handlers/common/params_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/handlers/common/params_test.go:29]: Just currently the logic of getting v1,v2 and expected is not so trivial. Sometimes, a bit repetitive way is easier to maintain, sorry for a picky comment :sweat:

[the remark this answers is not in the document]
Comment (noisersup) [reply internal/handlers/common/params_test.go]: No worries! It doesn't sound picky :smile:

File: internal/handlers/common/params.go (hunk 4 above)
Comment (rumyantseva) [inline internal/handlers/common/params.go:380]: But when should we use this function if `multiplyNumbers` is preferred instead?

File: internal/handlers/common/params.go (hunk 1 above)
Comment (rumyantseva) [reply internal/handlers/common/params.go:385]: @noisersup I remember you said you want to try `-1` and some other cases, is it still actual? I see the tests that handle `-1`, but according to the logic in this function, `errLongExceeded` will be returned for them, right?

File: internal/handlers/common/params_test.go [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+			err: errLongExceeded,
+		},
+	} {
+		name, tc := name, tc
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			actualRes, err := multiplyLongSafely(tc.v1, tc.v2)
+			assert.Equal(t, tc.err, err)
+
```
Comment (rumyantseva) [inline internal/handlers/common/params_test.go:88]:
```suggestion
```

File: internal/handlers/common/params_test.go (hunk 2 above)
Comment (noisersup) [reply internal/handlers/common/params_test.go]: Fixed, I picked the value from the range that might be rounded because of double precision

File: internal/handlers/common/params.go (hunk 1 above)
Comment (noisersup) [reply internal/handlers/common/params.go:385]: Not exactly, in the first `multiplyLongSafely` case we check only for `0` and `1`, as those are only values possible to multiply correctly with `MinInt64`.

All other values compared to any other value are handled after the switch case, and all overflows should be detected there.

File: internal/handlers/common/params.go [hunk 6]
```diff
@@ -351,16 +351,8 @@ func multiplyNumbers(v1, v2 any) (any, error) {
 
 			return res, nil
 		case int64:
-			res := int64(v1) * v2
+			return multiplyLongSafely(int64(v1), v2)
```
[the remark this answers is not in the document]
Comment (noisersup) [reply internal/handlers/common/params.go:354]: That's strange, for me it shows: "No Files covered by tests were changed"

[the remark this answers is not in the document]
Comment (rumyantseva) [reply internal/handlers/common/params.go:354]: Probably something on CI then... Let's wait for CI to pass and let's see if it still persists.

File: internal/handlers/common/params.go (hunk 4 above)
Comment (noisersup) [reply internal/handlers/common/params.go:380]: I guess that only in `multiplyNumbers` as it's just a helper function for it

Comment (rumyantseva) [reply internal/handlers/common/params.go:380]: Hmm, maybe we can rephrase the comment this way? Something like `Please always use multiplyNumbers as it calls multiplyLongSafely when needed.`

File: internal/handlers/common/params_test.go [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+		"Zero": {
+			v1:       0,
+			v2:       1000,
+			expected: 0,
+		},
+		"One": {
+			v1:       42,
+			v2:       1,
+			expected: 42,
+		},
```
Comment (chilagrow) [inline internal/handlers/common/params_test.go:40]: So if we remove https://github.com/FerretDB/FerretDB/pull/2232/files#diff-a21b8c640c12ecfe3c572f59caf5486544b411403f77500597b373634b17b726R385
at least some test fail.
```
		"Zero": {
			v1:       0,
			v2:       MinInt64,
			expected: MinInt64,
		},
		"One": {
			v1:       1,
			v2:       MinInt64,
			expected: MinInt64,
		},
```

Comment (noisersup) [reply internal/handlers/common/params_test.go:40]: Yes, those will fail as `MinInt64` is handled explicitly

File: internal/handlers/common/params.go (hunk 4 above)
Comment (noisersup) [reply internal/handlers/common/params.go]: fixed

File: internal/handlers/common/params.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (rumyantseva) [reply internal/handlers/common/params.go:354]: Yeah, that looks fixed

**Review by rumyantseva — APPROVED** [review]
LGTM
