### PR TITLE
Fix version detection for embeddable package

### LINKED ISSUE #4889: Embeddable package is broken
### What should be done?

```
panic: Invalid build/version/version.txt file content. Please run `bin/task gen-version`.
	Alternatively, create this file manually with a content similar to
	the output of `git describe`: `v<major>.<minor>.<patch>`.
	See https://pkg.go.dev/github.com/FerretDB/FerretDB/v2/build/version

goroutine 1 [running]:
github.com/FerretDB/FerretDB/v2/build/version.init.0()
	/Users/aleksi/Soft/GOPATH/pkg/mod/github.com/!ferret!d!b/!ferret!d!b/v2@v2.0.0/build/version/version.go:148 +0x9a0
exit status 2
```

But that file is not present in the repo and Go module.
Go 1.24 changed how the version is stored inside the module for "library modules". We probably could use that.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/build/version
https://github.com/FerretDB/embedded-example

### Definition of Done

- `build/version` works for both normal FerretDB and for embedding;
- version is known in as many situations as possible.

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Closes #4889.

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [x] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: build/version/version.go [hunk 1]
```diff
@@ -94,77 +104,183 @@ func Get() *Info {
...
-		return
-	}
-
-	// for tests
-	if buildInfo.Main.Path == "" {
-		return
-	}
-
+	// Those files are present in two cases:
+	// 1. When we are working int the FerretDB repo (building binaries, running integration tests, etc),
```
Comment (chilagrow) [inline build/version/version.go:138]:
```suggestion
	// 1. When we are working in the FerretDB repo (building binaries, running integration tests, etc),
```

**Review by chilagrow — DISMISSED** [review]
Thanks for in-depth explanation :hugs:
