### PR TITLE
Fix bitwise operators

### LINKED ISSUE #442: Bitwise operators behave differently
While working on #417 I noticed that MongoDB and FerretDB behave differently on the first test I wrote. See #443.

We should port tests from handler_test.go and dance, and fix the difference in behavior.

### PR DESCRIPTION
**Pull request by w84thesun**
Closes #442.

### CODE REVIEW

File: integration/query_bitwise_test.go [hunk 1]
```diff
@@ -15,41 +15,517 @@
...
+		})
+	}
+}
+
+func TestQueryBitwiseAnySet(t *testing.T) {
+	t.Parallel()
+	ctx, collection := setup(t, shareddata.Scalars)
+
+	for name, tc := range map[string]struct {
+		filter      any
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:426]: `filter` is a `value`, isn't it?

File: integration/query_bitwise_test.go [hunk 2]
```diff
@@ -15,41 +15,517 @@
...
+		})
+	}
+}
+
+func TestQueryBitwiseAnyClear(t *testing.T) {
+	t.Parallel()
+	ctx, collection := setup(t, shareddata.Scalars)
+
+	for name, tc := range map[string]struct {
+		filter      any
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:302]: `filter` is a `value`, also, WDYT?

File: internal/handlers/common/filter.go [hunk 3]
```diff
@@ -594,76 +594,231 @@ func filterFieldExprSize(fieldValue any, sizeValue any) (bool, error) {
...
+		if err != nil {
+			return false, formatBitwiseOperatorErr(err, "$bitsAllClear", maskValue)
+		}
+		return (^uint64(value) & bitmask) == bitmask, nil
 
-	for i := 0; i < len(fieldBinary.B); i++ {
-		if (fieldBinary.B[i] & maskBinary.B[i]) != 0 {
+	case float64:
+		// TODO check float negative zero
+		if value != math.Trunc(value) || math.IsNaN(value) || math.IsInf(value, 0) || value > math.MaxInt64 {
```
Comment (seeforschauer) [inline internal/handlers/common/filter.go:614]: can it be in several strings? 
why not to check negative zero now?

**Review by seeforschauer — CHANGES_REQUESTED** [review]
Some naming and linters, others seems like ok. Thank you.

File: internal/handlers/common/filter.go (hunk 3 above)
Comment (w84thesun) [reply internal/handlers/common/filter.go:614]: Why do you want to split it?
Negative zero seems to be another tough thing. It's not so easy to check for that as far as I get.

File: integration/query_bitwise_test.go (hunk 1 above)
Comment (w84thesun) [reply integration/query_bitwise_test.go:426]: I think we should stick with the same naming across tests.

File: internal/handlers/common/filter.go (hunk 3 above)
Comment (seeforschauer) [reply internal/handlers/common/filter.go:614]: > Why do you want to split it? 

different conditions on separate lines.

> Negative zero seems to be another tough thing. It's not so easy to check for that as far as I get.

ok

File: integration/query_bitwise_test.go (hunk 1 above)
Comment (AlekSi) [reply integration/query_bitwise_test.go:426]: Yes, we should. But that's not a filter, that's only a value for it. Compare and contrast:

Whole filter: https://github.com/FerretDB/FerretDB/blob/373e79c3b929304df30b7d9e18a578d003d60843/integration/query_comparision_test.go#L157

Value for filter: https://github.com/FerretDB/FerretDB/blob/373e79c3b929304df30b7d9e18a578d003d60843/integration/query_comparision_test.go#L383

File: integration/query_bitwise_test.go [hunk 4]
```diff
@@ -15,41 +15,517 @@
...
-				"binary-empty", "double-negative-zero", "double-zero",
-				"int32-min", "int32-zero", "int64-min", "int64-zero",
+				"binary",
+				"double-whole",
+				"int32", "int32-max",
+				"int64", "int64-max",
+			},
+		},
+		"FloatNegativeValue": {
+			filter: int32(-1),
```
Comment (AlekSi) [inline integration/query_bitwise_test.go:448]: That's not float. Also, there is no "float" at all; BSON and we call it "double"

Comment (w84thesun) [reply integration/query_bitwise_test.go]: Fixed

File: integration/query_bitwise_test.go (hunk 1 above)
Comment (w84thesun) [reply integration/query_bitwise_test.go]: Fixed

File: integration/query_bitwise_test.go [hunk 5]
```diff
@@ -15,41 +15,528 @@
...
+		"Int32NegativeValue": {
+			value: int32(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAllClear: -1",
+			},
+		},
+
+		"Int64": {
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:130]:
```suggestion
		"MaxInt64": {
```

File: integration/query_bitwise_test.go [hunk 6]
```diff
@@ -15,41 +15,528 @@
...
+		"Int32NegativeValue": {
+			value: int32(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAllSet: -1",
+			},
+		},
+
+		"Int64": {
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:247]:
```suggestion
		"MaxInt64": {
```

File: integration/query_bitwise_test.go [hunk 7]
```diff
@@ -15,41 +15,528 @@
...
+		"Int32NegativeValue": {
+			value: int32(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAnyClear: -1",
+			},
+		},
+
+		"Int64": {
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:364]:
```suggestion
		"MaxInt64": {
```

File: integration/query_bitwise_test.go [hunk 8]
```diff
@@ -15,41 +15,528 @@
...
+		"Int32NegativeValue": {
+			value: int32(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAnySet: -1",
+			},
+		},
+
+		"Int64": {
```
Comment (seeforschauer) [inline integration/query_bitwise_test.go:491]:
```suggestion
		"MaxInt64": {
```

File: internal/handlers/common/filter.go (hunk 3 above)
Comment (seeforschauer) [inline internal/handlers/common/filter.go:614]:
```suggestion
		if value != math.Trunc(value) || 
		   math.IsNaN(value) || 
		   math.IsInf(value, 0) || 
		   value > math.MaxInt64 {
```

File: internal/handlers/common/filter.go [hunk 9]
```diff
@@ -594,76 +594,231 @@ func filterFieldExprSize(fieldValue any, sizeValue any) (bool, error) {
...
+		if err != nil {
+			return false, formatBitwiseOperatorErr(err, "$bitsAllSet", maskValue)
+		}
+		return (uint64(value) & bitmask) == bitmask, nil
 
-	for i := 0; i < len(fieldBinary.B); i++ {
-		if (fieldBinary.B[i] & maskBinary.B[i]) != maskBinary.B[i] {
+	case float64:
+		// TODO check float negative zero
+		if value != math.Trunc(value) || math.IsNaN(value) || math.IsInf(value, 0) || value > math.MaxInt64 {
```
Comment (seeforschauer) [inline internal/handlers/common/filter.go:671]:
```suggestion
		if value != math.Trunc(value) || 
		math.IsNaN(value) || 
		math.IsInf(value, 0) || 
		value > math.MaxInt64 {
```

File: internal/handlers/common/filter.go (hunk 3 above)
Comment (seeforschauer) [reply internal/handlers/common/filter.go:614]: When editing if condition: adding or deleting, it will clearly and explicitly visible what was added, deleted or what condition was edited. 

Having single row for all condition it would be more difficult to catch the change in a row.

**Comment by w84thesun** [comment]
Tests for BinData would be in #508

**Review by seeforschauer — APPROVED** [review]

File: integration/query_bitwise_test.go [hunk 10]
```diff
@@ -15,41 +15,503 @@
...
+		"Int32NegativeValue": {
+			value: int32(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAllClear: -1",
+			},
+		},
+
+		"MaxInt64": {
```
Comment (AlekSi) [inline integration/query_bitwise_test.go:97]: Int64 should be a prefix

File: integration/query_bitwise_test.go [hunk 11]
```diff
@@ -15,41 +15,503 @@
...
+		"Int64NegativeValue": {
+			value: int64(-1),
+			err: mongo.CommandError{
+				Code:    9,
+				Name:    "FailedToParse",
+				Message: "Expected a positive number in: $bitsAllClear: -1",
+			},
+		},
+
+		"Array": {
```
Comment (AlekSi) [inline integration/query_bitwise_test.go:114]: Composite types should be before scalar types: https://pkg.go.dev/github.com/FerretDB/FerretDB@v0.1.1/internal/types#hdr-Mapping

File: internal/handlers/common/params.go [hunk 12]
```diff
@@ -99,104 +100,76 @@ func GetWholeNumberParam(value any) (int64, error) {
...
+			if byteAt == 0 {
+				continue
+			}
+
+			if b < 8 {
+				bitmask |= uint64(byteAt) << b
+			} else {
+				bitmask |= 1 << 63
+			}
+		}
```
Comment (AlekSi) [inline internal/handlers/common/params.go:166]: Let's remove that code if it is not tested (and, I guess, does not work the same way as MongoDB)

Comment (w84thesun) [reply internal/handlers/common/params.go:166]: I've added tests for that code.

File: integration/query_bitwise_test.go (hunk 11 above)
Comment (w84thesun) [reply integration/query_bitwise_test.go]: Fixed

File: integration/query_bitwise_test.go (hunk 10 above)
Comment (w84thesun) [reply integration/query_bitwise_test.go]: Fixed

**Review by seeforschauer — APPROVED** [review]

File: internal/handlers/common/filter.go [hunk 13]
```diff
@@ -594,76 +594,170 @@ func filterFieldExprSize(fieldValue any, sizeValue any) (bool, error) {
...
-	for i := 0; i < len(fieldBinary.B); i++ {
-		if (fieldBinary.B[i] & maskBinary.B[i]) != 0 {
+	case int64:
+		bitmask, err := getBinaryMaskParam(maskValue)
+		if err != nil {
+			return false, formatBitwiseOperatorErr(err, "$bitsAllClear", maskValue)
+		}
+		return (^uint64(value) & bitmask) == bitmask, nil
+
+	case float64:
```
Comment (AlekSi) [inline internal/handlers/common/filter.go:612]: Types order

File: internal/handlers/common/filter.go [hunk 14]
```diff
@@ -594,76 +594,170 @@ func filterFieldExprSize(fieldValue any, sizeValue any) (bool, error) {
...
-	for i := 0; i < len(fieldBinary.B); i++ {
-		if (fieldBinary.B[i] & maskBinary.B[i]) != maskBinary.B[i] {
+	case int64:
+		bitmask, err := getBinaryMaskParam(maskValue)
+		if err != nil {
+			return false, formatBitwiseOperatorErr(err, "$bitsAllSet", maskValue)
+		}
+		return (uint64(value) & bitmask) == bitmask, nil
+
+	case float64:
```
Comment (AlekSi) [inline internal/handlers/common/filter.go:654]: Types order

**Review by AlekSi — APPROVED** [review]
