### PR TITLE
Fix query projection for top level fields

### LINKED ISSUE #537: Fix projections tests
Investigate why projection doesn't work as it should and fix `TestQueryProjection`

### LINKED ISSUE #2299: Projection with `_id` returns all fields
### Versions

commit.txt: a06bd4bf1832bceed7189cff07d788cdb11e2155
version.txt: v0.9.4-1-ga06bd4bf

### What did you do?

See repro in #2298.

### What did you expect to see?

2 documents returned with just the `_id` field.

### What did you see instead?

All fields.

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go version go1.20 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 23.0.1
```

### PR DESCRIPTION
**Pull request by w84thesun**
# Description

Closes #2299.
Closes #537.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/shareddata/shareddata.go [hunk 1]
```diff
@@ -197,6 +199,66 @@ func (values *Values[idType]) IsCompatible(backend string) bool {
 	return slices.Contains(values.backends, backend)
 }
 
+// fields is a map of field name -> value.
+type fields map[string]any
+
+// TopLevelValues stores shared data documents as {"_id": key, "field1": value1, "field2": value2, ...} documents.
+//
+//nolint:vet // for readability
+type TopLevelValues[id comparable] struct {
```
Comment (w84thesun) [inline integration/shareddata/shareddata.go:208]: I didn't come up with any good name for this provider, so suggestions are welcome!

File: internal/handlers/common/projection.go [hunk 2]
```diff
@@ -15,160 +15,206 @@
...
-					err = commonerrors.NewCommandErrorMsgWithArgument(commonerrors.ErrProjectionInEx,
-						fmt.Sprintf("Cannot do inclusion on field %s in exclusion projection", k),
-						"projection",
-					)
-					return
-				}
-				inclusion = true
+			comparison := types.Compare(value, int32(0))
+			if comparison != types.Equal {
+				result = true
```
Comment (chilagrow) [inline internal/handlers/common/projection.go:69]: So result is true for inclusion. But currently any none zero value (i.e. any negative/positive number) would evaluate projection is inclusion. But I see from tests that only `1` is tested for projection inclusion. Maybe worthwhile adding a test for `-1`?

File: integration/query_projection_compat_test.go [hunk 3]
```diff
@@ -24,17 +24,68 @@ func TestQueryProjectionCompat(t *testing.T) {
...
+			projection: bson.D{{"_id", false}},
+		},
+		"IncludeFieldExcludeID": {
+			filter:     bson.D{},
+			projection: bson.D{{"_id", false}, {"array", true}},
+		},
+		"ExcludeFieldIncludeID": {
+			filter:     bson.D{},
+			projection: bson.D{{"_id", true}, {"array", false}},
+		},
```
Comment (chilagrow) [inline integration/query_projection_compat_test.go:58]: Could you add test for 
`projection: bson.D{{"_id", true}, {"v", true}},` I'm curious because of https://github.com/FerretDB/FerretDB/pull/2386/files#diff-7bba61640a80f2f9020b4e4049d8a46e197e35d987264d20e1ed1cfe41121f9dR108.
Also could you add `projection: bson.D{{"_id", false}, {"v", false}},`? I don't know what happens if everything is excluded.

File: integration/query_projection_compat_test.go [hunk 4]
```diff
@@ -24,17 +24,68 @@ func TestQueryProjectionCompat(t *testing.T) {
...
+			filter:     bson.D{},
+			projection: bson.D{{"_id", true}},
+		},
+		"ExcludeID": {
+			filter:     bson.D{},
+			projection: bson.D{{"_id", false}},
+		},
+		"IncludeFieldExcludeID": {
+			filter:     bson.D{},
+			projection: bson.D{{"_id", false}, {"array", true}},
```
Comment (chilagrow) [inline integration/query_projection_compat_test.go:53]: `array` top level field does not exist, is  this testing the case where field does not exist?

**Review by chilagrow — COMMENTED** [review]
Great work! I have couple of comments

File: internal/handlers/common/projection.go (hunk 2 above)
Comment (w84thesun) [reply internal/handlers/common/projection.go:69]: Any non-zero value is treated as `true`, including `-1`.

File: integration/query_projection_compat_test.go (hunk 4 above)
Comment (w84thesun) [reply integration/query_projection_compat_test.go]: Changed it to 'v' field.

File: internal/handlers/common/projection.go [hunk 5]
```diff
@@ -15,160 +15,206 @@
...
+	if projection == nil {
+		return nil, false, errProjectionEmpty
 	}
 
-	for i := 0; i < len(docs); i++ {
-		err = projectDocument(inclusion, docs[i], projection)
+	var projectionVal *bool
+
+	iter := projection.Iterator()
+	defer iter.Close()
```
[the remark this answers is not in the document]
Comment (w84thesun) [reply internal/handlers/common/projection.go:43]: @AlekSi when we should use `Closer`? Would simply `defer iter.Close()` enough for `*types.Document`?

**Review by noisersup — APPROVED** [review]
:+1:

File: internal/handlers/common/projection.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (AlekSi) [reply internal/handlers/common/projection.go:43]: Sorry, I don't understand the question. `Closer` is just an interface with one method `Close`.

If the question is about `MultiCloser`, then this is more or less an equivalent of https://pkg.go.dev/io#MultiReader. One could arrange everything themselves to read all Readers one-by-one – or just use `MultiWriter`.

File: Taskfile.yml [hunk 6]
```diff
@@ -5,7 +5,7 @@ env:
   GORACE: halt_on_error=1,history_size=2
 
 vars:
-  INTEGRATIONTIME: 30m
+  INTEGRATIONTIME: 35m
```
Comment (rumyantseva) [inline Taskfile.yml:8]: Oh! 😅

File: integration/query_compat_test.go [hunk 7]
```diff
@@ -41,6 +41,7 @@ type queryCompatTestCase struct {
 	resultType     compatTestCaseResultType // defaults to nonEmptyResult
 	resultPushdown bool                     // defaults to false
 
+	skipIDCheck   bool   // skip check collected IDs, check results only
```
Comment (rumyantseva) [inline integration/query_compat_test.go:44]: I think I need an explanation of when collected IDs should be skipped.

File: integration/shareddata/scalars.go [hunk 8]
```diff
@@ -434,6 +434,31 @@ var ObjectIDKeys = &Values[primitive.ObjectID]{
 	},
 }
 
+// TopLevelFieldsIntegers contains documents with several top level fields with integer values.
+var TopLevelFieldsIntegers = &TopLevelValues[string]{
```
Comment (rumyantseva) [inline integration/shareddata/scalars.go:438]: Why did we add it to `scalars.go`? It looks like a composite. I guess, the name should also start with `Documents` like for other composites of similar nature.

Or, if you want to highlight  that it's a totally new thing (no `v` field), then maybe it should be in a new file (not scalars and not composites).

The test data itself looks super helpful! So far we've only tested `v` :D

File: integration/shareddata/shareddata.go (hunk 1 above)
Comment (rumyantseva) [reply integration/shareddata/shareddata.go:208]: I would just call it something like "CustomeFields". Non-custom is for `v`, and custom is for any other case. But "CustomFields" doesn't look super perfect name, so I'm ok with your name too!

**Review by rumyantseva — COMMENTED** [review]
Not a full review yet, asked a few questions

File: integration/query_compat_test.go (hunk 7 above)
Comment (w84thesun) [reply integration/query_compat_test.go]: I rewrote the comment to this flag to add an explanation.

File: internal/handlers/common/projection.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/handlers/common/projection.go:43]: This one actually just have one iterator so no need of any change, misread, my bad.

File: internal/handlers/common/projection.go (hunk 2 above)
Comment (chilagrow) [reply internal/handlers/common/projection.go:66]: Wow weird,  thanks!

File: integration/shareddata/composites.go [hunk 9]
```diff
@@ -382,3 +382,28 @@ var ArrayDocuments = &Values[string]{
...
+			}`,
+		},
+	},
+	data: map[string]fields{
+		"int32-two": {
+			"foo": int32(1),
+			"bar": int32(2),
+		},
+	},
+}
```
Comment (chilagrow) [inline integration/shareddata/composites.go:409]: I'm seeing quite a lot of test failures due to the order of fields `foo` and `bar`. I think it's expected from this because fields are design to be random order by using map. There can be multiple way of handling this, either ensure fields are the specific order, tests sorts response before compare or something else.

```
2023-04-17T18:40:02.3596105Z             --- FAIL: TestUpdateFieldCompatSetOnInsert/DocArrFieldNotExist/TestUpdateFieldCompatSetOnInsert-DocArrFieldNotExist_TopLevelFieldsIntegers/int32-two (0.04s)
2023-04-17T18:40:02.3596429Z                 update_field_compat_test.go:968: 
2023-04-17T18:40:02.3597076Z                            Error Trace:    /home/runner/work/FerretDB/FerretDB/internal/util/testutil/equal.go:42
2023-04-17T18:40:02.3597968Z                                                                    /home/runner/work/FerretDB/FerretDB/integration/helpers.go:143
2023-04-17T18:40:02.3598942Z                                                                    /home/runner/work/FerretDB/FerretDB/integration/update_compat_test.go:143
2023-04-17T18:40:02.3599260Z                            Error:          Not equal: 
2023-04-17T18:40:02.3599574Z                                            expected: {
2023-04-17T18:40:02.3599870Z                                              "$k": [
2023-04-17T18:40:02.3600186Z                                                "_id",
2023-04-17T18:40:02.3600503Z                                                "foo",
2023-04-17T18:40:02.3600806Z                                                "bar"
2023-04-17T18:40:02.3601064Z                                              ],
2023-04-17T18:40:02.3601523Z                                              "_id": "int32-two",
2023-04-17T18:40:02.3601844Z                                              "foo": 1,
2023-04-17T18:40:02.3602201Z                                              "bar": 2
2023-04-17T18:40:02.3602418Z                                            }
2023-04-17T18:40:02.3602725Z                                            actual  : {
2023-04-17T18:40:02.3603023Z                                              "$k": [
2023-04-17T18:40:02.3603338Z                                                "_id",
2023-04-17T18:40:02.3603647Z                                                "bar",
2023-04-17T18:40:02.3603947Z                                                "foo"
2023-04-17T18:40:02.3604201Z                                              ],
2023-04-17T18:40:02.3604658Z                                              "_id": "int32-two",
2023-04-17T18:40:02.3605022Z                                              "bar": 2,
2023-04-17T18:40:02.3605392Z                                              "foo": 1
2023-04-17T18:40:02.3605625Z                                            }
2023-04-17T18:40:02.3605996Z                                            --- expected
2023-04-17T18:40:02.3606289Z                                            +++ actual
2023-04-17T18:40:02.3606667Z                                            @@ -3,8 +3,8 @@
2023-04-17T18:40:02.3606991Z                                                 "_id",
2023-04-17T18:40:02.3607344Z                                            -    "foo",
2023-04-17T18:40:02.3607687Z                                            -    "bar"
2023-04-17T18:40:02.3607993Z                                            +    "bar",
2023-04-17T18:40:02.3608294Z                                            +    "foo"
2023-04-17T18:40:02.3608557Z                                               ],
2023-04-17T18:40:02.3609022Z                                               "_id": "int32-two",
2023-04-17T18:40:02.3609396Z                                            -  "foo": 1,
2023-04-17T18:40:02.3609751Z                                            -  "bar": 2
2023-04-17T18:40:02.3610063Z                                            +  "bar": 2,
2023-04-17T18:40:02.3610374Z                                            +  "foo": 1
2023-04-17T18:40:02.3610614Z                                             }
```

**Review by chilagrow — COMMENTED** [review]
Looks good, let's fix failing tests :hugs:

File: internal/handlers/common/projection.go (hunk 2 above)
Comment (chilagrow) [reply internal/handlers/common/projection.go:66]: Would be great to document this in the code though. Did not find this in the documentation I've looked :see_no_evil:

File: integration/shareddata/composites.go (hunk 9 above)
Comment (w84thesun) [reply integration/shareddata/composites.go]: Fixed it.

File: Taskfile.yml (hunk 6 above)
Comment (w84thesun) [reply Taskfile.yml]: Restored previous value.

File: internal/handlers/common/projection.go (hunk 2 above)
Comment (w84thesun) [reply internal/handlers/common/projection.go:68]: I added a comment to the place where we comparing values.

**Review by noisersup — DISMISSED** [review]

**Comment by w84thesun** [comment]
@noisersup sorry, forgot to add an interface check.

**Review by noisersup — DISMISSED** [review]

File: integration/shareddata/shareddata.go [hunk 10]
```diff
@@ -242,8 +242,85 @@ func (b *BenchmarkValues) Docs() iterator.Interface[struct{}, bson.D] {
 	return b.iter
 }
 
+// field represents a field in a document.
+type field struct {
+	Value any
+	Key   string
+}
+
+// Fields is a map of field name -> value.
```
Comment (chilagrow) [inline integration/shareddata/shareddata.go:251]:
```suggestion
// Fields is a slice of ordered field name value pair. To avoid fields being inserted in different order between compat and target, use a slice instead of a map.
```

**Review by chilagrow — APPROVED** [review]

**Review by chilagrow — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
LGTM
