### PR TITLE
Fix `upsert` with `$setOnInsert` operator

### LINKED ISSUE #3224: `upsert` with `$setOnInsert` is not working
### FerretDB version

1.8 

### Backend

PostgreSQL

### Environment

- OS:
- Deployment: ghcr.io/ferretdb/all-in-one
- Deployment details:

### What did you do?

````csharp
using System;
using System.Text.Json;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Driver;

class Program
{
    static async Task Main(string[] args)
    {
        string connectionString = "mongodb://localhost:27020"; // Update with your MongoDB connection string
        string databaseName = "TestDataBase"; // Update with your database name
        var client = new MongoClient(connectionString);
        var database = client.GetDatabase(databaseName);
        var collection = database.GetCollection<BsonDocument>("SimpleItems");

        // Create random item
        var item = new BsonDocument
        {
            { "_id", ObjectId.GenerateNewId() }, // New ObjectId for upsert
            { "Text", "Initial Text" },
            { "Number", 42 }
        };

        // Insert into DB
        await collection.InsertOneAsync(item);

        // Update document for Text field upsert
        var updateText = new BsonDocument
        {
            { "$set", new BsonDocument { { "Text", "Test" } } }, 
            { "$setOnInsert", new BsonDocument
                {
                    { "_id", ObjectId.GenerateNewId() }, // New ObjectId for upsert
                    { "Number", 42 }
                } 
            }
        };

        // Perform the Text field upsert operation
        var textFilter = Builders<BsonDocument>.Filter.Eq("_id", item["_id"]);
        var textUpdateOptions = new UpdateOptions { IsUpsert = true };
        await collection.UpdateOneAsync(textFilter, updateText, textUpdateOptions);

        // Update document for Number field upsert
        var updateNumber = new BsonDocument
        {
            { "$set", new BsonDocument { { "Number", -1 } } }, 
            { "$setOnInsert", new BsonDocument
                {
                    { "_id", ObjectId.GenerateNewId() }, // New ObjectId for upsert
                    { "Text", "Initial Text" }
                }
            } 
        };

        // Perform the Number field upsert operation
        var numberFilter = Builders<BsonDocument>.Filter.Eq("_id", item["_id"]);
        var numberUpdateOptions = new UpdateOptions { IsUpsert = true };
        await collection.UpdateOneAsync(numberFilter, updateNumber, numberUpdateOptions);

        // Check if Item was updated properly
        var itemFromDb = await collection.Find(textFilter).FirstOrDefaultAsync();

        // Check if item loaded from DB contains the same information as item inserted to DB
        bool textMatch = "Test" == itemFromDb["Text"];
        bool numberMatch = -1 == itemFromDb["Number"];
        Console.WriteLine("Item Text was " + (textMatch ? "" : "not ") + "updated or 'Text'-Field was overwritten");
        Console.WriteLine("Item Number was " + (numberMatch ? "" : "not ") + "updated or 'Number'-Field was overwritten");
    }
}
````

### What did you expect to see?

The document Text should be updated to `Test` and the Number to `-1`

### What did you see instead?

The initial values.

Log:
`````
2023-08-18 19:20:13 2023-08-18 17:20:13.838 UTC [10] LOG:  database system is ready to accept connections
2023-08-18 19:20:20 2023-08-18T17:20:20.742Z    INFO    listener        clientconn/listener.go:319      Connection started      {"conn": "172.17.0.1:44846 -> 172.17.0.2:27017"}
2023-08-18 19:20:20 2023-08-18T17:20:20.742Z    INFO    listener        clientconn/listener.go:319      Connection started      {"conn": "172.17.0.1:44844 -> 172.17.0.2:27017"}
2023-08-18 19:20:20 2023-08-18T17:20:20.765Z    DEBUG   // 172.17.0.1:44846 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   305, id:    1, response_to:    0, opcode: OP_QUERY
2023-08-18 19:20:20 2023-08-18T17:20:20.765Z    DEBUG   // 172.17.0.1:44844 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   305, id:    2, response_to:    0, opcode: OP_QUERY
2023-08-18 19:20:20 2023-08-18T17:20:20.765Z    DEBUG   // 172.17.0.1:44844 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Flags": 4,
2023-08-18 19:20:20   "FullCollectionName": "admin.$cmd",
2023-08-18 19:20:20   "NumberToReturn": -1,
2023-08-18 19:20:20   "NumberToSkip": 0,
2023-08-18 19:20:20   "Query": {
2023-08-18 19:20:20     "$k": [
2023-08-18 19:20:20       "isMaster",
2023-08-18 19:20:20       "helloOk",
2023-08-18 19:20:20       "client",
2023-08-18 19:20:20       "compression"
2023-08-18 19:20:20     ],
2023-08-18 19:20:20     "isMaster": 1,
2023-08-18 19:20:20     "helloOk": true,
2023-08-18 19:20:20     "client": {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "driver",
2023-08-18 19:20:20         "os",
2023-08-18 19:20:20         "platform"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "driver": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "name": "mongo-csharp-driver",
2023-08-18 19:20:20         "version": "2.21.0.0"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "os": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "type",
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "architecture",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "type": "Windows",
2023-08-18 19:20:20         "name": "Microsoft Windows 10.0.22621",
2023-08-18 19:20:20         "architecture": "x86_64",
2023-08-18 19:20:20         "version": "10.0.22621"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "platform": ".NET 6.0.20"
2023-08-18 19:20:20     },
2023-08-18 19:20:20     "compression": []
2023-08-18 19:20:20   }
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.765Z    DEBUG   // 172.17.0.1:44846 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Flags": 4,
2023-08-18 19:20:20   "FullCollectionName": "admin.$cmd",
2023-08-18 19:20:20   "NumberToReturn": -1,
2023-08-18 19:20:20   "NumberToSkip": 0,
2023-08-18 19:20:20   "Query": {
2023-08-18 19:20:20     "$k": [
2023-08-18 19:20:20       "isMaster",
2023-08-18 19:20:20       "helloOk",
2023-08-18 19:20:20       "client",
2023-08-18 19:20:20       "compression"
2023-08-18 19:20:20     ],
2023-08-18 19:20:20     "isMaster": 1,
2023-08-18 19:20:20     "helloOk": true,
2023-08-18 19:20:20     "client": {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "driver",
2023-08-18 19:20:20         "os",
2023-08-18 19:20:20         "platform"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "driver": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "name": "mongo-csharp-driver",
2023-08-18 19:20:20         "version": "2.21.0.0"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "os": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "type",
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "architecture",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "type": "Windows",
2023-08-18 19:20:20         "name": "Microsoft Windows 10.0.22621",
2023-08-18 19:20:20         "architecture": "x86_64",
2023-08-18 19:20:20         "version": "10.0.22621"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "platform": ".NET 6.0.20"
2023-08-18 19:20:20     },
2023-08-18 19:20:20     "compression": []
2023-08-18 19:20:20   }
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.766Z    DEBUG   // 172.17.0.1:44846 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:   223, id:    1, response_to:    1, opcode: OP_REPLY
2023-08-18 19:20:20 2023-08-18T17:20:20.766Z    DEBUG   // 172.17.0.1:44844 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:   223, id:    1, response_to:    2, opcode: OP_REPLY
2023-08-18 19:20:20 2023-08-18T17:20:20.766Z    DEBUG   // 172.17.0.1:44844 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "CursorID": 0,
2023-08-18 19:20:20   "Documents": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "ismaster",
2023-08-18 19:20:20         "maxBsonObjectSize",
2023-08-18 19:20:20         "maxMessageSizeBytes",
2023-08-18 19:20:20         "maxWriteBatchSize",
2023-08-18 19:20:20         "localTime",
2023-08-18 19:20:20         "connectionId",
2023-08-18 19:20:20         "minWireVersion",
2023-08-18 19:20:20         "maxWireVersion",
2023-08-18 19:20:20         "readOnly",
2023-08-18 19:20:20         "ok"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "ismaster": true,
2023-08-18 19:20:20       "maxBsonObjectSize": 16777216,
2023-08-18 19:20:20       "maxMessageSizeBytes": 48000000,
2023-08-18 19:20:20       "maxWriteBatchSize": 100000,
2023-08-18 19:20:20       "localTime": {
2023-08-18 19:20:20         "$d": 1692379220765
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "connectionId": 42,
2023-08-18 19:20:20       "minWireVersion": 0,
2023-08-18 19:20:20       "maxWireVersion": 17,
2023-08-18 19:20:20       "readOnly": false,
2023-08-18 19:20:20       "ok": {
2023-08-18 19:20:20         "$f": 1
2023-08-18 19:20:20       }
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ],
2023-08-18 19:20:20   "NumberReturned": 1,
2023-08-18 19:20:20   "ResponseFlags": 0,
2023-08-18 19:20:20   "StartingFrom": 0
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.766Z    DEBUG   // 172.17.0.1:44846 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "CursorID": 0,
2023-08-18 19:20:20   "Documents": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "ismaster",
2023-08-18 19:20:20         "maxBsonObjectSize",
2023-08-18 19:20:20         "maxMessageSizeBytes",
2023-08-18 19:20:20         "maxWriteBatchSize",
2023-08-18 19:20:20         "localTime",
2023-08-18 19:20:20         "connectionId",
2023-08-18 19:20:20         "minWireVersion",
2023-08-18 19:20:20         "maxWireVersion",
2023-08-18 19:20:20         "readOnly",
2023-08-18 19:20:20         "ok"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "ismaster": true,
2023-08-18 19:20:20       "maxBsonObjectSize": 16777216,
2023-08-18 19:20:20       "maxMessageSizeBytes": 48000000,
2023-08-18 19:20:20       "maxWriteBatchSize": 100000,
2023-08-18 19:20:20       "localTime": {
2023-08-18 19:20:20         "$d": 1692379220765
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "connectionId": 42,
2023-08-18 19:20:20       "minWireVersion": 0,
2023-08-18 19:20:20       "maxWireVersion": 17,
2023-08-18 19:20:20       "readOnly": false,
2023-08-18 19:20:20       "ok": {
2023-08-18 19:20:20         "$f": 1
2023-08-18 19:20:20       }
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ],
2023-08-18 19:20:20   "NumberReturned": 1,
2023-08-18 19:20:20   "ResponseFlags": 0,
2023-08-18 19:20:20   "StartingFrom": 0
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.858Z    INFO    listener        clientconn/listener.go:319      Connection started      {"conn": "172.17.0.1:44848 -> 172.17.0.2:27017"}
2023-08-18 19:20:20 2023-08-18T17:20:20.868Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   305, id:    3, response_to:    0, opcode: OP_QUERY
2023-08-18 19:20:20 2023-08-18T17:20:20.869Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Flags": 4,
2023-08-18 19:20:20   "FullCollectionName": "admin.$cmd",
2023-08-18 19:20:20   "NumberToReturn": -1,
2023-08-18 19:20:20   "NumberToSkip": 0,
2023-08-18 19:20:20   "Query": {
2023-08-18 19:20:20     "$k": [
2023-08-18 19:20:20       "isMaster",
2023-08-18 19:20:20       "helloOk",
2023-08-18 19:20:20       "client",
2023-08-18 19:20:20       "compression"
2023-08-18 19:20:20     ],
2023-08-18 19:20:20     "isMaster": 1,
2023-08-18 19:20:20     "helloOk": true,
2023-08-18 19:20:20     "client": {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "driver",
2023-08-18 19:20:20         "os",
2023-08-18 19:20:20         "platform"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "driver": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "name": "mongo-csharp-driver",
2023-08-18 19:20:20         "version": "2.21.0.0"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "os": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "type",
2023-08-18 19:20:20           "name",
2023-08-18 19:20:20           "architecture",
2023-08-18 19:20:20           "version"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "type": "Windows",
2023-08-18 19:20:20         "name": "Microsoft Windows 10.0.22621",
2023-08-18 19:20:20         "architecture": "x86_64",
2023-08-18 19:20:20         "version": "10.0.22621"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "platform": ".NET 6.0.20"
2023-08-18 19:20:20     },
2023-08-18 19:20:20     "compression": []
2023-08-18 19:20:20   }
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.869Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:   223, id:    1, response_to:    3, opcode: OP_REPLY
2023-08-18 19:20:20 2023-08-18T17:20:20.869Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "CursorID": 0,
2023-08-18 19:20:20   "Documents": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "$k": [
2023-08-18 19:20:20         "ismaster",
2023-08-18 19:20:20         "maxBsonObjectSize",
2023-08-18 19:20:20         "maxMessageSizeBytes",
2023-08-18 19:20:20         "maxWriteBatchSize",
2023-08-18 19:20:20         "localTime",
2023-08-18 19:20:20         "connectionId",
2023-08-18 19:20:20         "minWireVersion",
2023-08-18 19:20:20         "maxWireVersion",
2023-08-18 19:20:20         "readOnly",
2023-08-18 19:20:20         "ok"
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "ismaster": true,
2023-08-18 19:20:20       "maxBsonObjectSize": 16777216,
2023-08-18 19:20:20       "maxMessageSizeBytes": 48000000,
2023-08-18 19:20:20       "maxWriteBatchSize": 100000,
2023-08-18 19:20:20       "localTime": {
2023-08-18 19:20:20         "$d": 1692379220869
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "connectionId": 42,
2023-08-18 19:20:20       "minWireVersion": 0,
2023-08-18 19:20:20       "maxWireVersion": 17,
2023-08-18 19:20:20       "readOnly": false,
2023-08-18 19:20:20       "ok": {
2023-08-18 19:20:20         "$f": 1
2023-08-18 19:20:20       }
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ],
2023-08-18 19:20:20   "NumberReturned": 1,
2023-08-18 19:20:20   "ResponseFlags": 0,
2023-08-18 19:20:20   "StartingFrom": 0
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.919Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   154, id:    4, response_to:    0, opcode: OP_MSG
2023-08-18 19:20:20 2023-08-18T17:20:20.919Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Checksum": 0,
2023-08-18 19:20:20   "FlagBits": 0,
2023-08-18 19:20:20   "Sections": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Document": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "insert",
2023-08-18 19:20:20           "ordered",
2023-08-18 19:20:20           "$db"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "insert": "SimpleItems",
2023-08-18 19:20:20         "ordered": true,
2023-08-18 19:20:20         "$db": "TestDataBase"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "Kind": 0
2023-08-18 19:20:20     },
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Documents": [
2023-08-18 19:20:20         {
2023-08-18 19:20:20           "$k": [
2023-08-18 19:20:20             "_id",
2023-08-18 19:20:20             "Text",
2023-08-18 19:20:20             "Number"
2023-08-18 19:20:20           ],
2023-08-18 19:20:20           "_id": {
2023-08-18 19:20:20             "$o": "64dfa854e13a676f1b4e19e9"
2023-08-18 19:20:20           },
2023-08-18 19:20:20           "Text": "Initial Text",
2023-08-18 19:20:20           "Number": 42
2023-08-18 19:20:20         }
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "Identifier": "documents",
2023-08-18 19:20:20       "Kind": 1
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ]
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.925Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"args": [], "time": "440.584µs", "commandTag": "SHOW", "pid": 47, "sql": "SHOW server_version"}
2023-08-18 19:20:20 2023-08-18T17:20:20.926Z    DEBUG   pgdb    pgdb/pool.go:211        PostgreSQL setting      {"name": "client_encoding", "setting": "UTF8"}
2023-08-18 19:20:20 2023-08-18T17:20:20.926Z    DEBUG   pgdb    pgdb/pool.go:211        PostgreSQL setting      {"name": "lc_collate", "setting": "en_US.utf8"}
2023-08-18 19:20:20 2023-08-18T17:20:20.926Z    DEBUG   pgdb    pgdb/pool.go:211        PostgreSQL setting      {"name": "lc_ctype", "setting": "en_US.utf8"}
2023-08-18 19:20:20 2023-08-18T17:20:20.927Z    DEBUG   pgdb    pgdb/pool.go:211        PostgreSQL setting      {"name": "server_encoding", "setting": "UTF8"}
2023-08-18 19:20:20 2023-08-18T17:20:20.927Z    DEBUG   pgdb    pgdb/pool.go:211        PostgreSQL setting      {"setting": "on", "name": "standard_conforming_strings"}
2023-08-18 19:20:20 2023-08-18T17:20:20.927Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "SHOW ALL", "args": [], "time": "1.58421ms", "commandTag": "SHOW"}
2023-08-18 19:20:20 2023-08-18T17:20:20.927Z    INFO    pg/pg.go:143    DBPool: connection succeed      {"username": ""}
2023-08-18 19:20:20 2023-08-18T17:20:20.928Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "begin", "args": [], "time": "285.617µs", "commandTag": "BEGIN", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.933Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "4.809968ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.935Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "1.596991ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.937Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "2.006518ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.938Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "847.934µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.939Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "INSERT INTO \"TestDataBase\".\"_imple_tems_98200051\" (_jsonb) VALUES ($1)", "args": ["7b222473223a7b2270223a7b225f6964223a7b2274223a226f626a6563744964227d2c2254657874223a7b2274223a22737472696e67227d2c224e756d626572 (truncated 112 bytes)"], "time": "773.731µs", "commandTag": "INSERT 0 1"}
2023-08-18 19:20:20 2023-08-18T17:20:20.941Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "commit", "args": [], "time": "2.265165ms", "commandTag": "COMMIT", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.941Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:    45, id:    2, response_to:    4, opcode: OP_MSG
2023-08-18 19:20:20 2023-08-18T17:20:20.942Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Checksum": 0,
2023-08-18 19:20:20   "FlagBits": 0,
2023-08-18 19:20:20   "Sections": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Document": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "n",
2023-08-18 19:20:20           "ok"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "n": 1,
2023-08-18 19:20:20         "ok": {
2023-08-18 19:20:20           "$f": 1
2023-08-18 19:20:20         }
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "Kind": 0
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ]
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.979Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   216, id:    5, response_to:    0, opcode: OP_MSG
2023-08-18 19:20:20 2023-08-18T17:20:20.979Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Checksum": 0,
2023-08-18 19:20:20   "FlagBits": 0,
2023-08-18 19:20:20   "Sections": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Document": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "update",
2023-08-18 19:20:20           "ordered",
2023-08-18 19:20:20           "$db"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "update": "SimpleItems",
2023-08-18 19:20:20         "ordered": true,
2023-08-18 19:20:20         "$db": "TestDataBase"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "Kind": 0
2023-08-18 19:20:20     },
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Documents": [
2023-08-18 19:20:20         {
2023-08-18 19:20:20           "$k": [
2023-08-18 19:20:20             "q",
2023-08-18 19:20:20             "u",
2023-08-18 19:20:20             "upsert"
2023-08-18 19:20:20           ],
2023-08-18 19:20:20           "q": {
2023-08-18 19:20:20             "$k": [
2023-08-18 19:20:20               "_id"
2023-08-18 19:20:20             ],
2023-08-18 19:20:20             "_id": {
2023-08-18 19:20:20               "$o": "64dfa854e13a676f1b4e19e9"
2023-08-18 19:20:20             }
2023-08-18 19:20:20           },
2023-08-18 19:20:20           "u": {
2023-08-18 19:20:20             "$k": [
2023-08-18 19:20:20               "$set",
2023-08-18 19:20:20               "$setOnInsert"
2023-08-18 19:20:20             ],
2023-08-18 19:20:20             "$set": {
2023-08-18 19:20:20               "$k": [
2023-08-18 19:20:20                 "Text"
2023-08-18 19:20:20               ],
2023-08-18 19:20:20               "Text": "Test"
2023-08-18 19:20:20             },
2023-08-18 19:20:20             "$setOnInsert": {
2023-08-18 19:20:20               "$k": [
2023-08-18 19:20:20                 "_id",
2023-08-18 19:20:20                 "Number"
2023-08-18 19:20:20               ],
2023-08-18 19:20:20               "_id": {
2023-08-18 19:20:20                 "$o": "64dfa854e13a676f1b4e19ea"
2023-08-18 19:20:20               },
2023-08-18 19:20:20               "Number": 42
2023-08-18 19:20:20             }
2023-08-18 19:20:20           },
2023-08-18 19:20:20           "upsert": true
2023-08-18 19:20:20         }
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "Identifier": "updates",
2023-08-18 19:20:20       "Kind": 1
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ]
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.979Z    DEBUG   pg/pg.go:119    DBPool: found existing pool     {"username": ""}
2023-08-18 19:20:20 2023-08-18T17:20:20.979Z    DEBUG   commonparams/extract_params.go:110      ignoring field  {"command": "update", "field": "ordered", "value": true}
2023-08-18 19:20:20 2023-08-18T17:20:20.980Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "begin", "args": [], "time": "248.839µs", "commandTag": "BEGIN", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.982Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "1.282701ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.983Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"time": "912.358µs", "commandTag": "SELECT 1", "pid": 47, "sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""]}
2023-08-18 19:20:20 2023-08-18T17:20:20.983Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "commit", "args": [], "time": "153.01µs", "commandTag": "COMMIT", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.983Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"commandTag": "BEGIN", "pid": 47, "sql": "begin", "args": [], "time": "120.439µs"}
2023-08-18 19:20:20 2023-08-18T17:20:20.984Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "1.164578ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.985Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "883.91µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.986Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"commandTag": "SELECT 1", "pid": 47, "sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_imple_tems_98200051\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"64dfa854e13a676f1b4e19e9\""], "time": "842.166µs"}
2023-08-18 19:20:20 2023-08-18T17:20:20.989Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "1.623472ms", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.990Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"time": "894.194µs", "commandTag": "SELECT 1", "pid": 47, "sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""]}
2023-08-18 19:20:20 2023-08-18T17:20:20.990Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"args": ["7b222473223a7b2270223a7b225f6964223a7b2274223a226f626a6563744964227d2c2254657874223a7b2274223a22737472696e67227d2c224e756d626572 (truncated 104 bytes)","2236346466613835346531336136373666316234653139656122"], "time": "605.556µs", "commandTag": "UPDATE 0", "pid": 47, "sql": "UPDATE \"TestDataBase\".\"_imple_tems_98200051\" SET _jsonb = $1 WHERE _jsonb->'_id' = $2"}
2023-08-18 19:20:20 2023-08-18T17:20:20.991Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "commit", "args": [], "time": "191.155µs", "commandTag": "COMMIT"}
2023-08-18 19:20:20 2023-08-18T17:20:20.991Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:    60, id:    3, response_to:    5, opcode: OP_MSG
2023-08-18 19:20:20 2023-08-18T17:20:20.991Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Checksum": 0,
2023-08-18 19:20:20   "FlagBits": 0,
2023-08-18 19:20:20   "Sections": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Document": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "n",
2023-08-18 19:20:20           "nModified",
2023-08-18 19:20:20           "ok"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "n": 1,
2023-08-18 19:20:20         "nModified": 0,
2023-08-18 19:20:20         "ok": {
2023-08-18 19:20:20           "$f": 1
2023-08-18 19:20:20         }
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "Kind": 0
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ]
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.994Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   224, id:    6, response_to:    0, opcode: OP_MSG
2023-08-18 19:20:20 2023-08-18T17:20:20.994Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:20 {
2023-08-18 19:20:20   "Checksum": 0,
2023-08-18 19:20:20   "FlagBits": 0,
2023-08-18 19:20:20   "Sections": [
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Document": {
2023-08-18 19:20:20         "$k": [
2023-08-18 19:20:20           "update",
2023-08-18 19:20:20           "ordered",
2023-08-18 19:20:20           "$db"
2023-08-18 19:20:20         ],
2023-08-18 19:20:20         "update": "SimpleItems",
2023-08-18 19:20:20         "ordered": true,
2023-08-18 19:20:20         "$db": "TestDataBase"
2023-08-18 19:20:20       },
2023-08-18 19:20:20       "Kind": 0
2023-08-18 19:20:20     },
2023-08-18 19:20:20     {
2023-08-18 19:20:20       "Documents": [
2023-08-18 19:20:20         {
2023-08-18 19:20:20           "$k": [
2023-08-18 19:20:20             "q",
2023-08-18 19:20:20             "u",
2023-08-18 19:20:20             "upsert"
2023-08-18 19:20:20           ],
2023-08-18 19:20:20           "q": {
2023-08-18 19:20:20             "$k": [
2023-08-18 19:20:20               "_id"
2023-08-18 19:20:20             ],
2023-08-18 19:20:20             "_id": {
2023-08-18 19:20:20               "$o": "64dfa854e13a676f1b4e19e9"
2023-08-18 19:20:20             }
2023-08-18 19:20:20           },
2023-08-18 19:20:20           "u": {
2023-08-18 19:20:20             "$k": [
2023-08-18 19:20:20               "$set",
2023-08-18 19:20:20               "$setOnInsert"
2023-08-18 19:20:20             ],
2023-08-18 19:20:20             "$set": {
2023-08-18 19:20:20               "$k": [
2023-08-18 19:20:20                 "Number"
2023-08-18 19:20:20               ],
2023-08-18 19:20:20               "Number": -1
2023-08-18 19:20:20             },
2023-08-18 19:20:20             "$setOnInsert": {
2023-08-18 19:20:20               "$k": [
2023-08-18 19:20:20                 "_id",
2023-08-18 19:20:20                 "Text"
2023-08-18 19:20:20               ],
2023-08-18 19:20:20               "_id": {
2023-08-18 19:20:20                 "$o": "64dfa854e13a676f1b4e19eb"
2023-08-18 19:20:20               },
2023-08-18 19:20:20               "Text": "Initial Text"
2023-08-18 19:20:20             }
2023-08-18 19:20:20           },
2023-08-18 19:20:20           "upsert": true
2023-08-18 19:20:20         }
2023-08-18 19:20:20       ],
2023-08-18 19:20:20       "Identifier": "updates",
2023-08-18 19:20:20       "Kind": 1
2023-08-18 19:20:20     }
2023-08-18 19:20:20   ]
2023-08-18 19:20:20 }
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 
2023-08-18 19:20:20 2023-08-18T17:20:20.994Z    DEBUG   pg/pg.go:119    DBPool: found existing pool     {"username": ""}
2023-08-18 19:20:20 2023-08-18T17:20:20.994Z    DEBUG   commonparams/extract_params.go:110      ignoring field  {"command": "update", "field": "ordered", "value": true}
2023-08-18 19:20:20 2023-08-18T17:20:20.995Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "begin", "args": [], "time": "195.978µs", "commandTag": "BEGIN", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.996Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "1.313784ms", "commandTag": "SELECT 1"}
2023-08-18 19:20:20 2023-08-18T17:20:20.997Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "813.194µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.997Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "commit", "args": [], "time": "145.262µs", "commandTag": "COMMIT", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.998Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "begin", "args": [], "time": "128.642µs", "commandTag": "BEGIN", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.998Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "301.758µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:20 2023-08-18T17:20:20.999Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "831.222µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.000Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"args": ["_id","\"64dfa854e13a676f1b4e19e9\""], "time": "578.714µs", "commandTag": "SELECT 1", "pid": 47, "sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_imple_tems_98200051\" WHERE _jsonb->$1 @> $2"}
2023-08-18 19:20:21 2023-08-18T17:20:21.001Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "289.729µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.002Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "766.589µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.002Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"args": ["7b222473223a7b2270223a7b225f6964223a7b2274223a226f626a6563744964227d2c2254657874223a7b2274223a22737472696e67227d2c224e756d626572 (truncated 112 bytes)","2236346466613835346531336136373666316234653139656222"], "time": "316.877µs", "commandTag": "UPDATE 0", "pid": 47, "sql": "UPDATE \"TestDataBase\".\"_imple_tems_98200051\" SET _jsonb = $1 WHERE _jsonb->'_id' = $2"}
2023-08-18 19:20:21 2023-08-18T17:20:21.002Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "commit", "args": [], "time": "122.59µs", "commandTag": "COMMIT", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.002Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:    60, id:    4, response_to:    6, opcode: OP_MSG
2023-08-18 19:20:21 2023-08-18T17:20:21.003Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:21 {
2023-08-18 19:20:21   "Checksum": 0,
2023-08-18 19:20:21   "FlagBits": 0,
2023-08-18 19:20:21   "Sections": [
2023-08-18 19:20:21     {
2023-08-18 19:20:21       "Document": {
2023-08-18 19:20:21         "$k": [
2023-08-18 19:20:21           "n",
2023-08-18 19:20:21           "nModified",
2023-08-18 19:20:21           "ok"
2023-08-18 19:20:21         ],
2023-08-18 19:20:21         "n": 1,
2023-08-18 19:20:21         "nModified": 0,
2023-08-18 19:20:21         "ok": {
2023-08-18 19:20:21           "$f": 1
2023-08-18 19:20:21         }
2023-08-18 19:20:21       },
2023-08-18 19:20:21       "Kind": 0
2023-08-18 19:20:21     }
2023-08-18 19:20:21   ]
2023-08-18 19:20:21 }
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 2023-08-18T17:20:21.028Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:287  Request header: length:   111, id:    7, response_to:    0, opcode: OP_MSG
2023-08-18 19:20:21 2023-08-18T17:20:21.029Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:288  Request message:
2023-08-18 19:20:21 {
2023-08-18 19:20:21   "Checksum": 0,
2023-08-18 19:20:21   "FlagBits": 0,
2023-08-18 19:20:21   "Sections": [
2023-08-18 19:20:21     {
2023-08-18 19:20:21       "Document": {
2023-08-18 19:20:21         "$k": [
2023-08-18 19:20:21           "find",
2023-08-18 19:20:21           "filter",
2023-08-18 19:20:21           "limit",
2023-08-18 19:20:21           "$db"
2023-08-18 19:20:21         ],
2023-08-18 19:20:21         "find": "SimpleItems",
2023-08-18 19:20:21         "filter": {
2023-08-18 19:20:21           "$k": [
2023-08-18 19:20:21             "_id"
2023-08-18 19:20:21           ],
2023-08-18 19:20:21           "_id": {
2023-08-18 19:20:21             "$o": "64dfa854e13a676f1b4e19e9"
2023-08-18 19:20:21           }
2023-08-18 19:20:21         },
2023-08-18 19:20:21         "limit": 1,
2023-08-18 19:20:21         "$db": "TestDataBase"
2023-08-18 19:20:21       },
2023-08-18 19:20:21       "Kind": 0
2023-08-18 19:20:21     }
2023-08-18 19:20:21   ]
2023-08-18 19:20:21 }
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 2023-08-18T17:20:21.029Z    DEBUG   pg/pg.go:119    DBPool: found existing pool     {"username": ""}
2023-08-18 19:20:21 2023-08-18T17:20:21.030Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "begin", "args": [], "time": "281.622µs", "commandTag": "BEGIN", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.030Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "SELECT EXISTS ( SELECT 1 FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2 )", "args": ["TestDataBase","_ferretdb_database_metadata"], "time": "348.614µs", "commandTag": "SELECT 1"}
2023-08-18 19:20:21 2023-08-18T17:20:21.031Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_ferretdb_database_metadata\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"SimpleItems\""], "time": "776.524µs", "commandTag": "SELECT 1", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.031Z    DEBUG   cursors cursor/registry.go:133  Creating        {"id": 1, "db": "TestDataBase", "collection": "SimpleItems"}
2023-08-18 19:20:21 2023-08-18T17:20:21.032Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"pid": 47, "sql": "SELECT _jsonb  FROM \"TestDataBase\".\"_imple_tems_98200051\" WHERE _jsonb->$1 @> $2", "args": ["_id","\"64dfa854e13a676f1b4e19e9\""], "time": "952.183µs", "commandTag": "SELECT 1"}
2023-08-18 19:20:21 2023-08-18T17:20:21.033Z    INFO    pgdb    tracelog/tracelog.go:335        Query   {"sql": "rollback", "args": [], "time": "117.154µs", "commandTag": "ROLLBACK", "pid": 47}
2023-08-18 19:20:21 2023-08-18T17:20:21.033Z    DEBUG   cursors cursor/registry.go:182  Deleting        {"total": 1, "id": 1, "duration": "1.102736ms"}
2023-08-18 19:20:21 2023-08-18T17:20:21.033Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:598  Response header: length:   173, id:    5, response_to:    7, opcode: OP_MSG
2023-08-18 19:20:21 2023-08-18T17:20:21.033Z    DEBUG   // 172.17.0.1:44848 -> 172.17.0.2:27017         clientconn/conn.go:599  Response message:
2023-08-18 19:20:21 {
2023-08-18 19:20:21   "Checksum": 0,
2023-08-18 19:20:21   "FlagBits": 0,
2023-08-18 19:20:21   "Sections": [
2023-08-18 19:20:21     {
2023-08-18 19:20:21       "Document": {
2023-08-18 19:20:21         "$k": [
2023-08-18 19:20:21           "cursor",
2023-08-18 19:20:21           "ok"
2023-08-18 19:20:21         ],
2023-08-18 19:20:21         "cursor": {
2023-08-18 19:20:21           "$k": [
2023-08-18 19:20:21             "firstBatch",
2023-08-18 19:20:21             "id",
2023-08-18 19:20:21             "ns"
2023-08-18 19:20:21           ],
2023-08-18 19:20:21           "firstBatch": [
2023-08-18 19:20:21             {
2023-08-18 19:20:21               "$k": [
2023-08-18 19:20:21                 "_id",
2023-08-18 19:20:21                 "Text",
2023-08-18 19:20:21                 "Number"
2023-08-18 19:20:21               ],
2023-08-18 19:20:21               "_id": {
2023-08-18 19:20:21                 "$o": "64dfa854e13a676f1b4e19e9"
2023-08-18 19:20:21               },
2023-08-18 19:20:21               "Text": "Initial Text",
2023-08-18 19:20:21               "Number": 42
2023-08-18 19:20:21             }
2023-08-18 19:20:21           ],
2023-08-18 19:20:21           "id": {
2023-08-18 19:20:21             "$l": "0"
2023-08-18 19:20:21           },
2023-08-18 19:20:21           "ns": "TestDataBase.SimpleItems"
2023-08-18 19:20:21         },
2023-08-18 19:20:21         "ok": {
2023-08-18 19:20:21           "$f": 1
2023-08-18 19:20:21         }
2023-08-18 19:20:21       },
2023-08-18 19:20:21       "Kind": 0
2023-08-18 19:20:21     }
2023-08-18 19:20:21   ]
2023-08-18 19:20:21 }
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 
2023-08-18 19:20:21 2023-08-18T17:20:21.060Z    INFO    listener        clientconn/listener.go:324      Connection stopped      {"conn": "172.17.0.1:44848 -> 172.17.0.2:27017"}
2023-08-18 19:20:21 2023-08-18T17:20:21.060Z    INFO    listener        clientconn/listener.go:324      Connection stopped      {"conn": "172.17.0.1:44846 -> 172.17.0.2:27017"}
2023-08-18 19:20:21 2023-08-18T17:20:21.060Z    INFO    listener        clientconn/listener.go:324      Connection stopped      {"conn": "172.17.0.1:44844 -> 172.17.0.2:27017"}
````

### PR DESCRIPTION
**Pull request by wazir-ahmed**
# Description

Closes #3224.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [ ] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [ ] I marked all done items in this checklist.

### CODE REVIEW

File: integration/update_compat_test.go [hunk 1]
```diff
@@ -181,87 +181,78 @@ func testUpdateManyCompat(t *testing.T, testCases map[string]testUpdateManyCompa
...
-							compatUpdateRes, compatErr = compatCollection.UpdateMany(ctx, filter, update, tc.updateOpts)
+					targetUpdateRes, targetErr = targetCollection.UpdateMany(ctx, filter, update, tc.updateOpts)
+					compatUpdateRes, compatErr = compatCollection.UpdateMany(ctx, filter, update, tc.updateOpts)
 
-							if targetErr != nil {
-								t.Logf("Target error: %v", targetErr)
-								t.Logf("Compat error: %v", compatErr)
+					if targetErr != nil {
+						t.Logf("Target error: %v", targetErr)
+						t.Logf("Compat error: %v", compatErr)
```
Comment (henvic) [inline integration/update_compat_test.go:220]: Why are you [just] printing targetErr and compatErr if target error is not nil? Is this just a leftover from manual testing?

**Comment by henvic** [comment]
Just a small comment that needs clarification. Otherwise, LGTM.

File: integration/update_compat_test.go (hunk 1 above)
Comment (wazir-ahmed) [reply integration/update_compat_test.go:220]: I have modified this function as per [this](https://ferretdb.slack.com/archives/C02NWN1K3MJ/p1702803985556339) discussion on slack. I have kept the existing code as it is. I see that the same pattern has been followed on many of the `compat*` functions in integration test.

Comment (wazir-ahmed) [reply integration/update_compat_test.go:220]: It makes sense for me. If target returns errors, then we compare it compatErr and return from the test (there is no point in continuing after that). If the assertion fails, then we will have both compatErr and targetErr available in the test output, so that we can debug.

File: integration/.golangci-new.yml [hunk 2]
```diff
@@ -18,6 +18,7 @@ linters-settings:
     exclude-functions:
       - (*database/sql.Rows).Close
       - (*github.com/FerretDB/FerretDB/internal/util/fsql.Rows).Close
+      - (*go.mongodb.org/mongo-driver/mongo.Cursor).Close
```
Comment (noisersup) [inline integration/.golangci-new.yml:21]: Why do we exclude that?

**Review by noisersup — DISMISSED** [review]
Apart from one question looks good to me

File: integration/.golangci-new.yml (hunk 2 above)
Comment (wazir-ahmed) [reply integration/.golangci-new.yml:21]: @noisersup `errcheck` linter throws error for unhandled return value even in `defer` statements, on statement such as,
https://github.com/FerretDB/FerretDB/blob/8edda5518ed210fcb92ee4850434381fab90d981/integration/update_compat_test.go#L246-L251

Though we have such statements all over the integration tests, I faced errors only on my changes in `testUpdateManyCompat`. After investigating, I found out that we only run linters on changed code. https://github.com/FerretDB/FerretDB/blob/8edda5518ed210fcb92ee4850434381fab90d981/integration/.golangci-new.yml#L162

IMO, it is safe to exclude this unhandled error. Otherwise, we change the defer statements as shown below, in many places of the codebase, just to keep the linter happy.
```golang
defer func() { _ = targetCursor.Close() }
```
There is no option in the `errcheck` tool to ignore unhandled errors from all `defer` statements. We have to ignore the functions one by one, as I have done.

**Review by henvic — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
Thank you!
