### PR TITLE
Require `limit` parameter in `delete` command

### LINKED ISSUE #982: Require `limit` in delete query
The goal of this task is to require a `limit` field with numerical value of 0 or 1 while running the `delete` query. 

Currently we allow sending the delete query without this field, which is unexpected behavior. See: https://www.mongodb.com/docs/v4.2/reference/command/delete/

 [The Example of the test that is failing for MongoDB and not for FerretDB](https://github.com/FerretDB/FerretDB/runs/7652477027?check_suite_focus=true).

Don't make a test too complicated.

### PR DESCRIPTION
**Pull request by noisersup**
# Description

This PR closes #982.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/delete_test.go [hunk 1]
```diff
@@ -55,3 +55,18 @@ func TestDeleteSimple(t *testing.T) {
...
+	ctx, collection := setup.Setup(t)
+	cmd := bson.D{
+		{"delete", collection.Name()},
+		{"deletes", bson.A{bson.D{{"q", bson.D{{"v", "foo"}}}}}},
+	}
+
+	expectedErr := "(Location40414) BSON field 'delete.deletes.limit' is missing but a required field"
+
+	res := collection.Database().RunCommand(ctx, cmd)
+	assert.EqualError(t, res.Err(), expectedErr)
```
Comment (AlekSi) [inline integration/delete_test.go:71]: We should compare error values, both types and content, not error strings. See other tests that use `mongo.CommandError`

**Review by AlekSi — CHANGES_REQUESTED** [review]

File: integration/delete_test.go (hunk 1 above)
Comment (AlekSi) [reply integration/delete_test.go:71]: See also `AssertEqualError` helper

File: integration/delete_test.go [hunk 2]
```diff
@@ -55,3 +56,22 @@ func TestDeleteSimple(t *testing.T) {
 		})
 	}
 }
+
+func TestDeleteLimitNotSet(t *testing.T) {
```
Comment (w84thesun) [inline integration/delete_test.go:60]: Do we want to add other cases like pass valid values, pass `float64`?

**Review by w84thesun — COMMENTED** [review]
Overall looks good, asked the question about test cases.

File: integration/delete_test.go (hunk 2 above)
Comment (noisersup) [reply integration/delete_test.go:60]: We could. I'm going to improve that then

File: internal/handlers/pg/msg_delete.go [hunk 3]
```diff
@@ -63,10 +63,17 @@ func (h *Handler) MsgDelete(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg,
...
+		l, err := d.Get("limit")
+		if err != nil {
+			return nil, common.NewErrorMsg(
+				common.ErrMissingField,
+				"BSON field 'delete.deletes.limit' is missing but a required field",
+			)
+		}
+
+		if limit, err = common.GetWholeNumberParam(l); err != nil {
+			return nil, err
```
Comment (rumyantseva) [inline internal/handlers/pg/msg_delete.go:76]: Is it enough to just return `err`? Shouldn't it be something like `NewErrorMsg(ErrBadValue, err)`?

Let's write a test that would generate this error? I guess, it could be something like `limit` is a string or a value like `42.13`.

File: internal/handlers/tigris/msg_delete.go [hunk 4]
```diff
@@ -66,10 +66,17 @@ func (h *Handler) MsgDelete(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg,
...
+
+		l, err := d.Get("limit")
+		if err != nil {
+			return nil, common.NewErrorMsg(
+				common.ErrMissingField,
+				"BSON field 'delete.deletes.limit' is missing but a required field",
+			)
+		}
+
+		if limit, err = common.GetWholeNumberParam(l); err != nil {
```
Comment (rumyantseva) [inline internal/handlers/tigris/msg_delete.go:78]: Same comment as for `pg`.

**Review by rumyantseva — CHANGES_REQUESTED** [review]
It seems to be that `bad_value` is missing if `limit` is not a correct number (see the comments).

File: internal/handlers/pg/msg_delete.go [hunk 5]
```diff
@@ -68,11 +68,21 @@ func (h *Handler) MsgDelete(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg,
...
+			return common.NewErrorMsg(
+				common.ErrMissingField,
+				"BSON field 'delete.deletes.limit' is missing but a required field",
+			)
+		}
+
+		if limit, err = common.GetWholeNumberParam(l); err != nil {
+			return common.NewErrorMsg(
+				common.ErrFailedToParse,
+				fmt.Sprintf("The limit field in delete objects must be 0 or 1. Got %v", l),
```
Comment (rumyantseva) [inline internal/handlers/pg/msg_delete.go:84]: And what if I set limit as 100? :)

File: internal/handlers/tigris/msg_delete.go [hunk 6]
```diff
@@ -211,3 +233,13 @@ func (h *Handler) delete(ctx context.Context, fp tigrisdb.FetchParam, docs []*ty
 
 	return len(ids), nil
 }
+
+// respondAsBulkWriteException calls the fun. If fun returns
+// not-nil error then it is wrapped with lazyerrors.Error.
+func respondAsBulkWriteException(fun func() error) error {
```
Comment (rumyantseva) [inline internal/handlers/tigris/msg_delete.go:239]: I don't like the word "Exception" here as I don't see what is "Exception" here.

**Review by rumyantseva — COMMENTED** [review]
I'd suggest sitting together and rewriting some things as this is not quite an exact thing we discussed at the standup yesterday.

File: internal/handlers/pg/msg_delete.go (hunk 5 above)
Comment (noisersup) [reply internal/handlers/pg/msg_delete.go:84]: Nice catch!

**Review by rumyantseva — APPROVED** [review]
LGTM for now. We might want to refactor something later (e.g. when we have transactions for Tigris), but I'd say for now this is enough.

**Review by w84thesun — APPROVED** [review]
