### PR TITLE
Fix embedded array query bug

### LINKED ISSUE #709: Query embedded array, special case
I accidentally found a case when FerretDB and Proxy give different results for the same embedded array query.

Data in the database:
`{ _id: 'array-embedded', value: [ [ "42",  "foo" ] ] }`

Query:
`{ value: ["42", "foo"] }`

Proxy found `array-embedded` item.
FerretDB didn't find it and returned an empty response.

To demonstrate the case I added a tiny test in #708.

When I run it with proxy the test pass: 
```
$ go test -timeout 90s -run ^TestQueryArrayEqual$ github.com/FerretDB/FerretDB/integration -v -count=1 -port=37017
=== RUN   TestQueryArrayEqual
=== PAUSE TestQueryArrayEqual
=== CONT  TestQueryArrayEqual
2022-06-07T17:34:42.946+0200    INFO    debug   debug/debug.go:60       Starting debug server on http://127.0.0.1:65311/
=== RUN   TestQueryArrayEqual/Embeded
=== PAUSE TestQueryArrayEqual/Embeded
=== CONT  TestQueryArrayEqual/Embeded
--- PASS: TestQueryArrayEqual (0.11s)
    --- PASS: TestQueryArrayEqual/Embeded (0.01s)
PASS
ok      github.com/FerretDB/FerretDB/integration        0.356s
```

When I run it with FerretDB the test fails: 
```
$go test -timeout 90s -run ^TestQueryArrayEqual$ github.com/FerretDB/FerretDB/integration -v -count=1 -port=27017
=== RUN   TestQueryArrayEqual
=== PAUSE TestQueryArrayEqual
=== CONT  TestQueryArrayEqual
2022-06-07T17:34:09.033+0200    INFO    debug   debug/debug.go:60       Starting debug server on http://127.0.0.1:65300/
=== RUN   TestQueryArrayEqual/Embeded
=== PAUSE TestQueryArrayEqual/Embeded
=== CONT  TestQueryArrayEqual/Embeded
    query_array_test.go:56: 
                Error Trace:    query_array_test.go:56
                Error:          Not equal: 
                                expected: []interface {}{"array-embeded-special"}
                                actual  : []interface {}{}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,2 @@
                                -([]interface {}) (len=1) {
                                - (string) (len=21) "array-embeded-special"
                                +([]interface {}) {
                                 }
                Test:           TestQueryArrayEqual/Embeded
=== CONT  TestQueryArrayEqual
    setup.go:118: Keeping database "testqueryarrayequal" and collection "testqueryarrayequal" for debugging.
--- FAIL: TestQueryArrayEqual (0.18s)
    --- FAIL: TestQueryArrayEqual/Embeded (0.02s)
FAIL
FAIL    github.com/FerretDB/FerretDB/integration        0.382s
FAIL
```

### LINKED ISSUE #732: FerretDB returns incorrect results for empty nested arrays
### How to reproduce

```
db.embedded.insertOne( {"_id": "array-empty-nested", "value": [[]]});

db.embedded.find({ "value.0": []})
db.embedded.find({ value: []})
db.embedded.find({ value: {$eq:  []}})
```

### Expected result

Every `find` should return the doc with a nested array:

```
[ { _id: 'array-empty-nested', value: [ [] ] } ]
```

### Actual result

Nothing was found.

### To do

- Uncomment `array-empty-nested` example in https://github.com/FerretDB/FerretDB/blob/main/integration/shareddata/composites.go
- Run `task test-integration-mongodb` and fix tests that fail
- When all the tests for `task test-integration-mongodb` pass, run `task test-integration-ferretdb`
- Investigate why FerretDB provides incorrect results and fix the problems

### PR DESCRIPTION
**Pull request by ribaraka**
Closes #709.
Closes #732.

### CODE REVIEW

File: integration/shareddata/composites.go [hunk 1]
```diff
@@ -43,3 +43,23 @@ var Composites = &Values[string]{
...
+// ArraySet contains various array variations for tests.
+//
+// This shared data set is not frozen yet, but please add to it only if it is really shared.
+var ArraySet = &Values[string]{
+	data: map[string]any{
+		"array-one":              bson.A{int32(42)},
+		"array-two":              bson.A{42, "foo"},
+		"array-three":            bson.A{int32(42), "foo", nil},
+		"array-three-reverse":    bson.A{nil, "foo", int32(42)},
+		"array-empty":            bson.A{},
```
Comment (AlekSi) [inline integration/shareddata/composites.go:56]: Let's merge it into composites

**Review by AlekSi — APPROVED** [review]
