### PR TITLE
Fix `saslContinue` prematurely returning `done`

### LINKED ISSUE #4385: Fix speculative authentication
### What should be done?

Speculative authentication does not work correctly in some cases (in the currently unreleased version).

Steps to reproduce:
1.
```sh
docker run --rm -p 5432:5432 \
  -e POSTGRES_USER=p_user \
  -e POSTGRES_PASSWORD=p_password \
  -e POSTGRES_DB=p_ferretdb \
  postgres
```
2.
```sh
docker run --rm -p 27017:27017 \
  -e FERRETDB_POSTGRESQL_URL=postgres://p_user:p_password@host.docker.internal:5432/p_ferretdb \
  -e FERRETDB_TEST_ENABLE_NEW_AUTH=true \
  -e FERRETDB_SETUP_DATABASE=ferretdb \
  -e FERRETDB_SETUP_USERNAME=username \
  -e FERRETDB_SETUP_PASSWORD=password \
  ghcr.io/ferretdb/ferretdb-dev:main
```
3.
```sh
# works
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb?authMechanism=SCRAM-SHA-1'

# works
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb?authMechanism=SCRAM-SHA-256'

# doesn't work
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb'
```

We probably should sync changes between 1.x and 2.x to resolve that problem.

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Bypassing backend authentication is moved to after `SCRAM` conversation is succeeded.
Sets `saslContinue` `done:true` from SCRAM conversation.

Closes #4385.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handler/msg_saslcontinue.go [hunk 1]
```diff
@@ -70,16 +70,18 @@ func (h *Handler) MsgSASLContinue(ctx context.Context, msg *wire.OpMsg) (*wire.O
 		)
 	}
 
-	binResponse := types.Binary{
-		B: []byte(response),
+	h.L.Debug("saslContinue succeed", zap.Bool("valid", conv.Valid()), zap.Bool("done", conv.Done()))
+
+	if conv.Valid() && conv.Done() {
+		conninfo.Get(ctx).SetBypassBackendAuth()
```
Comment (chilagrow) [inline internal/handler/msg_saslcontinue.go:76]: Bypass only after valid conversation and conversation being done.

File: internal/handler/msg_saslcontinue.go [hunk 2]
```diff
@@ -70,16 +70,18 @@ func (h *Handler) MsgSASLContinue(ctx context.Context, msg *wire.OpMsg) (*wire.O
...
 	}
 
 	var reply wire.OpMsg
 	must.NoError(reply.SetSections(wire.MakeOpMsgSection(
 		must.NotFail(types.NewDocument(
 			"conversationId", int32(1),
-			"done", true,
-			"payload", binResponse,
+			"done", conv.Done(),
```
Comment (chilagrow) [inline internal/handler/msg_saslcontinue.go:83]: Let's return from conv.Done().

**Review by noisersup — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]
