### PR TITLE
Include `SpeculativeAuthenticate` changes

### LINKED ISSUE #4385: Fix speculative authentication
### What should be done?

Speculative authentication does not work correctly in some cases (in the currently unreleased version).

Steps to reproduce:
1.
```sh
docker run --rm -p 5432:5432 \
  -e POSTGRES_USER=p_user \
  -e POSTGRES_PASSWORD=p_password \
  -e POSTGRES_DB=p_ferretdb \
  postgres
```
2.
```sh
docker run --rm -p 27017:27017 \
  -e FERRETDB_POSTGRESQL_URL=postgres://p_user:p_password@host.docker.internal:5432/p_ferretdb \
  -e FERRETDB_TEST_ENABLE_NEW_AUTH=true \
  -e FERRETDB_SETUP_DATABASE=ferretdb \
  -e FERRETDB_SETUP_USERNAME=username \
  -e FERRETDB_SETUP_PASSWORD=password \
  ghcr.io/ferretdb/ferretdb-dev:main
```
3.
```sh
# works
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb?authMechanism=SCRAM-SHA-1'

# works
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb?authMechanism=SCRAM-SHA-256'

# doesn't work
mongosh 'mongodb://username:password@127.0.0.1:27017/ferretdb'
```

We probably should sync changes between 1.x and 2.x to resolve that problem.

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #4385.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handler/cmd_query.go [hunk 1]
```diff
@@ -19,9 +19,10 @@ import (
 	"fmt"
 	"strings"
 
-	"github.com/FerretDB/FerretDB/internal/handler/common"
+	"go.uber.org/zap"
+
+	"github.com/FerretDB/FerretDB/internal/bson"
```
Comment (chilagrow) [inline internal/handler/cmd_query.go:24]: @AlekSi we have a linter checking that `bson` namespace should not be imported, is `types` still preferred over `bson` in handler package?

Comment (chilagrow) [reply internal/handler/cmd_query.go]: Actually I kept it to use types to avoid too many changes.

**Review by AlekSi — APPROVED** [review]
