### PR TITLE
Fix unit tests for indexes

### LINKED ISSUE #3375: Store index metadata
### What should be done?

Information about indexes should be stored in metadata in the same way as in the old `pgdb` package.

Create unique index for `_id` when collection is created.

Only metadata/registry changes are in the scope. The rest is in #3394, #3399, #3397.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/backends/postgresql/metadata

### Definition of Done

- unit tests added/updated;
- spot refactorings done.

### PR DESCRIPTION
**Pull request by rumyantseva**
# Description

Closes #3375.

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/backends/postgresql/postgresql.go [hunk 1]
```diff
@@ -39,7 +39,13 @@ type stats struct {
 }
 
 // collectionsStats returns statistics about tables and indexes for the given collections.
+//
+// If the list of collections is empty, then stats filled with zero values is returned.
```
Comment (rumyantseva) [inline internal/backends/postgresql/postgresql.go:43]: This fixes a situation when the empty list is provided, and the `SELECT` query below returns an invalid syntax error.  There were some tests that were failing because of it.

File: internal/backends/postgresql/metadata/registry_test.go [hunk 2]
```diff
@@ -407,6 +407,46 @@ func TestRenameCollection(t *testing.T) {
 	})
 }
 
+func TestMetadataIndexes(t *testing.T) {
```
Comment (rumyantseva) [inline internal/backends/postgresql/metadata/registry_test.go:410]: Moved as a separate test, so it doesn't look confusing.

**Review by noisersup — APPROVED** [review]
LGTM!

**Review by AlekSi — APPROVED** [review]
