### PR TITLE
Make Data API without authentication if requested

### LINKED ISSUE #4790: Data API fails when authentication is disabled
### What should be done?

Should Data API be supported when authentication is disabled? At the moment it fails like below.

Start FerretDB without authentication using `--no-auth` flag or the development environment with `task run`.

Send a request, it returns `curl: (52) Empty reply from server`.
```
$ curl -X POST http://127.0.0.1:8899/action/insertOne   -H "Content-Type: application/json"    -d '{
        "database": "test",
        "collection": "users",
        "document": {
          "name": "Andrew",
          "email": "andrew@example.com",
          "age": 25
        }
      }'
curl: (52) Empty reply from server
```
FerretDB log shows more information.
```
2025-02-20T10:53:50.841+0900    DEBUG   server/insert_one.go:36 Request:                              
POST /action/insertOne HTTP/1.1                                                                                                                                                                             
Host: 127.0.0.1:8899                                                                                                                                                                                        
Accept: */*                                                                                                                                                                                                 
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=                                                                                                                                                               
Content-Length: 189                                                                                                                                                                                         
Content-Type: application/json                                                                        
User-Agent: curl/7.81.0                                                                               
                                                                                                      
{                                                                                                                                                                                                           
        "database": "test",                                                                           
        "collection": "users",                                                                                                                                                                              
        "document": {                                                                                 
          "name": "Andrew",                                                                                                                                                                                 
          "email": "andrew@example.com",                                                              
          "age": 25                                                                                                                                                                                         
        }                                                                                             
      }                                                                                               
        {"name":"dataapi"}                                                                                                                                                                                  
2025-02-20T10:53:50.842+0900    INFO+2  http: panic serving 127.0.0.1:57300: connInfo is not set in context                                    
goroutine 31 [running]:                                                                               
net/http.(*conn).serve.func1()                                                                        
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:1947 +0x10a
panic({0x15b86e0?, 0x1df0c40?})                                                                       
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/runtime/panic.go:785 +0x132   
github.com/FerretDB/FerretDB/v2/internal/clientconn/conninfo.Get({0x1e012b8, 0xc0005e9530})
        /home/chi/workspace/FerretDB/internal/clientconn/conninfo/ctx.go:34 +0x185
github.com/FerretDB/FerretDB/v2/internal/handler/session.getUserID({0x1e012b8, 0xc0005e9530})
        /home/chi/workspace/FerretDB/internal/handler/session/session.go:135 +0xaf
github.com/FerretDB/FerretDB/v2/internal/handler/session.(*Registry).CreateOrUpdateByLSID(0xc0005780a0, {0x1e012b8, 0xc0005e9530}, {0xc0002dce00, 0x75, 0x75})
        /home/chi/workspace/FerretDB/internal/handler/session/registry.go:169 +0xe5
github.com/FerretDB/FerretDB/v2/internal/handler.(*Handler).MsgInsert(0xc000702020, {0x1e012b8, 0xc0005e9530}, 0xc00049e6a0)
        /home/chi/workspace/FerretDB/internal/handler/msg_insert.go:38 +0x3f2
github.com/FerretDB/FerretDB/v2/internal/dataapi/server.(*Server).InsertOne(0xc000130330, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6640)
        /home/chi/workspace/FerretDB/internal/dataapi/server/insert_one.go:66 +0x6bd
github.com/FerretDB/FerretDB/v2/internal/dataapi/api.(*ServerInterfaceWrapper).InsertOne.func1({0x1dff2d0, 0xc00034c2a0}, 0xc0001f6640)
        /home/chi/workspace/FerretDB/internal/dataapi/api/gen.go:597 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0003b0640, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6640)
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:2220 +0x48
github.com/FerretDB/FerretDB/v2/internal/dataapi/api.(*ServerInterfaceWrapper).InsertOne(0xc00027a210, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6500)
        /home/chi/workspace/FerretDB/internal/dataapi/api/gen.go:604 +0x3af
net/http.HandlerFunc.ServeHTTP(0xc000130480, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6500)
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:2220 +0x48
net/http.(*ServeMux).ServeHTTP(0xc0002a21c0, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6500)
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:2747 +0x256
net/http.serverHandler.ServeHTTP({0x1dface8?}, {0x1dff2d0, 0xc00034c2a0}, 0xc0001f6500)
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:3210 +0x2a2
net/http.(*conn).serve(0xc0000403f0, {0x1e012b8, 0xc00027a6c0})
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:2092 +0x12a5
created by net/http.(*Server).Serve in goroutine 67 
        /home/chi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/net/http/server.go:3360 +0x8ed
```

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/dataapi

### Definition of Done

- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Close #4790.

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [x] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/dataapi/listener.go [hunk 1]
```diff
@@ -69,17 +71,21 @@ func (lis *Listener) Run(ctx context.Context) {
 	}
 
 	srv := &http.Server{
-		Handler: srvHandler,
-		BaseContext: func(_ net.Listener) context.Context {
-			return ctx
+		Handler:  srvHandler,
+		ErrorLog: slog.NewLogLogger(lis.opts.L.Handler(), slog.LevelError),
+		BaseContext: func(net.Listener) context.Context {
+			return conninfo.Ctx(ctx, conninfo.New())
```
Comment (AlekSi) [inline internal/dataapi/listener.go:77]: That's the main change – we should always return context with `connInfo`

File: internal/dataapi/listener_test.go [hunk 2]
```diff
@@ -39,7 +39,7 @@ import (
 )
 
 func TestSmokeDataAPI(t *testing.T) {
-	addr, db := setupDataAPI(t)
+	addr, db := setupDataAPI(t, true)
```
Comment (AlekSi) [inline internal/dataapi/listener_test.go:42]: Changing that to `false` would make the old code to panic

File: internal/dataapi/listener.go (hunk 1 above)
Comment (chilagrow) [reply internal/dataapi/listener.go:77]: I see, so context passed to our handler now always contains connInfo :+1:
