### PR TITLE
Test `getMore` integration test using one connection pool

### LINKED ISSUE #1807: Investigate `TestGetMoreErrors` sessions errors
I think our tests should have better control over connections. `*mongo.Client` uses a pool of connections; be default we don't know if two subsequent commands use the same connection or not.

It should be possible to:
* create one client that uses MongoDB URI query parameters to fix connection pool size to 1, ensuring that all commands run with this client use the same connection;
* create a separate client like the first one, ensuring that different clients use different connections.

That might require quite some refactoring of our tests.

---

### What should be done?

In #1733 was introduced test `TestGetMoreErrors`. To test parameters other than cursor id we need to call `find` first to get the correct cursor id. The problem is that from time to time MongoDB will return an error `(Location50738) Cannot run getMore on cursor 5531067849097530169, which was created in session ..., in session ... `. Adding those tests would make MongoDB integration test flaky.

We should either investigate why MongoDB returns that error or a way to enable those test without failing other tests.

### Where?

Search for this issue ID in the code.

### Definition of Done
- unit tests added;
- integration tests added;
- compatibility tests added;
- spot refactorings were done;
- user documentation updated;

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1807.

## Readiness checklist

- [ ] I added/updated unit tests.
- [x] I added/updated integration/compatibility tests.
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

File: integration/query_test.go [hunk 1]
```diff
@@ -950,7 +950,11 @@ func TestQueryBatchSize(t *testing.T) {
 
 func TestQueryCommandGetMore(t *testing.T) {
 	t.Parallel()
-	ctx, collection := setup.Setup(t)
+	s := setup.SetupWithOpts(t, &setup.SetupOpts{
+		ClientOptions: options.Client().SetMaxPoolSize(1),
```
Comment (AlekSi) [inline integration/query_test.go:954]: At the very least, we should also set `SetMinPoolSize` to prevent the number of active connections from dropping to zero. Please also check other options.

File: integration/setup/client.go [hunk 2]
```diff
@@ -77,10 +77,8 @@ func mongoDBURI(tb testing.TB, opts *mongoDBURIOpts) string {
 	return u.String()
 }
 
-// makeClient returns new client for the given working MongoDB URI.
-func makeClient(ctx context.Context, uri string) (*mongo.Client, error) {
-	clientOpts := options.Client().ApplyURI(uri)
-
+// makeClient returns new client for the given MongoDB client options.
+func makeClient(ctx context.Context, clientOpts *options.ClientOptions) (*mongo.Client, error) {
```
Comment (AlekSi) [inline integration/setup/client.go:81]: Please pass all options via URI's query parameters

File: integration/setup/setup.go [hunk 3]
```diff
@@ -86,6 +86,9 @@ type SetupOpts struct {
 
 	// Benchmark data provider. If empty, collection is not created.
 	BenchmarkProvider shareddata.BenchmarkProvider
+
+	// ClientOptions overwrites the options set in MongoDB URI when the same option is set.
+	ClientOptions *options.ClientOptions
```
Comment (AlekSi) [inline integration/setup/setup.go:91]:
```suggestion
	ExtraOptions url.Values
```

**Comment by AlekSi** [comment]
> Do we want to test this only for FerretDB?

First of all, we want to understand how MongoDB works. We can't do that if we don't run tests for it.

> As far as I know, MongoDB does not provide information related to uniquely identifying a connection for commands.

That's why we fix `*mongo.Client`'s pool size to 1 – it is easy to uniquely identify a connection if there is only one of them.

>> create a separate client like the first one, ensuring that different clients use different connections.
>
> Also this can be implemented for FerretDB, but I didn't find equivalent check for MongoDB.

Not sure I understand why we can't create a separate `*mongo.Client` instance for MongoDB. See `TestCommandsDiagnosticWhatsMyURI` for example.

> If we want to ensure FerretDB does use the same connection,

It will use the same connection if there is only one. And if there is only one, if we configure `*mongo.Client` to use the only one.

File: integration/commands_diagnostic_test.go [hunk 4]
```diff
@@ -406,3 +409,130 @@ func TestCommandsDiagnosticWhatsMyURI(t *testing.T) {
...
+	s := setup.SetupWithOpts(t, &setup.SetupOpts{
+		ExtraOptions: q1,
+	})
+
+	collection1 := s.Collection
+	databaseName := s.Collection.Database().Name()
+	collectionName := s.Collection.Name()
+
+	t.Run("SameClient", func(t *testing.T) {
+		setup.SkipExceptMongoDB(t, "https://github.com/FerretDB/FerretDB/issues/2906")
```
Comment (chilagrow) [inline integration/commands_diagnostic_test.go:435]: Fails on FerretDB, see https://github.com/FerretDB/FerretDB/actions/runs/5373306151/jobs/9747542079?pr=2878

File: integration/query_test.go (hunk 1 above)
Comment (chilagrow) [reply integration/query_test.go]: Good idea, applied in the tests.

File: integration/setup/client.go (hunk 2 above)
Comment (chilagrow) [reply integration/setup/client.go]: Using URI now :+1:

File: integration/commands_diagnostic_test.go (hunk 4 above)
Comment (AlekSi) [reply integration/commands_diagnostic_test.go:435]: All MongoDB URI query parameters are driver / client options, not MongoDB / FerretDB server options. `maxPoolSize`, `minPoolSize` and few other options speicify how many connections the client opens and when. Those options are not visible for the server.

File: integration/commands_diagnostic_test.go [hunk 5]
```diff
@@ -406,3 +409,133 @@ func TestCommandsDiagnosticWhatsMyURI(t *testing.T) {
...
+
+		t.Parallel()
+
+		num := runtime.GOMAXPROCS(-1) * 10
```
Comment (AlekSi) [inline integration/commands_diagnostic_test.go:439]: Please use `teststress.Stress`

File: integration/query_test.go [hunk 6]
```diff
@@ -950,7 +951,19 @@ func TestQueryBatchSize(t *testing.T) {
...
+
+	q := url.Values{}
+
+	// set 1 to ensure only one pool exists duration of the test,
+	// which forces a client to use a single connection pool
+	q.Set("maxPoolSize", "1")
+	q.Set("minPoolSize", "1")
+
+	s := setup.SetupWithOpts(t, &setup.SetupOpts{
+		ExtraOptions: q,
```
Comment (AlekSi) [inline integration/query_test.go:963]:
```suggestion
		ExtraOptions: url.Values{
			"minPoolSize": []string{"1"},
			"maxPoolSize": []string{"1"},
		}
```

or something like that

File: integration/setup/client.go [hunk 7]
```diff
@@ -77,10 +77,24 @@ func mongoDBURI(tb testing.TB, opts *mongoDBURIOpts) string {
 	return u.String()
 }
 
-// makeClient returns new client for the given working MongoDB URI.
-func makeClient(ctx context.Context, uri string) (*mongo.Client, error) {
-	clientOpts := options.Client().ApplyURI(uri)
+// makeClient returns new client for the given MongoDB URI and extra options.
+// The extraOpts that comes later overwrites value for the query key.
+func makeClient(ctx context.Context, uri string, extraOpts url.Values) (*mongo.Client, error) {
```
Comment (AlekSi) [inline integration/setup/client.go:82]:
```suggestion
func makeClient(ctx context.Context, uri string) (*mongo.Client, error) {
```

Options should already be in the `uri`

File: integration/setup/client.go [hunk 8]
```diff
@@ -103,15 +117,15 @@ func makeClient(ctx context.Context, uri string) (*mongo.Client, error) {
 //
 // If the connection can't be established, it panics,
 // as it doesn't make sense to proceed with other tests if we couldn't connect in one of them.
-func setupClient(tb testing.TB, ctx context.Context, uri string) *mongo.Client {
+func setupClient(tb testing.TB, ctx context.Context, uri string, extraOpts url.Values) *mongo.Client {
```
Comment (AlekSi) [inline integration/setup/client.go:120]:
```suggestion
func setupClient(tb testing.TB, ctx context.Context, uri string) *mongo.Client {
```

**Review by AlekSi — CHANGES_REQUESTED** [review]

File: integration/query_test.go [hunk 9]
```diff
@@ -1179,15 +1190,48 @@ func TestQueryCommandGetMore(t *testing.T) {
 				Message: "BSON field 'getMore.collection' is missing but a required field",
 			},
 		},
+		"UnsetAllBatchSize": {
```
Comment (chilagrow) [inline integration/query_test.go:1193]: These tests address this comment https://github.com/FerretDB/FerretDB/pull/2864#discussion_r1243195284

File: integration/query_test.go [hunk 10]
```diff
@@ -1179,15 +1190,48 @@ func TestQueryCommandGetMore(t *testing.T) {
...
 			}
 
-			// TODO: https://github.com/FerretDB/FerretDB/issues/1807
-			// Do not run tests in parallel, MongoDB throws error that session and cursor do not match.
+			// Do not run subtests in t.Parallel() to reduce the occurrence
+			// of session error. Even the same connection is used for the test
+			// by setting `minPoolSize` and `maxPoolSize` to 1, on rare occasion
+			// it returns error due to different session calling `find` and `getMore`.
+			// Supporting session would help us understand fix it
+			// https://github.com/FerretDB/FerretDB/issues/153.
```
Comment (chilagrow) [inline integration/query_test.go:1233]: So far this hasn't happened as long as sub tests don't run in parallel. But just a warning

File: integration/commands_diagnostic_test.go (hunk 4 above)
Comment (chilagrow) [reply integration/commands_diagnostic_test.go]: This was totally my fault, I forgot to add pool size to newly created listeners :sweat:

File: integration/commands_diagnostic_test.go (hunk 5 above)
Comment (chilagrow) [reply integration/commands_diagnostic_test.go]: Made minor change to export goroutine numbers.

**Review by noisersup — DISMISSED** [review]
Looks great!

File: integration/query_test.go [hunk 11]
```diff
@@ -1280,3 +1324,114 @@ func TestQueryCommandGetMore(t *testing.T) {
...
+	collection1 := s.Collection
+	databaseName := s.Collection.Database().Name()
+	collectionName := s.Collection.Name()
+
+	docs := generateDocuments(0, 5)
+	_, err := collection1.InsertMany(s.Ctx, docs)
+	require.NoError(t, err)
+
+	t.Run("SameClient", func(t *testing.T) {
+		// Do not run subtests in t.Parallel() to reduce the occurrence
```
Comment (AlekSi) [inline integration/query_test.go:1349]: That should eliminate those occurrences, not just reduce them

File: integration/query_test.go [hunk 12]
```diff
@@ -1280,3 +1324,114 @@ func TestQueryCommandGetMore(t *testing.T) {
...
+		}).Decode(&res)
+		require.NoError(t, err)
+	})
+
+	t.Run("DifferentClient", func(t *testing.T) {
+		// error returned from using different clients are session related error,
+		// hence currently FerretDB does not return an error
+		setup.SkipExceptMongoDB(t, "https://github.com/FerretDB/FerretDB/issues/153")
+
+		t.Parallel()
```
Comment (AlekSi) [inline integration/query_test.go:1390]: It also can't be a parallel test – it will be broken once we add another parallel subtest

File: integration/setup/client.go [hunk 13]
```diff
@@ -33,26 +33,43 @@ import (
 
 // mongoDBURIOpts represents mongoDBURI's options.
 type mongoDBURIOpts struct {
+	baseURI        string
```
Comment (AlekSi) [inline integration/setup/client.go:36]: I will like we are going back and forth there.

`mongoDBURI` returns a MongoDB URI for the given options. Those options are created only by the in-process listener, where no URI exists and we need to create one.

When URI exists (for example, when the target system is not in-process FerretDB), we just use it with extra query options for specific tests if they need them.

With this change, `mongoDBURI` could be used to construct MongoDB URI from many different options, making it much harder to understand.

Comment (chilagrow) [reply integration/setup/client.go:36]: Okie, so mongoDBURI should not be modified because it's for in-process listener and parameters should stay vanilla. Once mongoDBURI is built, then I can use that uri to add extra query options then.

File: integration/query_test.go (hunk 12 above)
Comment (chilagrow) [reply integration/query_test.go:1390]: Yep thanks

File: integration/query_test.go (hunk 11 above)
Comment (chilagrow) [reply integration/query_test.go:1349]: In practice, I'm not 100% sure that it eliminates them. But that is the hope yes.

File: integration/commands_diagnostic_test.go [hunk 14]
```diff
@@ -404,3 +406,106 @@ func TestCommandsDiagnosticWhatsMyURI(t *testing.T) {
 		assert.NotEqual(t, ports[0], ports[1])
 	}
 }
+
+// TestCommandWhatsMyURIConnection tests that a client uses the same connection for
+// all commands run by the client, and different clients use different connection.
+// The port number is used to validate if the same connection is used or not,
+// since unique port number is assigned to each client connection in the test setup.
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/commands_diagnostic_test.go:413]: Yes true thanks, purely for me to check our integration setup is working.... Let me update the comment.

File: integration/query_test.go [hunk 15]
```diff
@@ -1280,3 +1324,114 @@ func TestQueryCommandGetMore(t *testing.T) {
...
+		err = collection1.Database().RunCommand(s.Ctx, bson.D{
+			{"getMore", cursorID},
+			{"collection", collection1.Name()},
+		}).Decode(&res)
+		require.NoError(t, err)
+	})
+
+	t.Run("DifferentClient", func(t *testing.T) {
+		// error returned from using different clients are session related error,
+		// hence currently FerretDB does not return an error
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/query_test.go:1387]: Last I tested, FerretDB does not return error. I could return not implemented error in place though.

File: integration/setup/client.go (hunk 13 above)
Comment (AlekSi) [reply integration/setup/client.go:36]: We could probably rename that function to make it more clear

File: integration/commands_diagnostic_test.go [hunk 16]
```diff
@@ -404,3 +406,106 @@ func TestCommandsDiagnosticWhatsMyURI(t *testing.T) {
...
+func TestCommandWhatsMyURIConnection(t *testing.T) {
+	t.Parallel()
+
+	// set minPoolSize and maxPoolSize 1 to ensure only one pool exists duration of the test,
+	// which forces a client to use a single connection pool
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/commands_diagnostic_test.go:418]: Thanks let me update the comment!

File: integration/query_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (AlekSi) [reply integration/query_test.go:1387]: https://github.com/FerretDB/FerretDB/blob/5b1e6b61547e7e644e3c023694baa2adff21afde/internal/handlers/common/getmore.go#L89-L90

https://github.com/FerretDB/FerretDB/blob/5b1e6b61547e7e644e3c023694baa2adff21afde/internal/handlers/common/getmore.go#L111

If there is a bug, we should fix it. In any case, that test should check that some error is returned

File: integration/setup/client.go (hunk 13 above)
Comment (chilagrow) [reply integration/setup/client.go:36]: Any preference on the name?  `InProcessFerretDBURI`?

File: integration/query_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/query_test.go:1387]: Perfect, let me check.

[the remark this answers is not in the document]
Comment (AlekSi) [reply integration/query_test.go:1387]: Ah… Oh… Well, yeah, I get it now… Yeah, okat :)

[the remark this answers is not in the document]
Comment (chilagrow) [reply integration/query_test.go:1387]: > Ah… Oh… Well, yeah, I get it now… Yeah, okay :)

What did I miss?? :thinking:

[the remark this answers is not in the document]
Comment (AlekSi) [reply integration/query_test.go:1387]: In that case, the username, database, and collection are all the same. In theory, even without sessions, we could check that the _connection_ (client's port) is the same. But that would probably break more things. So yeah, let's keep it.

File: integration/query_test.go (hunk 11 above)
Comment (AlekSi) [reply integration/query_test.go:1349]: The only case when it will not be fixed is if the client closes and re-opens that single connection. If it does, we could use it as we want in all those tests. With `maxIdleTimeMS=0` (which is a default, but I think we could pass that explicitly to make things a bit more clear), that should not happen.

Comment (chilagrow) [reply integration/query_test.go:1349]: Thanks for looking into this. Great.

File: integration/setup/client.go (hunk 13 above)
Comment (AlekSi) [reply integration/setup/client.go:36]: I don't know :)

File: integration/setup/setup.go [hunk 17]
```diff
@@ -133,13 +137,31 @@ func SetupWithOpts(tb testing.TB, opts *SetupOpts) *SetupResult {
...
+			for _, v := range vs {
+				q.Set(k, v)
+			}
+		}
+
+		u.RawQuery = q.Encode()
+		uri = u.String()
+
+		// If ExtraOptions is set for in-process FerretDB, two clients are created
+		// on purpose. setupListener creates a client to check in-process FerretDB
```
Comment (AlekSi) [inline integration/setup/setup.go:162]: No, there is no purpose now :)

**Review by AlekSi — APPROVED** [review]

File: integration/setup/setup.go (hunk 17 above)
Comment (AlekSi) [reply integration/setup/setup.go]: @chilagrow PTAL at my changes

Comment (chilagrow) [reply integration/setup/setup.go]: Thank you for refactoring that part of the code :+1:

**Review by noisersup — APPROVED** [review]
:+1:
