### PR TITLE
Fix `$pop` operator error handling of non-existent path

### LINKED ISSUE #1663: `$pop` with non-existing dot notation path does not fail
### Versions

0.7.1

### What did you do?

Moved `TestUpdateFieldCompatPop` test `PopDotNotation` to compat. 

### What did you expect to see?

Same error as compat

```
    update_field_compat_test.go:495: 
        	Error:      	Received unexpected error:
        	            	write exception: write errors: [Cannot use the part (array) of (v.array) to traverse the element ({v: /foo/i})]
        	Test:       	TestUpdateFieldCompatPop/PopDotNotation/TestUpdateFieldCompatPop-PopDotNotation_Regexes/regex
        	Messages:   	compat error; target returned no error
            --- FAIL: TestUpdateFieldCompatPop/PopDotNotation/TestUpdateFieldCompatPop-PopDotNotation_Regexes/regex 
```

### What did you see instead?

No error on scalar shareddata.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1663.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

File: internal/handlers/common/update_array_operators.go [hunk 1]
```diff
@@ -91,6 +97,40 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
...
+		val := must.NotFail(doc.Get(prefix))
+		if prefixDoc, ok := val.(*types.Document); ok {
+			// recursively check if document contains prefix.
+			return ensureNonExistentPrefix(prefixDoc, prefix, path.TrimPrefix())
+		}
+
+		return commonerrors.NewWriteErrorMsg(
+			commonerrors.ErrUnsuitableValueType,
+			fmt.Sprintf(
+				"Cannot use the part (%s) of (%s) to traverse the element ({%s: %v})",
```
Comment (chilagrow) [inline internal/handlers/common/update_array_operators.go:121]: Message is not the same, please suggest if you know an easy fix.

```
compat -   Message: (string) (len=99) "Cannot use the part (array) of (v.array.foo.array) to traverse the element ({v: [ \"c\", \"b\", \"a\" ]})",
target  +   Message: (string) (len=92) "Cannot use the part (array) of (v.array.foo.array) to traverse the element ({v: &{[c b a]}})",
```

```
compat -   Message: (string) (len=84) "Cannot use the part (array) of (v.array.foo.array) to traverse the element ({v: []})",
target +   Message: (string) (len=87) "Cannot use the part (array) of (v.array.foo.array) to traverse the element ({v: &{[]}})",
```

File: internal/handlers/common/update_array_operators.go [hunk 2]
```diff
@@ -91,6 +97,40 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
 	return changed, nil
 }
 
+// ensureNonExistentPrefix checks if a given path and its prefix
+// does not exist in doc. It returns error if any prefix exists in the path.
```
Comment (rumyantseva) [inline internal/handlers/common/update_array_operators.go:101]: Let's specify what type of error it returns as it looks important (that's the error we want to return in the response).

File: internal/handlers/common/update_array_operators.go [hunk 3]
```diff
@@ -91,6 +97,40 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
 	return changed, nil
 }
 
+// ensureNonExistentPrefix checks if a given path and its prefix
```
Comment (rumyantseva) [inline internal/handlers/common/update_array_operators.go:100]: Based on the description I don't understand what's the difference between this func and `HasByPath`.

**Review by rumyantseva — COMMENTED** [review]
I guess it's something `$pop`-specific, then probably it's fine... But I don't really understand the difference between this case and `hasByPath`. If `hasByPath` returns false, we check if the prefix exists? Can't we reuse `hasByPath` for it once again but only for prefix?

Also, the title of this PR doesn't look suitable for release notes, I believe it should mention `$pop` as an operator (like we do in other PRs), not just the word "Pop".

**Comment by chilagrow** [comment]
> I guess it's something $pop-specific, then probably it's fine... But I don't really understand the difference between this case and hasByPath. If hasByPath returns false, we check if the prefix exists? Can't we reuse hasByPath for it once again but only for prefix?
Also, the title of this PR doesn't look suitable for release notes, I believe it should mention $pop as an operator (like we do in other PRs), not just the word "Pop". The title doesn't describe if we fix the bug or what actually is happening. As a user who doesn't have any idea about the issue you solve, I'd be confused seeing such a sentence in release notes.

can't use doc.HasByPath(path) because pop does not error on non-existent path, pop returns error if other value type exists on part of path.

File: internal/handlers/common/update_array_operators.go (hunk 2 above)
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go]: Thanks I updated the comment

File: internal/handlers/common/update_array_operators.go (hunk 3 above)
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go]: Added comment in the code :+1:

**Review by w84thesun — COMMENTED** [review]
Overall good, proposed value format suggestion.

File: internal/handlers/common/update_array_operators.go (hunk 1 above)
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go:124]: Thanks amazing!

**Review by w84thesun — DISMISSED** [review]
👍

File: internal/handlers/common/update_array_operators.go [hunk 4]
```diff
@@ -91,6 +96,44 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
 	return changed, nil
 }
 
+// checkUnsuitableValueError returns ErrUnsuitableValueType when part of
+// the path is used by non document value type.
+// If path is "v.foo" and
+// - doc is {v: 42} it returns ErrUnsuitableValueType, v is used by unsuitable value type.
+// - doc is {c: 10} it returns no error since the path does not exist.
```
Comment (rumyantseva) [inline internal/handlers/common/update_array_operators.go:103]:
```suggestion
// checkUnsuitableValueError returns ErrUnsuitableValueType if 
// if finds an element that contains a non-document value. 
// If it fiends an element that does not exist, it returns nil.
//
// For example, if the path is "v.foo" and
// - doc is {v: 42}, it returns ErrUnsuitableValueType, v is used by unsuitable value type;
// - doc is {c: 10}, it returns no error since the path does not exist.
```

I'm not sure if my doc suggestion is better, so feel free to skip it

**Review by rumyantseva — COMMENTED** [review]
I like the comments and explanations, but I'm not fully convinced it can't be a part of `GetByPath`. Maybe I don't understand some other corner cases. I don't press "request the changes", maybe others would agree with this approach, and then I'm ok to merge it as is. Feel free to schedule a pair programming call with me if it's easier to discuss things synchronously.

**Review by rumyantseva — APPROVED** [review]
After some thinking and experimentation, I actually decided to approve the PR, if we have better ideas around `GetByPath`, we can implement them.

File: internal/handlers/common/update_array_operators.go [hunk 5]
```diff
@@ -53,13 +54,17 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
...
-		if !doc.HasByPath(path) {
-			continue
-		}
-
 		val, err := doc.GetByPath(path)
 		if err != nil {
-			return false, err
+			// If any part of the path exists in doc, pop returns ErrUnsuitableValueType.
+			// Cannot use doc.HasByPath(path) because pop does not error on non-existent
+			// path, pop returns error if other value type exists on part of path.
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go]: Thanks for the suggestion, applied :+1:

File: internal/handlers/common/update_array_operators.go (hunk 4 above)
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go]: I took part of it. Let me know what you think :pray:

File: internal/handlers/common/update_array_operators.go [hunk 6]
```diff
@@ -91,6 +96,44 @@ func processPopArrayUpdateExpression(doc *types.Document, update *types.Document
 	return changed, nil
 }
 
+// checkUnsuitableValueError returns ErrUnsuitableValueType when part of
+// the path is used by non document value type.
+// If path is "v.foo" and
+// - doc is {v: 42} it returns ErrUnsuitableValueType, v is used by unsuitable value type.
+// - doc is {c: 10} it returns no error since the path does not exist.
+func checkUnsuitableValueError(doc *types.Document, key string, path types.Path) error {
```
[the remark this answers is not in the document]
Comment (chilagrow) [reply internal/handlers/common/update_array_operators.go:102]: Thanks for experimenting. I also attempted, but came to the conclusion that `getPath` is sufficiently different. Because `getPath` expects to return error if it does not exist, on the other hand the user case for this is no error if  the path doesn't exist

**Comment by chilagrow** [comment]
Thanks a lot for input everyone :pray:

**Review by w84thesun — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
LGTM
