### PR TITLE
Fix free monitoring tests for MongoDB 6.0.6

### LINKED ISSUE #2735: Fix free monitoring tests for MongoDB 6.0.6
### What should be done?

The free monitoring is no longer available. To reproduce it, make sure to run `task env-pull` to get the 6.0.6 version of mongodb. see #2727. `setFreeMonitoring` seems to function fine, but `getFreeMonitoringStatus` response has deprecated message and `state` is always `disabled`, although it contains `debug` document indicating actual state. Tests should check `debug.state` instead of just `state`.

Example of `disabled` response from MongoDB
```
admin> db.runCommand({setFreeMonitoring: 1, action: "disable"})
{ ok: 1 }
admin> db.runCommand({getFreeMonitoringStatus: 1})
{
  state: 'disabled',
  message: "Free monitoring is deprecated, refer to 'debug' field for actual status",
  debug: {
    state: 'disabled',
    message: 'Free monitoring has been deprecated and is not available for new MongoDB Community instances. For more information on monitoring alternatives, please see https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    url: 'https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    userReminder: 'Free Monitoring URL:\n' +
      'https://cloud.mongodb.com/freemonitoring/cluster/C3RNC7GDDCOCALYKJHFSGTKIU4YWAZQM'
  },
  ok: 1
}
```
Example of `enabled` response from MongoDB
```
admin> db.runCommand({setFreeMonitoring: 1, action: "enable"})
{ ok: 1 }
admin> db.runCommand({getFreeMonitoringStatus: 1})
{
  state: 'disabled',
  message: "Free monitoring is deprecated, refer to 'debug' field for actual status",
  debug: {
    state: 'enabled',
    message: 'Free monitoring has been deprecated and is not available for new MongoDB Community instances. For more information on monitoring alternatives, please see https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    url: 'https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    userReminder: 'Free Monitoring URL:\n' +
      'https://cloud.mongodb.com/freemonitoring/cluster/C3RNC7GDDCOCALYKJHFSGTKIU4YWAZQM'
  },
  ok: 1
}
```

### Where?

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/commands_freemonitoring_test.go#L65-L69

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/commands_freemonitoring_test.go#L70-L74

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

### PR DESCRIPTION
**Pull request by jeremyphua**
# Description

Closes #2735.

## Readiness checklist

- [x] I added/updated unit tests.
- [ ] I added/updated integration/compatibility tests.
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
- [ ] I marked all done items in this checklist.

### CODE REVIEW

File: integration/commands_freemonitoring_test.go [hunk 1]
```diff
@@ -111,7 +111,7 @@ func TestCommandsFreeMonitoringSetFreeMonitoring(t *testing.T) {
 				err := s.Collection.Database().RunCommand(s.Ctx, bson.D{{"getFreeMonitoringStatus", 1}}).Decode(&actual)
 				require.NoError(t, err)
 
-				actualStatus, ok := actual.Map()["state"]
+				actualStatus, ok := actual.Map()["debug"].(bson.D).Map()["state"]
```
Comment (chilagrow) [inline integration/commands_freemonitoring_test.go:114]: Let's make `GOFLAGS='-run=TestCommandsFreeMonitoringSetFreeMonitoring' task test-integration-mongodb` and `GOFLAGS='-run=TestCommandsFreeMonitoringSetFreeMonitoring'  task test-integration-pg` to both pass.

What we could do is that, it can check `actualStatus, ok := actual.Map()["state"]`, and if it's disabled and has `debug` field, we can check debug field to see if it is `enabled`.

We want to make sure that change also works for current version of MongoDB until we update it :hugs: 

Let me know if you need any help :hugs:

**Review by chilagrow — COMMENTED** [review]
Just a comment about this, thanks for the contribution!

File: integration/commands_freemonitoring_test.go (hunk 1 above)
Comment (jeremyphua) [reply integration/commands_freemonitoring_test.go]: Hi! I've made the changes. Not too sure about my approach, let me know if it's okay. Thanks!

File: integration/commands_freemonitoring_test.go [hunk 2]
```diff
@@ -148,6 +148,12 @@ func TestCommandsFreeMonitoringSetFreeMonitoring(t *testing.T) {
 				actualStatus, ok := actual.Map()["state"]
 				require.True(t, ok)
 
+				if actualStatus == "disabled" {
+					if _, ok := actual.Map()["debug"]; ok {
+						actualStatus = actual.Map()["debug"].(bson.D).Map()["state"]
```
Comment (chilagrow) [inline integration/commands_freemonitoring_test.go:153]: Thanks for the change, great solution :hugs: This would work well :+1: I have minor suggestions.

When we read do type assertion such as `.(bson.D)`, if the type is not `bson.D` this case it it would panic. I would suggest `debug, ok := v.(bson.D)` and checking `require.True(t, ok)` to fail the test rather than panic :hugs: By the way, you could assign  `v, ok := actual.Map()["debug"]` to use variable `v` instead.

Also for the last part of `.Map()["state"]`, let's check that `state` field exists similarly to https://github.com/FerretDB/FerretDB/blob/96f304606972c59455fd2c893ccaba1db0461a88/integration/commands_freemonitoring_test.go#L148-L149

File: integration/commands_freemonitoring_test.go (hunk 1 above)
Comment (chilagrow) [reply integration/commands_freemonitoring_test.go]: I like how you did it! I have minor assertion suggestion in another comment

File: integration/commands_freemonitoring_test.go (hunk 2 above)
Comment (jeremyphua) [reply integration/commands_freemonitoring_test.go]: I've made the changes, thanks for the suggestion!

**Review by chilagrow — DISMISSED** [review]
Great work, thanks again for your contribution :rocket:

File: integration/commands_freemonitoring_test.go [hunk 3]
```diff
@@ -148,7 +148,16 @@ func TestCommandsFreeMonitoringSetFreeMonitoring(t *testing.T) {
 				actualStatus, ok := actual.Map()["state"]
 				require.True(t, ok)
 
-				assert.Equal(t, tc.expectedStatus, actualStatus)
```
Comment (rumyantseva) [inline integration/commands_freemonitoring_test.go:151]: So, if `actualStatus` is `disabled`, we get status from `debug.state` and compare it. 
But we don’t do anything if `actualStatus` is not disabled - we don’t compare the results etc. Is it on purpose?

Comment (chilagrow) [reply integration/commands_freemonitoring_test.go:151]: Yes, that is true. See the response of MongoDB on the issue https://github.com/FerretDB/FerretDB/issues/2735. 

> admin> db.runCommand({setFreeMonitoring: 1, action: "enable"})
{ ok: 1 }
admin> db.runCommand({getFreeMonitoringStatus: 1})
{
  state: 'disabled',
  message: "Free monitoring is deprecated, refer to 'debug' field for actual status",
  debug: {
    state: 'enabled',
    message: 'Free monitoring has been deprecated and is not available for new MongoDB Community instances. For more information on monitoring alternatives, please see https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    url: 'https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    userReminder: 'Free Monitoring URL:\n' +
      'https://cloud.mongodb.com/freemonitoring/cluster/C3RNC7GDDCOCALYKJHFSGTKIU4YWAZQM'
  },
  ok: 1
}

The response contains `state: 'disabled` even though within debug `state: 'enabled'`. So just handling for `disabled` is fine.

Comment (rumyantseva) [reply integration/commands_freemonitoring_test.go:151]: Ok! Thanks for the explanation.

**Review by rumyantseva — DISMISSED** [review]
LGTM

**Review by rumyantseva — DISMISSED** [review]
LGTM

**Review by rumyantseva — APPROVED** [review]
:shipit:

File: integration/commands_freemonitoring_test.go (hunk 3 above)
Comment (chilagrow) [reply integration/commands_freemonitoring_test.go:151]: I misunderstood your question, I've pushed a commit to address that https://github.com/FerretDB/FerretDB/pull/2784/commits/6a5728d734a0e81b07c5c104de62c52fe84ca502

@jeremyphua letting you know as well :hugs:

Comment (jeremyphua) [reply integration/commands_freemonitoring_test.go:151]: Thanks for letting me know! I was also looking through the commits and realized I might have made a mistake and the assertion should be outside of the `if` statement.
